### ISSUE TITLE
Plug requires telemetry "~> 0.4.0"

### ISSUE THREAD

**Issue by tomciopp** [elixir-ecto/ecto_sql#100]
There has recently been an update to plug (v1.8.0) and it looks like there is a conflict with the telemetry library for ecto_sql. It looks like everything is up to date in master but a release has not been cut for a while. Is there any way we can get out patch release?

**Comment by wojtekmach** [comment]
I don't think we should bump the requirement in patch release as it would break for people that currently have `telemetry ~> 0.3.0` but maybe it's ok, not sure. Ecto/Ecto SQL v3.1 should be out this week so stay tuned!

**Comment by josevalim** [comment]
Ecto v3.1 coming out soon!

**Comment by josevalim** [comment]
Done!
