### ISSUE TITLE
index names changed between ecto 2.2 and ecto_sql 3.0.5

### ISSUE THREAD

**Issue by mjheilmann** [elixir-ecto/ecto_sql#104]
I am working on migrating a Postgres back-end from Ecto 2.2 to Ecto 3.0.5 (To coincide with the 1.3 Triplex release).  This is for these indices:

From my migration file:
```
create(unique_index(:account, ["(lower(email))"]))
create(unique_index(:account, ["(lower(username))"]))
```

In Ecto 2.2, the index names in postgres are created as:
```
account_lower_username__index
account_lower_email__index
```

But in Ecto 3.0.5, the index names in postgres are created as:
```
account__lower_username_index
account__lower_email_index
```

Please note that the double underscore in the index names moved between the two versions.  Because this is a custom index, I must specify the constraint name in my changeset to handle any violations correctly:

```
    |> unique_constraint(:username, name: :account_lower_username__index)
    |> unique_constraint(:email, name: :account_lower_email__index)
```

Because this is a multi-tenant application, I will have Ecto 2.2 created indexes and Ecto 3.0.5 created indexes being used by the same changeset.

My workaround is to edit my existing migration documents to include the legacy name when creating those indices.  I use:
```
create(unique_index(:account, ["(lower(email))"], name: :account_lower_email__index))
create(unique_index(:account, ["(lower(username))"], name: :account_lower_username__index))
```
And the changesets for current tenant schemas continue to work for new tenants.

Other options would have been to either drop and recreate indices in a migration to get the new naming convention (specifying the old name due to the naming convention change), or to add additional unique constraints to the changesets for all possible index names moving forward.

### Environment

* Elixir version (elixir -v): 1.8.1 on OTP 21
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  Postgres 10.5.1 (docker)
* Ecto version (mix deps): ecto 2.2 to ecto_sql 3.0.5
* Database adapter and version (mix deps): postgrex 0.13.5 to 0.14.1
* Operating system: MacOS 10.14.3

### Current behavior

Index names for a custom index field changed between versions.  Due to multi-tenancy, the unique_constraint in the changeset no longer matches the index names between existing tenants and new tenants.

### Expected behavior

The behavior should be consistent, or noted in the changelog.

**Comment by josevalim** [comment]
We changed the logic here: https://github.com/elixir-ecto/ecto/pull/2331

Unfortunately, if we change the logic again, then 3.1 will be incompatible with 3.0 and that's not an option. So our best option is to update the CHANGELOG for Ecto 3.0. Thank you!

**Comment by mjheilmann** [comment]
Understood.  Thanks!

**Comment by josevalim** [comment]
Btw, I think if you generate the name as:

    create(unique_index(:account, ["lower(email)"]))

Without the double parens in the column name, then it will inflect the same index on both. Ecto v2.2 and v3.0!
