### ISSUE TITLE
Add `table_exists?`

### ISSUE THREAD

**Issue by ulissesalmeida** [elixir-ecto/ecto_sql#109]
We started the discussion about making the `ecto.load` smarter and skip loaded databases. We'll need a function that can check if a table exists.

In Postgres we can check like this:
```
SELECT to_regclass('schema_name.table_name')
```

In MySQL we can check like this:
```
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'yourdb' 
    AND table_name = 'testtable'
LIMIT 1;
```

We thought that we can add this function to `Ecto.Adapters.SQL`, however, I wonder how we can do it?

Today the `Adapters.SQL` has these behaviours:

```
Ecto.Adapter
Ecto.Adapter.Migration
Ecto.Adapter.Queryable
Ecto.Adapter.Schema
Ecto.Adapter.Transaction
```

Wich one should we add the function `table_existence_check_query`?

We have also the 

```
Ecto.Adapter.Migration
Ecto.Adapter.Structure 
```

I'm a little lost where I should put the callback.

## Additional links

The discussion started here: https://groups.google.com/forum/#!topic/elixir-ecto/8aw2DL_c9Yc
The idea of the feature came from here: https://github.com/elixir-ecto/ecto_sql/pull/108

**Comment by josevalim** [comment]
I would put it in `Ecto.Adapter.Structure` and call it `table_exists?`. It should return `true | false`. It should receive the adapter_meta as first argument (as in the other adapter operations). Thoughts?

**Comment by ulissesalmeida** [comment]
I think it should receive the `table_name :: String.t` as second argument
