### ISSUE TITLE
Make it possible to use log functions 

### ISSUE THREAD

**Issue by nulian** [elixir-ecto/ecto_sql#110]
Could it be possible to make the log functions available so you can format the data you receive from telemetry?
I would like to reformat the uuids before printing the logging. 
But since you can no longer update the data you can no longer make use of logging of the printing code from this library.
So now I have to copy all the code from this library with log: false setting. And print the logging myself with this code and all the functions that are referenced in it.

```
Logger.log(
          level,
          fn -> log_iodata(measurements, metadata) end,
          ansi_color: sql_color(query_string)
        )
```

**Comment by josevalim** [comment]
Since we may want to change the log format in any way we want in the future, our recommendation is for you to bring that logic in and handle it in any way you want.
