### ISSUE TITLE
Document that telemetry measures are reported in nanoseconds?

### ISSUE THREAD

**Issue by nathanl** [elixir-ecto/ecto_sql#120]
### Environment

* Elixir version (elixir -v): 1.8.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.2
* Ecto version (mix deps): 3.1.6
* Database adapter and version (mix deps): `ecto_sql 3.1.1` and `postgrex 0.14.0`
* Operating system: MacOS 10.14

### Current behavior

I'm using `ecto 3.1.6`, `ecto_sql 3.1.1` and `postgrex 0.14.0` with PostgreSQL 11.2.

When I add an `IO.inspect` [here](https://github.com/elixir-ecto/ecto_sql/blob/9c839e15bc3722be676aa88736f3b49d359ba193/lib/ecto/adapters/sql.ex#L850), a particular query shows `:query_time` of 2587 μs. But the telemetry measurements reported to my handler show `query_time: 2587000`. So it appears to me that the times are being reported in nanoseconds. I don't see this documented anywhere.

### Expected behavior

I would like to document somewhere that the `measurements` are in nanoseconds, as it took me some puzzling to figure this out. Can someone advise me on where that documentation should go? So far I don't see where these numbers are actually generated.

**Comment by michalmuskala** [comment]
The `measurements` are in a closer unspecified "native" units, that offer the highest resolution on a particular system. You have to convert to real units with `System.convert_time_unit/3`. FWIW this is how almost everything reports time measurements in Elixir, but I agree we should improve the documentation to mention this.

**Comment by nathanl** [comment]
Is `ecto_sql` the right project to document this on, or should the docs go on `postgrex`?

**Comment by nathanl** [comment]
While I'm at it, I'd also like to document the meaning of the keys: `:decode_time, :query_time, :queue_time, :total_time`. I think that:

- `:decode_time` would be the time required for Ecto to build the SQL query
- `:queue_time`, the amount of time waiting to check outon a database connection from the pool
- `:query_time` would be the amount of time to actually run that query once we have a connection
- `:total_time` would be all of the above added up

**Comment by josevalim** [comment]
A PR is welcome! We document those events in Ecto.Repo in the `ecto` repo!

**Comment by josevalim** [comment]
Only one correction: decode_time is the time to decode the data received from the database

**Comment by nathanl** [comment]
Thanks! I will make a PR to add detail on `Ecto.Repo`

**Comment by michalmuskala** [comment]
We could probably largely re-use the documentation of the deprecated `Ecto.LogEntry` struct - most things stayed similar https://hexdocs.pm/ecto/3.0.9/Ecto.LogEntry.html#content

**Comment by nathanl** [comment]
See PR above
