### ISSUE TITLE
Ecto.Adapters.MyXQL.Connection.to_constraints/1 fails to match some constraint errors on MySQL >= 8.0.13

### ISSUE THREAD

**Issue by jbott** [elixir-ecto/ecto_sql#126]
### Environment

* Elixir version (elixir -v): Elixir 1.8.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8.0.16 (but likely reproducible on anything >= 8.0.13)
* Ecto version (mix deps): ecto 3.1.7 / ecto_sql 3.1.6
* Database adapter and version (mix deps): myxql 0.2.6
* Operating system: macOS 10.14.5

### Current behavior

When failing a foreign key constraint, the sql error is raised rather than the expected constraint errors. The error message is:
> (MyXQL.Error) (1216) (ER_NO_REFERENCED_ROW) Cannot add or update a child row: a foreign key constraint fails

### Expected behavior

Foreign key constraint error is returned.

### Additional Info

After some digging, it appears MySQL 8.0.13 changed behavior around foreign key constraints: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-13.html

> Previously, the ER_NO_REFERENCED_ROW_2 and ER_ROW_IS_REFERENCED_2 error messages for foreign key operations were displayed and revealed information about parent tables, even when the user had no parent table access privileges. Error handling for this situation has been revised:
> 
> If the user does have table-level privileges for all parent tables, ER_NO_REFERENCED_ROW_2 and ER_ROW_IS_REFERENCED_2 are displayed, the same as before.
> 
> If the user does not have table-level privileges for all parent tables, more generic error messages are displayed instead (ER_NO_REFERENCED_ROW and ER_ROW_IS_REFERENCED).

It's not immediately clear what "user does have table-level privileges for all parent tables" means. My current grants look like:
```
mysql> show grants FOR 'server';
+--------------------------------------------------------+
| Grants for server@%                                    |
+--------------------------------------------------------+
| GRANT USAGE ON *.* TO `server`@`%`                     |
| GRANT ALL PRIVILEGES ON `server_dev`.* TO `server`@`%` |
+--------------------------------------------------------+
2 rows in set (0.00 sec)
```
I'd expect to see `ER_NO_REFERENCED_ROW_2` in this scenario from the description in the excerpt, but it appears not.

**Comment by josevalim** [comment]
Hi @jbott, good find! Can you please send a PR? There are two ways you can help us:

1. Send a PR that makes MySQL 8.0.13 run on CI so we can see the failure
2. Send a PR that fixes the issue :)

Thank you!

**Comment by jbott** [comment]
It looks like you have MySQL pulling the latest 8.0.x release already, so we should be seeing this behavior on CI. The last travis run ([here](https://travis-ci.org/elixir-ecto/ecto_sql/jobs/558453236)) was run on the same version I reproduced this behavior on locally.
```
+-----------+
| @@version |
+-----------+
| 8.0.16    |
+-----------+
```

I'll try to give a PR a shot.

**Comment by jbott** [comment]
I opened a PR with an integration test that replicates the behavior I saw, but only when MYSQL_URL is modified. Since CI is authenticating to the database as `root`, the test will succeed there. I've documented the commands I used to locally recreate the error in that PR.

I'm not really sure how to resolve this issue though - the current implementation of [to_constraints/1](https://github.com/elixir-ecto/ecto_sql/blob/52f9d27a7ad86442f442bad2f7ebd19ba09ddc61/lib/ecto/adapters/myxql/connection.ex#L45-L60) relies upon parsing the returned error message for the constraint name. However, the new error messages returned do not contain this information. For example, the message in the PR: `"(1216) (ER_NO_REFERENCED_ROW) Cannot add or update a child row: a foreign key constraint fails"`. We can't refine that into a more specific error to inform the user about specific fields that failed validation.

I think next steps are to determine in what cases this error is returned.

It's not clear to me if this is an error caused by how we're structuring our queries (eg: adding the database name to our query would make it return the more fine-grained error) or if it's an issue with permission grants on the default user (I think unlikely, since the docker entrypoint [issues a GRANT ALL on the created database](https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh#L185-L193)).

**Comment by josevalim** [comment]
If the database does not tell us which constraint failed, then I am afraid there is absolutely nothing we can do besides documenting the issue. But you also said this:

> It's not clear to me if this is an error caused by how we're structuring our queries (eg: adding the database name to our query would make it return the more fine-grained error)

If that's the case, a workaround is to do this:

    @schema_prefix MyApp.Repo.config[:database]

This will force the schema to always use that given prefix (i.e. database name) in the queries. But the fact that this error only happens under certain conditions, it makes it look like a permission issue.

**Comment by jbott** [comment]
Looks like the existing tests also produce the same behavior. (not sure how I missed these, lol.)
```
$ ECTO_ADAPTER=myxql MYSQL_URL=mysql:mysql@localhost mix test --only foreign_key_constraint
Excluding tags: [:test, :array_type, :read_after_writes, :returning, :create_index_if_not_exists, :aggregate_filters, :transaction_isolation, :with_conflict_target, :map_boolean_in_expression]
Including tags: [:foreign_key_constraint]



  1) test assoc constraint (Ecto.Integration.RepoTest)
     deps/ecto/integration_test/cases/repo.exs:499
     Expected exception Ecto.ConstraintError but got MyXQL.Error ((1216) (ER_NO_REFERENCED_ROW) Cannot add or update a child row: a foreign key constraint fails)
     code: assert_raise Ecto.ConstraintError, ~r/constraint error when attempting to insert struct/, fn ->
     stacktrace:
       (ecto_sql) lib/ecto/adapters/myxql.ex:208: Ecto.Adapters.MyXQL.insert/6
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       deps/ecto/integration_test/cases/repo.exs:503: (test)



  2) test no assoc constraint error (Ecto.Integration.RepoTest)
     deps/ecto/integration_test/cases/repo.exs:529
     Expected exception Ecto.ConstraintError but got MyXQL.Error ((1217) (ER_ROW_IS_REFERENCED) Cannot delete or update a parent row: a foreign key constraint fails)
     code: assert_raise Ecto.ConstraintError, ~r/constraint error when attempting to delete struct/, fn ->
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:440: anonymous fn/10 in Ecto.Repo.Schema.do_delete/4
       (ecto) lib/ecto/repo/schema.ex:912: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
       (ecto) lib/ecto/repo/schema.ex:190: Ecto.Repo.Schema.delete!/4
       deps/ecto/integration_test/cases/repo.exs:534: (test)



  3) test insert and update with embeds during failing child foreign key (Ecto.Integration.RepoTest)
     deps/ecto/integration_test/cases/repo.exs:573
     ** (MyXQL.Error) (1216) (ER_NO_REFERENCED_ROW) Cannot add or update a child row: a foreign key constraint fails
     code: {:error, changeset} = TestRepo.insert(changeset)
     stacktrace:
       (ecto_sql) lib/ecto/adapters/myxql.ex:208: Ecto.Adapters.MyXQL.insert/6
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/association.ex:929: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto) lib/ecto/association.ex:413: Ecto.Association.on_repo_change/7
       (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/association.ex:392: Ecto.Association.on_repo_change/4
       (ecto) lib/ecto/repo/schema.ex:809: Ecto.Repo.Schema.process_parents/4
       (ecto) lib/ecto/repo/schema.ex:242: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:912: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
       deps/ecto/integration_test/cases/repo.exs:579: (test)



  4) test foreign key constraint (Ecto.Integration.RepoTest)
     deps/ecto/integration_test/cases/repo.exs:468
     Expected exception Ecto.ConstraintError but got MyXQL.Error ((1216) (ER_NO_REFERENCED_ROW) Cannot add or update a child row: a foreign key constraint fails)
     code: assert_raise Ecto.ConstraintError, ~r/constraint error when attempting to insert struct/, fn ->
     stacktrace:
       (ecto_sql) lib/ecto/adapters/myxql.ex:208: Ecto.Adapters.MyXQL.insert/6
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       deps/ecto/integration_test/cases/repo.exs:472: (test)



  5) test no assoc constraint with changeset match (Ecto.Integration.RepoTest)
     deps/ecto/integration_test/cases/repo.exs:560
     ** (MyXQL.Error) (1217) (ER_ROW_IS_REFERENCED) Cannot delete or update a parent row: a foreign key constraint fails
     code: |> TestRepo.delete()
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:440: anonymous fn/10 in Ecto.Repo.Schema.do_delete/4
       (ecto) lib/ecto/repo/schema.ex:912: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
       deps/ecto/integration_test/cases/repo.exs:568: (test)



  6) test no assoc constraint with changeset mismatch (Ecto.Integration.RepoTest)
     deps/ecto/integration_test/cases/repo.exs:543
     Expected exception Ecto.ConstraintError but got MyXQL.Error ((1217) (ER_ROW_IS_REFERENCED) Cannot delete or update a parent row: a foreign key constraint fails)
     code: assert_raise Ecto.ConstraintError, message, fn ->
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:440: anonymous fn/10 in Ecto.Repo.Schema.do_delete/4
       (ecto) lib/ecto/repo/schema.ex:912: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
       deps/ecto/integration_test/cases/repo.exs:549: (test)



Finished in 9.4 seconds
348 tests, 6 failures, 342 excluded

Randomized with seed 93542
```

**Comment by jbott** [comment]
After reading [the patch which introduced this behavior](https://github.com/mysql/mysql-server/commit/f26bc31bd462278866430b6b37c2b02bd2db34d0#diff-4dc2b4a5f5975a9378fc0a5d92a508e5) I did some testing with just the mysql command line:
```
mysql> show grants;
+------------------------------------------------------+
| Grants for mysql@%                                   |
+------------------------------------------------------+
| GRANT USAGE ON *.* TO `mysql`@`%`                    |
| GRANT ALL PRIVILEGES ON `ecto_test`.* TO `mysql`@`%` |
+------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> use `ecto_test`;
Database changed
mysql> SELECT * FROM `posts`;
Empty set (0.01 sec)

mysql> SELECT * FROM `users`;
Empty set (0.00 sec)

mysql> SELECT * FROM `comments`;
Empty set (0.01 sec)

mysql> INSERT INTO `comments` (post_id) VALUES (1);
ERROR 1216 (23000): Cannot add or update a child row: a foreign key constraint fails
mysql> show grants;
+------------------------------------------------------------+
| Grants for mysql@%                                         |
+------------------------------------------------------------+
| GRANT USAGE ON *.* TO `mysql`@`%`                          |
| GRANT ALL PRIVILEGES ON `ecto_test`.* TO `mysql`@`%`       |
| GRANT ALL PRIVILEGES ON `ecto_test`.`users` TO `mysql`@`%` |
+------------------------------------------------------------+
3 rows in set (0.01 sec)
mysql> INSERT INTO `comments` (post_id) VALUES (1);
ERROR 1216 (23000): Cannot add or update a child row: a foreign key constraint fails
mysql> show grants;
+------------------------------------------------------------+
| Grants for mysql@%                                         |
+------------------------------------------------------------+
| GRANT USAGE ON *.* TO `mysql`@`%`                          |
| GRANT ALL PRIVILEGES ON `ecto_test`.* TO `mysql`@`%`       |
| GRANT SELECT ON `ecto_test`.`posts` TO `mysql`@`%`         |
| GRANT ALL PRIVILEGES ON `ecto_test`.`users` TO `mysql`@`%` |
+------------------------------------------------------------+
4 rows in set (0.00 sec)
mysql> INSERT INTO `comments` (post_id) VALUES (1);
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`ecto_test`.`comments`, CONSTRAINT `comments_post_id_fkey` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`))
```

I believe this is incorrect behavior on MySQL's part - it doesn't seem to be checking database level permissions when returning the error message. As soon as any table level permission is present on all referenced tables, the `ER_NO_REFERENCED_ROW_2` error is returned. I'll file a bug with MySQL and see what happens.

**Comment by josevalim** [comment]
Hi @jbott, I will go ahead and close this as it seems there is nothing to be done on Ecto side. Thank you!
