### ISSUE TITLE
Migration warning when `migration_lock: nil`is set

### ISSUE THREAD

**Issue by lucas-nelson** [elixir-ecto/ecto_sql#130]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.3.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 20)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

Postgres 10.7

* Ecto version (mix deps):

```
* ecto 3.1.7 (Hex package) (mix)
  locked at 3.1.7 (ecto) fa21d06e
  ok
```

* Database adapter and version (mix deps):

```
* ecto_sql 3.1.6 (Hex package) (mix)
  locked at 3.1.6 (ecto_sql) 1e80e30d
  ok
```

* Operating system:

MacOS 10.14.6

### Current behavior

App is configured to disable the migration lock: https://github.com/elixir-ecto/ecto_sql/blob/v3.1.6/lib/ecto/migration.ex#L186-L190

```
config :app, App.Repo, migration_lock: nil
```

A migration has a concurrent index creation in it:

```
create(index(:table, [:column], concurrently: true))
```

When the migration is run, we see a warning:

```
warning: Migration App.Migrations.TheMigration has set index `table_column_index` on table `table` to concurrently but did not disable migration lock. Please set:

    use Ecto.Migration
    @disable_migration_lock true
```

### Expected behavior

The documentation in Ecto.Migration states:

```
    * `:migration_lock` - By default, Ecto will lock the migration table. This allows
      multiple nodes to attempt to run migrations at the same time but only one will
      succeed. You can disable the `migration_lock` by setting it to `nil`:
          config :app, App.Repo, migration_lock: nil
```

Which seems to be not true. At least in terms of: but if I do that, I get this scary warning.

Should that doco be removed? Is `@disable_migration_lock true` in each migration file now required?

NOTE: the change seems to me to be from a80f80ef9a46d6ca95dae5c26878bd3369135d11 relating to #115

If I rollback to ecto_sql 3.1.4 the warning goes away.

**Comment by josevalim** [comment]
Yes, this is intentional. You have to use the module attribute. Using the configuration is no longer recommended. It disables too much and later if you decide to no longer set it to nil, your migrations would be broken. Use the module attributes. Thanks!
