### ISSUE TITLE
Binary generated with mix release fails to start

### ISSUE THREAD

**Issue by ikouchiha47** [elixir-ecto/ecto_sql#132]
### Environment

* Elixir version (elixir -v): 1.9.1 
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgresql 10.2
* Ecto version (mix deps): 3.1.7 (ecto) fa21d06e
* Database adapter and version (mix deps): postgrex 0.15.0 (postgrex) dd534916
* Operating system: mac os 10.12

### Current behavior

When I run `_build/.../app/<app_name> start` It crashes with the following error
```
** (EXIT from #PID<0.163.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Code.ensure_loaded?/1
        (elixir) lib/code.ex:1044: Code.ensure_loaded?(20)
        (ecto_sql) lib/ecto/adapters/sql.ex:481: Ecto.Adapters.SQL.normalize_pool/1
        (elixir) lib/keyword.ex:873: Keyword.update/4
        (elixir) lib/keyword.ex:877: Keyword.update/4
        (ecto_sql) lib/ecto/adapters/sql.ex:459: Ecto.Adapters.SQL.init/3
        (ecto) lib/ecto/repo/supervisor.ex:162: Ecto.Repo.Supervisor.init/1
        (stdlib) supervisor.erl:295: :supervisor.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
```

I looked at the codebase https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/sql.ex#L438 this expects a connection where as I am getting a number.

But the app runs fine when run like `mix run --no-halt`
Code repository https://github.com/ikouchiha47/shorty

Run `ENV=prod mix release shorty` and then `<generate binary> start`

### Expected behavior

It runs without crashing

**Comment by wojtekmach** [comment]
Change

```elixir
  pool: 20,
```

to:

```elixir
  pool_size: 20,
```

and you should be good to go!

**Comment by wojtekmach** [comment]
And thanks for providing example app https://github.com/ikouchiha47/shorty/blob/master/config/releases.exs#L8, it was incredibly useful to solve the issue quickly.

**Comment by ikouchiha47** [comment]
Thanks :))) such a bad mistake
