### ISSUE TITLE
Cannot rollback to a savepoint once an error in a transaction occured

### ISSUE THREAD

**Issue by dkulchenko** [elixir-ecto/ecto_sql#136]
### Environment

* Elixir version (elixir -v): 1.9.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11
* Ecto version (mix deps): 3.1.7
* Database adapter and version (mix deps): postgrex 0.14.3
* Operating system: Ubuntu 18.04 LTS

### Current behavior

I'm looking to make heavy use of savepoints inside of transactions to allow potentially failing SQL statements to attempt to run, then roll back to a valid savepoint in case the statement fails.

But running an Ecto query that has a SQL error and then issuing a `Repo.query!("ROLLBACK TO SAVEPOINT xyz")` to bring the transaction back into a valid state doesn't work:

```
[error] Postgrex.Protocol (#PID<0.396.0>) disconnected: ** (DBConnection.ConnectionError) transaction rolling back    
[error] Task #PID<0.561.0> started from #PID<0.558.0> terminating     
** (DBConnection.ConnectionError) transaction rolling back                                                                
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1                                      
    (kiwi) lib/kiwi/repo.ex:131: Kiwi.Repo.wrap_in_savepoint/1                                                              (kiwi) lib/kiwi/addresses.ex:112: anonymous fn/2 in Kiwi.Addresses.create_returning_immutable/2                         
    (ecto_sql) lib/ecto/adapters/sql.ex:890: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:804: DBConnection.transaction/3                                            
    (kiwi) lib/kiwi/addresses.ex:108: Kiwi.Addresses.create_returning_immutable/2
    (kiwi) lib/kiwi/addresses.ex:88: anonymous fn/4 in Kiwi.Addresses.fetch_or_create_address/3
    (ecto_sql) lib/ecto/adapters/sql.ex:890: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
```

So it seems the connection gets marked as aborted (and doesn't allow the rollback query to go through) even though it's still recoverable: a similar sequence works as expected in a psql prompt:

```
kiwi_dev=# begin;
BEGIN
kiwi_dev=# savepoint xyz;
SAVEPOINT
kiwi_dev=# random invalid sql syntax;
ERROR:  syntax error at or near "random"
LINE 1: random invalid sql syntax;
        ^
kiwi_dev=# select count(*) from immutable_addresses;
ERROR:  current transaction is aborted, commands ignored until end of transaction block
kiwi_dev=# rollback to savepoint xyz;
ROLLBACK
kiwi_dev=# select count(*) from immutable_addresses;
 count 
-------
     2
(1 row)

kiwi_dev=# commit;
COMMIT
kiwi_dev=# 
```

**Comment by josevalim** [comment]
We don’t officially support save points, so when you run the save point query, we think it is a regular query and therefore we fail, because running any query except the save point query at that moment would be an error. We have no plans to work in save points, but if you want to work on it, PR would be appreciated. I would first try to make it work on Postgrex (which should likely be enough).

**Comment by dkulchenko** [comment]
@josevalim Totally understood on the save points, and I certainly don't expect high-level Ecto support for them (though am definitely open to working on a PR). But I'm a bit puzzled as to how having no feasible way of executing an otherwise valid Postgres query using ecto_sql/postgrex isn't considered a bug :/

**Comment by josevalim** [comment]
@dkulchenko we can consider it a bug, that's fine. :) the outcome is still the same though, we are limited on time, so unless there is a PR, it is unlikely we will be able to work on it. sorry.

**Comment by josevalim** [comment]
And to be clear, it is most likely a potsgrex bug, so I would reproduce the problem there first!

**Comment by dkulchenko** [comment]
@josevalim Figured out the issue :)

Turns out it had nothing to do with db_connection or postgrex or ecto-sql after all, but with `wrap_in_transaction` in ecto/repo/schema.ex. 

If the insert has any relations/embeds, `wrap_in_transaction` creates a transaction and rolls back on any error, while if the insert doesn't have any embeds, it doesn't do so and just calls it as-is. So the after-failure savepoint query works just fine after a simple failed insert call in Ecto, but not with more complex ones (because those have an implicit transaction rollback on error, which bubbles up). This can be worked around by adding `skip_transaction: true` to the insert call.

I wrote a PR for not adding an additional transaction in wrap_in_transaction if we're already in a transaction (to allow the parent transaction to do its own handling), but it's not a backwards compatible change, so will sit on it for now.

**Comment by josevalim** [comment]
Great, thanks for investigating!

> I wrote a PR for not adding an additional transaction in wrap_in_transaction if we're already in a transaction (to allow the parent transaction to do its own handling), but it's not a backwards compatible change, so will sit on it for now.

Why it isn't backwards compatible?

**Comment by dkulchenko** [comment]
> Why it isn't backwards compatible?

Good point - I was worried about people with outer transactions relying on the implicit rollback in the `insert`, but I just did some tests and the insert behaves identically in one case or another, returning the same error and changeset. Plus the outer transaction will be considered tainted after an error regardless, so there shouldn't be an incompatibility. PR filed :)

**Comment by josevalim** [comment]
@dkulchenko thanks. I will still think this will be a breaking change but I wanted to hear from you if i was missing other cases, I will comment on the PR. :)
