### ISSUE TITLE
Missing v3.2.0 release in github repo

### ISSUE THREAD

**Issue by lucas-nelson** [elixir-ecto/ecto_sql#138]
Apologies if this is a poor way to communicate about this, but a 3.2.0 release has been [published to hex.pm](https://hex.pm/packages/ecto_sql/3.2.0) without a [new release](https://github.com/elixir-ecto/ecto_sql/releases) or tag being created in this github repo.

Is the hex.pm release legit?

**Comment by josevalim** [comment]
My bad, pushed now!

**Comment by isaacsanders** [comment]
Also, @josevalim, did you release this version without the tests passing?

**Comment by josevalim** [comment]
We need to update CI machines. A PR would be very appreciated, thank you.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Or even better, if someone can move to GitHub Actions, it would be awesome!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
