### ISSUE TITLE
MySQL Adapter removed in minor release 3.2.0

### ISSUE THREAD

**Issue by hauptbenutzer** [elixir-ecto/ecto_sql#141]
Hi! 

As https://github.com/elixir-ecto/ecto_sql/pull/117 has been merged into master, the MySQL adapter is entirely gone in 3.2.0. The adapter was deprecated in 3.1.5 but the complete removal is not mentioned in the changelog. Is this an oversight or was the removal premature?

**Comment by josevalim** [comment]
Hi @hauptbenutzer!

When we released Ecto 3.0, we announced that it became stable API and the only remaining backwards incompatible change was the removal of Mariaex in favor of MyXQL. The MyXQL driver has been available for quite a while for testing and also safe for a while for use.

In any case, you are correct, it doesn't hurt to further clarify things in the v3.2.0 changelog. We will fix it. Thank you.

**Comment by hauptbenutzer** [comment]
Thanks for the quick response and the clarification!

Cheers
