### ISSUE TITLE
Migration flush does not work

### ISSUE THREAD

**Issue by turion** [elixir-ecto/ecto_sql#144]
### Environment

* Elixir version (elixir -v): Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): CockroachDB OSS v2.1.5
* Ecto version (mix deps):
```
$ mix deps | grep ecto
* ecto 3.1.7 (Hex package) (mix)
  locked at 3.1.7 (ecto) fa21d06e
* ecto_sql 3.1.6 (Hex package) (mix)
  locked at 3.1.6 (ecto_sql) 1e80e30d
* ecto_cockroachdb 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (ecto_cockroachdb) 221cf5ac
```
* Operating system: NixOS unstable

### Bug

Let's assume I write the following migration:

```
defmodule Repo.Migrations.Test do
  use Ecto.Migration

  def up do
    create table("test") do
      add :test, :integer
    end
    flush()
    rename table("test"), :test, to: :test2
    flush()
    alter table("test") do
      add :test, :integer
    end
  end

  def down do
    alter table("test") do
      remove :test
    end
    flush()
    rename table("test"), :test2, to: :test
    flush()
    drop table("test")
  end
end
```
I can run it up:

```
$ mix ecto.migrate --to=20190916150901 --log-sql=true
15:15:44.462 [info]  == Running 20190916150901 Repo.Migrations.Test.up/0 forward

15:15:44.462 [info]  create table test

15:15:44.471 [debug] QUERY OK db=8.5ms
CREATE TABLE "test" ("id" bigserial, "test" integer, PRIMARY KEY ("id")) []

15:15:44.471 [info]  rename column test to test2 on table test

15:15:44.474 [debug] QUERY OK db=2.2ms
ALTER TABLE "test" RENAME "test" TO "test2" []

15:15:44.474 [info]  alter table test

15:15:44.481 [debug] QUERY OK db=7.3ms
ALTER TABLE "test" ADD COLUMN "test" integer []

15:15:44.483 [info]  == Migrated 20190916150901 in 0.0s
```
But rollback fails:
```
$ mix ecto.rollback --log-sql=true
15:16:08.352 [info]  == Running 20190916150901 Repo.Migrations.Test.down/0 forward

15:16:08.353 [info]  alter table test

15:16:08.356 [debug] QUERY OK db=2.5ms
ALTER TABLE "test" DROP COLUMN "test" []

15:16:08.356 [info]  rename column test2 to test on table test

15:16:08.378 [debug] QUERY ERROR db=21.8ms
ALTER TABLE "test" RENAME "test2" TO "test" []
** (Postgrex.Error) ERROR XX000 (internal_error) column name "test" already exists
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
    priv/repo/migrations/20190916150901_test.exs:24: Repo.Migrations.Test.down/0
```
I believe that somehow `flush` does not work as expected, and the `test` column is not actually deleted before `test2` is renamed to `test`.

**Comment by josevalim** [comment]
Thanks @turion for the report! Can you please do a quick check using Postgres just to make sure this is not a cockroach DB issue? Thanks!

**Comment by turion** [comment]
Good point. Seems like this is a cockroach issue.

I tried and ran the commands through a cockroach prompt and I found the following:

```
#
root@127.0.0.1:26257/defaultdb> CREATE TABLE "test" ("id" bigserial, "test" integer, PRIMARY KEY ("id"));
CREATE TABLE

Time: 24.086524ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test" TO "test2";
RENAME COLUMN

Time: 48.405945ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" ADD COLUMN "test" integer;
ALTER TABLE

Time: 157.332251ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" DROP COLUMN "test";
pq: rejected: ALTER TABLE DROP COLUMN will remove all data in that column (sql_safe_updates = true)
root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test2" TO "test";
pq: column name "test" already exists
```

So already in the `DROP COLUMN` statement, there is an error. I find it strange that this error is not rethrown through ecto, but the second one is.

Here is what happens if I switch safe updates off:

```
root@127.0.0.1:26257/defaultdb> SET sql_safe_updates = FALSE;
SET

Time: 876.383µs

root@127.0.0.1:26257/defaultdb> drop table "test";
DROP TABLE

Time: 79.801373ms

root@127.0.0.1:26257/defaultdb> CREATE TABLE "test" ("id" bigserial, "test" integer, PRIMARY KEY ("id"));
CREATE TABLE

Time: 23.327178ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test" TO "test2";
RENAME COLUMN

Time: 33.827897ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" ADD COLUMN "test" integer;
ALTER TABLE

Time: 138.131865ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" DROP COLUMN "test";
ALTER TABLE

Time: 216.117307ms

root@127.0.0.1:26257/defaultdb> ALTER TABLE "test" RENAME "test2" TO "test";
RENAME COLUMN

Time: 116.083427ms
```

So it seems like this is more an issue of https://github.com/jumpn/ecto_cockroachdb/?

**Comment by turion** [comment]
The two resolutions I could see are:

* Switch safe updates _off_ in the Cockroach adapter by default
* Make sure the above error message becomes visible to the user, and make safe updates configurable

**Comment by josevalim** [comment]
@turion I am not sure what "safe updates" do but from a glance turning it off sounds by default sounds like a bad idea. :D

I would suggest at least to document this limitation in their README and provide a configuration as you said. Can you please report the issue on the adapter side of things? Then if the maintainers there believe some work is necessary on `ecto_sql`, they are welcome to follow up or open up a new issue here. Thanks!

**Comment by turion** [comment]
The default in cockroach is to disable `drop table`, `alter table drop column`, unrestricted `delete`, and other destructive writes. See for example https://github.com/cockroachdb/cockroach/pull/17889. The CLI says:
```
$ cockroach sql --help

Open a sql shell running against a cockroach database.
[...]       
      --safe-updates                                                        
        Disable SQL statements that may have undesired side effects. For
        example a DELETE or UPDATE without a WHERE clause. By default,
        this setting is enabled (true) and such statements are rejected to
        prevent accidents. This can also be overridden in a session with SET
        sql_safe_updates = FALSE.
[...]
```
One has to specifically disable safe updates when performing any `DROP` statement.

Still, I think an issue for `ecto_sql` is that the error message upon a failing update does not get propagated at all.

**Comment by turion** [comment]
I created https://github.com/jumpn/ecto_cockroachdb/issues/2 to see whether we can solve this on the cockroach side.

**Comment by josevalim** [comment]
> Still, I think an issue for ecto_sql is that the error message upon a failing update does not get propagated at all.

The control over how migrations are executed and handling of the data returned by the database are completely to the adapter, so unless there is more information that it i indeed an `ecto_sql` issue, it is most likely that this is indeed an adapter behaviour. Thanks for filling up the issue there.
