### ISSUE TITLE
Update performance differs greatly from pgbench results

### ISSUE THREAD

**Issue by scouten** [elixir-ecto/ecto_sql#148]
### Environment

* Elixir version (elixir -v): 1.9.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11.5
* Ecto version (mix deps): 3.2.0
* Database adapter and version (mix deps): Postgrex 0.15.0
* Operating system: Mac OS X 10.14.6

### Current behavior

Please see https://github.com/scouten/pghr#update-item-benchmark-using-raw-sql-update.

This repo includes code samples and instructions for reproducing the results I've observed.

Highlight:

   ips | seed size | duration | Comments
------:|----------:|---------:|:---
  6311 |       500 |       30 | Ecto
  1781 |      5000 |       30 |
  0200 |     50000 |       30 |
  0021 |    500000 |       30 |
 27972 |       500 |       30 | pgbench
 27486 |      5000 |       30 |
 26466 |     50000 |       30 |
 26309 |    500000 |       30 |

When running the test using `pgbench`, performance shows a very, very slight decline as I seed the table with more rows.

When running the test using Ecto – **running the exact same SQL query using the exact same schema** – performance falls off almost proportionally to table size.

It feels as though somehow Ecto (or one of its dependencies) is preventing Postgres from using the primary key in the search.

### Expected behavior

Performance characteristics similar to that observed via `pgbench`. (Maybe there's an absolute constant difference, but the O-notation description of the algorithm should be the same.)

**Comment by scouten** [comment]
FWIW I do _not_ see a similar performance fall-off when doing _creates_ using Ecto: https://github.com/scouten/pghr#create-item-benchmark.

**Comment by josevalim** [comment]
Your pgbench command for updates is wrong, can you please update it to the one you are actually running and include the full pgbench outcome? Thanks.

**Comment by josevalim** [comment]
The name of the Elixir script that you are using does not exist also.

**Comment by josevalim** [comment]
Anyway, I was able to run your benchmarks, here is your linear operation: 

https://github.com/scouten/pghr/blob/master/bench/update_item_sql.exs#L32

Use `:rand.uniform(5000)` and clean tables, as you do for pghr, and I got times close to pgbench.

Also, you want to reduce the pool size, a large pool size means less re-use of the query cache, and you want to make it at least match pgbench and you may want to set both of them to use prepared queries.

**Comment by scouten** [comment]
Derp. You are correct. I'm not quite at `pgbench` numbers, but removing the `Enum.random` did make perf consistent across table sizes. I am sorry for the false alarm.
