### ISSUE TITLE
Union with subqueries returns wrong result

### ISSUE THREAD

**Issue by samphilipd** [elixir-ecto/ecto_sql#155]
On ecto_sql 3.1.0 I get a different result executing a query with Ecto compared to the raw SQL.

Here is the query struct:

```
#Ecto.Query<from r0 in subquery(from r0 in "roles",
  join: c1 in "candidate_role_interest",
  on: c1.role_id == r0.id and c1.candidate_id == ^57505,
  where: is_nil(r0.closed_date) and not(is_nil(r0.published_at)),
  order_by: [desc: c1.inserted_at],
  limit: 1,
  select: %{id: r0.id, ordinality: 1}),
 union: (from r0 in subquery(from r0 in "roles",
  join: c1 in "candidates_role_types",
  on: c1.role_type_id == r0.role_type_id and c1.candidate_id == ^57505,
  where: is_nil(r0.closed_date) and not(is_nil(r0.published_at)),
  order_by: [asc: fragment("RANDOM()")],
  select: %{id: r0.id, ordinality: 2}))>
```

Here is the raw SQL (as logged by Ecto):

```sql
SELECT
  s0."id",
  s0."ordinality" 
FROM
  (
    SELECT
      r0."id" AS "id",
      1 AS "ordinality" 
    FROM
      "roles" AS r0 
      INNER JOIN
        "candidate_role_interest" AS c1 
        ON (c1."role_id" = r0."id") 
        AND 
        (
          c1."candidate_id" = $1
        )
    WHERE
      (
        r0."closed_date" IS NULL 
        AND NOT (r0."published_at" IS NULL)
      )
    ORDER BY
      c1."inserted_at" DESC LIMIT 1
  )
  AS s0 
UNION
(
SELECT
  s0."id", s0."ordinality" 
FROM
  (
    SELECT
      r0."id" AS "id",
      2 AS "ordinality" 
    FROM
      "roles" AS r0 
      INNER JOIN
        "candidates_role_types" AS c1 
        ON (c1."role_type_id" = r0."role_type_id") 
        AND 
        (
          c1."candidate_id" = $2
        )
    WHERE
      (
        r0."closed_date" IS NULL 
        AND NOT (r0."published_at" IS NULL)
      )
    ORDER BY
      RANDOM()
  )
  AS s0)
-- [57505, 57505]
```

It seems like the ordinality is not getting selected propertly. I get the wrong result if I execute this query using the struct compared to the raw SQL.

```
iex> Repo.all(q)
[
  %{id: 24493, ordinality: 1},
  %{id: 24494, ordinality: 1},
  %{id: 24495, ordinality: 1},
  %{id: 24497, ordinality: 1}
]
```

But this is incorrect. Here is the result from executing the raw SQL:

```
iex> Ecto.Adapters.SQL.query!(Repo, sql_string, [57505, 57505])
%Postgrex.Result{
  columns: ["id", "ordinality"],
  command: :select,
  connection_id: 4394,
  messages: [],
  num_rows: 4,
  rows: [[24493, 2], [24494, 2], [24495, 2], [24497, 1]]
}
```

Note that three of the rows have ordinality 2, as expected.

**Comment by josevalim** [comment]
Thanks for the report. For us to move this forward, can you please:

1. Check if this issue still happens on v3.2?
2. Provide a minimal app or a failing test case that reproduces the error?

**Comment by samphilipd** [comment]
Hi Jose, yup this still happens on v3.2.

I'll attempt to create a minimal test case now.

**Comment by josevalim** [comment]
That would be in the Ecto repo, see the `integration_test` folder. The README for this repo has some information on how to run them. Basically `ECTO_PATH=../local/ecto mix test.all`.

**Comment by josevalim** [comment]
Ping!

**Comment by samphilipd** [comment]
Thanks for following up @josevalim .

I tried this but I can't get the tests to work:

```
ECTO_ADAPTER=pg ECTO_PATH=../ecto mix test.all # in ecto_sql
==> Running tests for ECTO_ADAPTER=pg mix test
** (MatchError) no match of right hand side value: {:error, :already_up}
    integration_test/pg/test_helper.exs:69: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by josevalim** [comment]
It is most likely something with your PG credentials. Here is what we use by default:

https://github.com/elixir-ecto/ecto_sql/blob/master/integration_test/pg/test_helper.exs#L10

You can set a different PG_URL if you have different user+pass.

**Comment by Eiji7** [comment]
@samphilipd Following @josevalim here are some examples:

1. Standard `PostgreSQL` installation
The default username is `postgres`. By default authentication is set to `ident` which means that current OS username is compared to allowed database username(s) and therefore there is no password set.
```bash
ECTO_ADAPTER="pg" ECTO_PATH="../ECTO" PG_URL="postgres:@127.0.0.1` mix test.all
```
Source: https://www.liquidweb.com/kb/what-is-the-default-password-for-postgresql/

2. An `asdf` installation using `postgres` plug-in.
In this way instead of `postgres` user you need to give your `Linux` user name as `initdb` called by `asdf` does not specify a `-U postgres`. In `BASH` current user name is stored under `USER` variable which simplifies it a bit. This installation also does not sets a default password.
```bash
ECTO_ADAPTER="pg" ECTO_PATH="../ECTO" PG_URL="$USER:@127.0.0.1` mix test.all
```
Source: https://github.com/smashedtoatoms/asdf-postgres/blob/a542375d228a478c55c18d938acae824ff473b99/bin/install#L37

**NOTE**: As you can see if there is no password set then you simply leave password part blank, so your url becomes: `username:@address` instead of `username:password@address`. That was confusing for me at start too, so hope it helps.

**Comment by samphilipd** [comment]
Thanks @Eiji7 now I get a new error:

`PG_URL="sam:@localhost" ECTO_ADAPTER=pg ECTO_PATH=../ecto mix test.all`

gives lots of these, among others:

`psql: FATAL:  database "sam" does not exist`

I tried to specify the DB but this doesn't work either:

`PG_URL="sam:@localhost/ecto_test"`

**Comment by samphilipd** [comment]
This is still the closest I've gotten to getting it working:

```
PG_URL="postgres:@localhost" ECTO_ADAPTER=pg ECTO_PATH=../ecto mix test.all
Excluding tags: [:without_conflict_target]

......................................................................................................................................................................................................................................................................................................................................................................

Finished in 13.6 seconds
363 tests, 0 failures, 5 excluded

Randomized with seed 158680
==> Running tests for ECTO_ADAPTER=pg mix test
** (MatchError) no match of right hand side value: {:error, :already_up}
    integration_test/pg/test_helper.exs:69: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
==> Running tests for ECTO_ADAPTER=myxql mix test

11:15:16.229 [error] GenServer #PID<0.266.0> terminating
** (DBConnection.ConnectionError) connection refused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil

11:15:16.231 [error] GenServer #PID<0.273.0> terminating
** (DBConnection.ConnectionError) connection refused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (MatchError) no match of right hand side value: {:error, %RuntimeError{message: "killed"}}
    integration_test/myxql/test_helper.exs:71: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by Eiji7** [comment]
> gives lots of these, among others:
> 
> `psql: FATAL: database "sam" does not exist`

@samphilipd Sorry, I forgot to mention that with `asdf` there is no database with same username created. You need to enter `psql` shell and paste this code:
```sql
create database "sam" with owner "sam" encoding 'UTF8' LC_COLLATE = 'pl_PL.UTF-8' LC_CTYPE = 'pl_PL.UTF-8' TEMPLATE template0;
```
It creates a database required by `ecto` tests.

**Comment by josevalim** [comment]
If setting up the repo is tricky, then reproducing the error in a sample
app is totally fine and we can port the test to this git repo when we work
on a fix too.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Eiji7** [comment]
@josevalim There is only a matter to know defaults in both cases and create database. There were no other things I was need to do in `asdf` installation.

**Comment by samphilipd** [comment]
@Eiji7 I'm not using asdf to install postgres, I used brew. And the database details _are_ correct - something else is failing.

**Comment by Eiji7** [comment]
@samphilipd Please take a look which part of your message I quoted and my answer is correct for them.

Also I got how you have that error and it's really weird.

@josevalim I did not test this way before, but when calling `mix test.all` with correct credentials gives me errors as well:
```elixir
$ PG_URL="$USER:@127.0.0.1" ECTO_ADAPTER=pg mix test.all
Excluding tags: [:without_conflict_target]

...................................................................................................................................................................................................................................................................................................................................................................

Finished in 17.3 seconds
360 tests, 0 failures, 5 excluded

Randomized with seed 814764
==> Running tests for ECTO_ADAPTER=pg mix test
** (MatchError) no match of right hand side value: {:error, :already_up}
    integration_test/pg/test_helper.exs:69: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
==> Running tests for ECTO_ADAPTER=myxql mix test

15:04:19.701 [error] GenServer #PID<0.251.0> terminating
** (DBConnection.ConnectionError) connection refused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil

15:04:19.704 [error] GenServer #PID<0.258.0> terminating
** (DBConnection.ConnectionError) connection refused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (MatchError) no match of right hand side value: {:error, %RuntimeError{message: "killed"}}
    integration_test/myxql/test_helper.exs:71: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
```
Also sometimes I have:
```elixir
15:04:06.692 [info]  Postgrex.Protocol (#PID<0.293.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1563.0> exited

15:04:06.692 [info]  Postgrex.Protocol (#PID<0.290.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1562.0> exited
```
in the middle of those dots:
```elixir
PG_URL="$USER:@127.0.0.1" ECTO_ADAPTER=pg mix test.all
Excluding tags: [:without_conflict_target]

.......................................................................................................................................................................................................................................................................................................................................................
15:04:06.692 [info]  Postgrex.Protocol (#PID<0.293.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1563.0> exited

15:04:06.692 [info]  Postgrex.Protocol (#PID<0.290.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1562.0> exited
............

Finished in 17.3 seconds
360 tests, 0 failures, 5 excluded

Randomized with seed 814764
==> Running tests for ECTO_ADAPTER=pg mix test
** (MatchError) no match of right hand side value: {:error, :already_up}
    integration_test/pg/test_helper.exs:69: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
==> Running tests for ECTO_ADAPTER=myxql mix test

15:04:19.701 [error] GenServer #PID<0.251.0> terminating
** (DBConnection.ConnectionError) connection refused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil

15:04:19.704 [error] GenServer #PID<0.258.0> terminating
** (DBConnection.ConnectionError) connection refused
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
** (MatchError) no match of right hand side value: {:error, %RuntimeError{message: "killed"}}
    integration_test/myxql/test_helper.exs:71: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
```

@samphilipd Please call `mix test` instead of `mix test.all` as `test.all` gives me unexpected error as well.

**Comment by Eiji7** [comment]
@josevalim Ah, that error message makes completely sense for me.

Please simply take a look at this line:
https://github.com/elixir-ecto/ecto_sql/blob/e2d484320e91621fb90105de9106aed980c34cc9/mix.exs#L24
and what happens on `mix test.adapters`:
https://github.com/elixir-ecto/ecto_sql/blob/e2d484320e91621fb90105de9106aed980c34cc9/mix.exs#L105-L123

This means that `mix test` task is called twice, so if there is a migration test then it would be "already up" as error says. With our tests it should always fail in such case.

**Comment by samphilipd** [comment]
This doesn't run the integration tests AFAICT - which are the only ones I care about here

**Comment by josevalim** [comment]
@samphilipd setting ECTO_ADAPTER=pg runs the integration tests for PG.

**Comment by Eiji7** [comment]
@samphilipd This runs normal unit tests:
```elixir
ECTO_PATH=../ecto mix test
```
This runs integration tests for `PostgreSQL`:
```elixir
PG_URL="postgres:@localhost" ECTO_ADAPTER=pg ECTO_PATH=../ecto mix test
```
This runs normal unit tests and integration tests for all adapters:
```
PG_URL="postgres:@localhost" ECTO_PATH=../ecto mix test.all
```

Please notice the line I linked in my previous post. Only `ECTO_ADAPTER` environment variable determines if we are running normal tests or integration tests. Also there is an alias for testing both normal tests and integration tests, but that works as expected only when you not specify `ECTO_ADAPTER` environment variable.

**Comment by samphilipd** [comment]
@Eiji7 I can't understand what I am doing wrong because it is not running the integration tests.

I have added a new test in `ecto` called `Ecto.Integration.UnionsTest` and it is not running.

**Comment by Eiji7** [comment]
@samphilipd Heh, if what I think you do is correct then it's 100% correct behaviour. :smiley:

You probably added `Ecto.Integration.UnionsTest` inside `ECTO_SQL_MAIN_DIR/test` instead of `ECTO_SQL_MAIN_DIR/integration_test/pg/unions_test.exs`. Also please notice the extension `exs` - this is really important as by default `ExUnit` is searching in `test_paths` (default: `APP_MAIN_DIR/test`) directory which could be changed in `mix.exs`, but only for all files which names ends with `_test` and have extension `.exs` - not `.ex`.

Also I believe that @josevalim would like to have this test in standard unit tests instead of `integration_test` (I think that's similar to my last PR in which I moved test).

At end you do not need to add any code to `ecto` or `ecto_sql` project. You can simply create a test on new `ecto`-based project. Other contributors would take care of making it work inside `ecto` or `ecto_sql` project.

**Comment by samphilipd** [comment]
I thought the integration test had to go in `ecto`? As Jose said:

> That would be in the Ecto repo, see the integration_test folder. The README for this repo has some information on how to run them. Basically ECTO_PATH=../local/ecto mix test.all.

**Comment by samphilipd** [comment]
The file I created is `ecto/integration_test/cases/unions.exs`

**Comment by josevalim** [comment]
That is good, yes, you would need to require it here: https://github.com/elixir-ecto/ecto_sql/blob/master/integration_test/pg/all_test.exs

Since the goal for now is simply to reproduce the issue ahough, I would add it to `ecto_sql` as it will be much easier. And then after we reproduce it, we move it to the proper place. For example, if we can extract a unit test out of it, that would be preferrable.

**Comment by samphilipd** [comment]
I managed to add it to ecto - see:

https://github.com/elixir-ecto/ecto/pull/3160

**Comment by josevalim** [comment]
Thanks! Once it was reproduced, fixing it was a breeze!
