### ISSUE TITLE
Migration change, ecto.rollback and flush problem 

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto_sql#157]
This situation happen to me when working with reversible migrations, so instead of `down`, `execute/1` and `up` I was simply using `change` and `execute/2`. I noticed that one part requires first to be finished, so I was in need to add `flush()` call. With `ecto.migrate` there was no problem. In `ecto.rollback` commands were althrough in reverted order, but not as I imagined …

When I had `first part` of migration, `flush()` call and `second part` of migration then after using `ecto.revert` I got reversed `first part` of migration, `flush()` call and reversed `second part` of migration. Should it not be like: reversed `second part` of migration, `flush()` call and reversed `first part` of migration instead? That's how I understood it after reading documentation.

In order words `flush()` in `ecto.rollback` task works like `flush()` in `ecto.migrate` task, but each part (separated by `flush` call) have reversed commands and the parts are executed with not reversed order (like in `ecto.migrate`).

This is really easily reproducable by such simple migration:

```elixir
defmodule Example.Repo.Migrations.Test do
  use Ecto.Migration

  @migrate_first "select 'first part of ecto.migrate';"
  @migrate_second "select 'second part of ecto.migrate';"
  @rollback_first "select 'first part of rollback.migrate';"
  @rollback_second "select 'second part of rollback.migrate';"

  def change do
    execute(@migrate_first, @rollback_second)
    flush()
    execute(@migrate_second, @rollback_first)
  end
end
```

Output with `flush()` call commented:
```elixir
$ mix ecto.migrate
05:14:25.060 [info]  == Running 20191028033147 Example.Repo.Migrations.Test.change/0 forward

05:14:25.063 [info]  execute "select 'first part of ecto.migrate';"

05:14:25.064 [info]  execute "select 'second part of ecto.migrate';"

05:14:25.067 [info]  == Migrated 20191028033147 in 0.0s

$ mix ecto.rollback
05:14:25.166 [info]  == Running 20191028033147 Example.Repo.Migrations.Test.change/0 backward

05:14:25.166 [info]  execute "select 'first part of rollback.migrate';"

05:14:25.167 [info]  execute "select 'second part of rollback.migrate';"

05:14:25.168 [info]  == Migrated 20191028033147 in 0.0s
```

Output with `flush()` uncommented:
```elixir
$ mix ecto.migrate
05:13:22.580 [info]  == Running 20191028033147 Example.Repo.Migrations.Test.change/0 forward

05:13:22.583 [info]  execute "select 'first part of ecto.migrate';"

05:13:22.584 [info]  execute "select 'second part of ecto.migrate';"

05:13:22.587 [info]  == Migrated 20191028033147 in 0.0s

$ mix ecto.rollback
05:13:22.682 [info]  == Running 20191028033147 Example.Repo.Migrations.Test.change/0 backward

05:13:22.682 [info]  execute "select 'second part of rollback.migrate';"

05:13:22.683 [info]  execute "select 'first part of rollback.migrate';"

05:13:22.684 [info]  == Migrated 20191028033147 in 0.0s
```

I may be wrong, but for me it looks like a bug. What do you think about it?

**Comment by josevalim** [comment]
Definitely a bug, thanks for the report. However, I am not sure if we cacn fix it. `flush` is usually used when you have non-migration commands in your migration and those likely won't work on change+rollback. So perhaps the best option is to make flush() a non reversible command.

**Comment by Eiji7** [comment]
@josevalim The point is that my non-migration commands actually requires `flush()` (or equivalent solution) for having fully reversible migrations. :-)

I'm making some changes in database and I need to fetch something using `Ecto.Migrator.repo()` in the middle of migration.

My library is generating migrations and if `ecto.rollback` would work like `ecto.migrate` then it would be really amazing. This is only one thing which stops me for now from finishing a release candidate of my new library. I have almost complete documentation and now I'm just stuck on last tests.

If there would be a patch then I would be the first who would test it in real use case. As it blocks me from finishing my current library I'm more than ok to help with that.

btw. I made a small research and gave summary in other issue in this repo, but nobody replied to it. Hope I did not made any mistake. :-)

**Comment by josevalim** [comment]
> I'm making some changes in database and I need to fetch something using Ecto.Migrator.repo() in the middle of migration.

That's my point. Whatever you do with Ecto.Migrator.repo won't be included in the reverse/flush instructions correctly. For us to correctly reverse custom code, we would need to reverse the Elixir code in the migration, and that's a non-trivial problem. :)

**Comment by josevalim** [comment]
>  Is there really no way to fix that other than making it non reversible command? If no then I can make a test PR and maybe I could somehow help with implementation fix.

Sure, you could try to implement flush as you describe. However I think once you use it in practice, it won't work as you expect. :) But practice beats theory, so do give it  try!

**Comment by Eiji7** [comment]
@josevalim 
> That's my point. Whatever you do with Ecto.Migrator.repo won't be included in the reverse/flush instructions correctly. For us to correctly reverse custom code, we would need to reverse the Elixir code in the migration, and that's a non-trivial problem. :)

Ah, sorry - now I see. Yeah, I missed that repo calls are not a part of command list …

I'm did not take a look at that part of `ecto_sql` source code, but from what I understand it's like `Ecto.Migrator` stores a list of commands which are called after `change/0` function finishes. So in short: `"Migrator has many commands at run-time"`.

What came to my mind is (let's call it) `step/1` macro which would be exactly between `Migrator` and `commands`, so `"Migrator would have many steps at compile-time and for each step Migrator have many commands at run-time"`. Instead of list of commands `Migrator` could optionally store a list of quoted expressions. `ecto.rollback` would firstly reverse steps list and for each step `Migrator` would collect commands. Then rest is easy as such commands could be reversed like now they are in normal migrations. Basically it would work something like sub-migrations. Since all of them would be quoted we would be able call `flush()` between `Code.eval_quoted/3` calls and therefore simply use `Ecto.Migration.repo()` separately in each step.

```elixir
defmodule Example.Repo.Migrations.Test do
  use Ecto.Migration

  def change do
    step do
      # first part
    end

    step do
      # Migration.Ecto.repo()
      # second part
    end
  end
end
```

The point here is that we would be able to do something like:
```elixir
defmodule Example.Repo.Migrations.Test do
  use Ecto.Migration

  def change do
    MyLib.Migration.first_part(args)
    MyLib.Migration.second_part(args)
  end
end
```
each of such functions would call `step/1` macro.

For sure I could generate multiple migrations for one thing, but going forward we don't need `flush()` at all and I think that's not the point.

It may require lots of work, but I believe that it would definitely increase experience of working with migrations. Please let me know what do you think about it.

**Comment by josevalim** [comment]
Actually, I think the solution is simpler. You most likely don't want to run the repo operation on rollback, so you just need to do something like this:

    if direction == :up do
      ...run the command...
    end

This takes care of the stray Repo operation, now we just need to change flush to flush properly.

**Comment by josevalim** [comment]
Alternatively, you can move the flush to inside the conditional above:

    if direction == :up do
      flush()
      ...run the command...
    end

Then everything should work *today*.

**Comment by Eiji7** [comment]
@josevalim I'm already using it for another part (inserting rows), so I already thought about it. Unfortunately it would not work in my use case.

I thought about my idea and for now this scenario looks best for me:
1. Making a `flush()` non reversible as you said (a quick fix for this issue)
2. Add steps support for `Migrator` (new feature for having reversible migrations with `Ecto.Migration.repo()` calls)
3. Deprecate (of course not "right now") non reversible `flush()` in favor of `step/1` (migration would be flushed automatically between steps, so there is no need for `flush()` API any more).

I'm sure that you have more important things now, but I would like to ask if such scenario looks good for you (i.e. if someone would implement it then would it have a chance to merge) or maybe I missed something. If in theory it's ok for you then I could start work on implementation for 2nd point.

**Comment by josevalim** [comment]
> Unfortunately it would not work in my use case.

Can you please expand on why?

**Comment by Eiji7** [comment]
> Can you please expand on why?

@josevalim Well … I still would like to make a little surprise, so I would describe it in general.

I need to fetch from database few things and depending on them I would generate an `SQL` code (use in `Ecto.Migration.execute/2`) for providing an automated migration and that fetch needs to be inside migration.

Imagine that you have 2 functions: `func_a` and `func_b`. `func_a` is working like a rollback of `func_b` and `func_b` is working like a rollback of `func_a`. Both functions run `Ecto.Migration.execute/2`. Only `func_b` requires `flush()` (or equivalent), so the problem is when I have `func_a` in change which in rollback it works like `func_b` which requires `flush()`, because when in change there is `func_b` then on rollback I have behaviour of `func_a` which does not requires `flush()`.

I can make them non reversible, but it requires more work from developer and more code for extra `up` and `down` migration (`my_lib.gen.migration` task). Of course I can make also separate migration files, so both `func_a` would be always in separated `change`, but that's not the point.

Hope I described it enough.

**Comment by josevalim** [comment]
I see. Going the step routes is ok but I think the proposal can be simpler. You can introduce:

```elixir
step do
  Repo.all(...)
end
```

That is a regular migration commant except stores its contents to be executed later (think of it as `execute` but for code) . But `step` wouldn't accept migration commands inside. So you can't call `execute` inside but you can just call `Repo.query!`, which has the same effect anyway.

**Comment by Eiji7** [comment]
@josevalim So in this form it's ok to make PR or there is something more to discuss?

**Comment by josevalim** [comment]
Please do a PR and let's discuss based on the code.

**Comment by Eiji7** [comment]
Closing in favor of: #158 and #159
