### ISSUE TITLE
CTEs cause a database error when using fields with non-default names

### ISSUE THREAD

**Issue by ccapndave** [elixir-ecto/ecto_sql#161]
### Environment

* Elixir version (elixir -v): 1.9.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8
* Ecto version (mix deps): 3.2.0
* Database adapter and version (mix deps): myxql 0.2.9, ecto_sql 3.2.0
* Operating system: MacOS 10.14.6

### Current behavior

Using a CTE with a schema that has differently named fields in the schema (using `source`) causes the CTE to select wrongly named fields.

Here is an example:

```
  @primary_key {:id, :id, source: :F_GroupID, autogenerate: true}
  schema "T_Groupstructure" do
    field :name, :string, source: :F_GroupName

    # Group hierarchy
    belongs_to :parent, __MODULE__, source: :F_GroupParent
    has_many :children, __MODULE__, foreign_key: :parent_id
  end

  def ancestors_query(%Group{} = group) do
    initial_query =
      Group
      |> where([g], g.id == ^group.id)

    recursion_query =
      Group
      |> join(:inner, [parent], tree in "group_tree", on: parent.parent_id == tree.id)

    ancestors_query = union_all(initial_query, ^recursion_query)

    {"group_tree", Group}
    |> recursive_ctes(true)
    |> with_cte("group_tree", as: ^ancestors_query)
  end
```

This causes this error: `** (MyXQL.Error) (1054) (ER_BAD_FIELD_ERROR) Unknown column 'g0.F_GroupParent' in 'where clause'`

Looking at the generated SQL, the problem is that the `initial_query` gets turned into something like:

`SELECT T0.F_GroupID AS id, T0.F_GroupName as name` (etc)

However, the main `SELECT` statement outside the CTE still uses the real names for the fields (e.g. `SELECT G0.`F_GroupID`), but by this point they have been renamed, causing the error.

**Comment by ccapndave** [comment]
Here is a full example of some generated SQL that fails:

```sql
WITH RECURSIVE `group_tree` AS (
 SELECT T0.`F_GroupID` AS `id`, T0.`F_GroupName` AS `name`, T0.`F_GroupType` AS `type`, T0.`F_DeletedAt` AS `deleted_at`, T0.`F_GroupParent` AS `parent_id` FROM `T_Groupstructure` AS T0 WHERE (T0.`F_GroupID` = 51)
 UNION ALL
 SELECT T0.`F_GroupID`, T0.`F_GroupName`, T0.`F_GroupType`, T0.`F_DeletedAt`, T0.`F_GroupParent` FROM `T_Groupstructure` AS T0 INNER JOIN `group_tree` AS g1 ON T0.`F_GroupParent` = g1.`id` WHERE (T0.`F_GroupID` = 51)
)

SELECT g0.`F_GroupID`, g0.`F_GroupName`, g0.`F_GroupType`, g0.`F_DeletedAt`, g0.`F_GroupParent` FROM `group_tree` AS g0
```

**Comment by josevalim** [comment]
I think we could fix this by disabling source aliasing for recursive queries.

**Comment by ccapndave** [comment]
If you can point me in the right direction I could have a go at fixing this (no promised though :) )

**Comment by josevalim** [comment]
I think it is an issue on Ecto.Query.Planner and unfortunately it is not straight-forward to fix it there, sorry. But if you want to give it a try, notice how some of the queries have the AS and the others do not, we need to find out why some do, and the others do not, and make them consistent.

**Comment by josevalim** [comment]
Btw @ccapndave, it would help me a ton if you provide a sample app that reproduces this error. This way I can focus my efforts on fixing the bug instead of reproducing it. Can you provide so?

**Comment by ccapndave** [comment]
Sure thing - I'll do it first thing next week.

**Comment by ccapndave** [comment]
@josevalim Here is a minimal example with two tests - the first passes using a fragment with manual SQL, and the second fails using composition.  Hope it helps!

https://github.com/ccapndave/cte_161_example

**Comment by josevalim** [comment]
@ccapndave I think I am missing something, because both queries in your example app is failing.

Here is MySQL version:

```
$ mysql --version
mysql  Ver 8.0.18 for osx10.14 on x86_64 (Homebrew)
```

**Comment by ccapndave** [comment]
I'm on the same version.  That's weird, let me double check it.

**Comment by ccapndave** [comment]
What error is it failing with?

**Comment by ccapndave** [comment]
```
➜  cte_161_example git:(master) MIX_ENV=test mix ecto.create
The database for Cte161Example.Repo has been created
➜  cte_161_example git:(master) MIX_ENV=test mix ecto.migrate
➜  cte_161_example git:(master) MIX_ENV=test mix test


  1) test it fails with composition (CTE161Test)
     test/cte_161_example_web/cte_161_test.exs:41
     ** (MyXQL.Error) (1054) (ER_BAD_FIELD_ERROR) Unknown column 'g0.F_GroupID' in 'field list'
     code: result = Repo.all(query)
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
       (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
       test/cte_161_example_web/cte_161_test.exs:57: (test)

.

Finished in 0.1 seconds
2 tests, 1 failure

Randomized with seed 672677
```

**Comment by josevalim** [comment]
Sorry for not pasting the error:

```elixir

  1) test it works with a fragment (CTE161Test)
     test/cte_161_example_web/cte_161_test.exs:21
     ** (MyXQL.Error) (1064) (ER_PARSE_ERROR) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE `group_tree` AS (SELECT * FROM T_Groups WHERE F_GroupID=?
                 ' at line 1
     code: result = Repo.all(query)
     stacktrace:
       (ecto_sql 3.2.1) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql 3.2.1) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
       (ecto 3.2.5) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
       (ecto 3.2.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
       test/cte_161_example_web/cte_161_test.exs:35: (test)



  2) test it fails with composition (CTE161Test)
     test/cte_161_example_web/cte_161_test.exs:41
     ** (MyXQL.Error) (1064) (ER_PARSE_ERROR) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE `group_tree` AS (SELECT T0.`F_GroupID` AS `id`, T0.`F_GroupName` AS `n' at line 1
     code: result = Repo.all(query)
     stacktrace:
       (ecto_sql 3.2.1) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql 3.2.1) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
       (ecto 3.2.5) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
       (ecto 3.2.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
       test/cte_161_example_web/cte_161_test.exs:57: (test)
```

**Comment by josevalim** [comment]
Wait. It is something weird on my end:

```elixir
{:ok,
 %MyXQL.Result{
   columns: ["@@version"],
   connection_id: 62,
   last_insert_id: nil,
   num_rows: 1,
   num_warnings: 0,
   rows: [["5.7.24"]]
 }}
```

It is running 5.7.24 even if I don'thave it anywhere in my system?

**Comment by josevalim** [comment]
Ok, I got it. Thanks for confirming it was rather me. :D

**Comment by josevalim** [comment]
So this is unfortunately not trivial to fix. The issue is that often you want to keep the aliases and it is hard to know when to keep or when not to. So you have two options:

  1. Use a fragment
  2. Use a query but build the select yourself %{F_GroupID: ...}

For now, I will document this limitation in the docs. Thank you for reporting and for the sample app.

**Comment by ccapndave** [comment]
Thanks very much for looking into it.  I don't think I'm going to be able to compose queries that way I want to using either fragments or manual selects, so I'm going to have a go creating `VIEW`s in the database that rename the columns to what Ecto expects.

Cheers!

**Comment by ccapndave** [comment]
In case anyone else encounters the same problem, I can confirm that making a `VIEW` with columns renamed to Ecto defaults works around this problem neatly.
