### ISSUE TITLE
Changelog entry for 3.2.2

### ISSUE THREAD

**Issue by dideler** [elixir-ecto/ecto_sql#168]
Heads up, there's no entry for v3.2.2 (2019-11-25) in the [current CHANGELOG](https://github.com/elixir-ecto/ecto_sql/blob/791f87068a6b5f727808f8fd6f20b7e1be9b5297/CHANGELOG.md).

https://github.com/elixir-ecto/ecto_sql/commits/v3.2.2

**Comment by wojtekmach** [comment]
Thanks for the report!
