### ISSUE TITLE
Error 1032: Can't find record in table

### ISSUE THREAD

**Issue by byronpc** [elixir-ecto/ecto_sql#169]
### Environment

* Elixir version (elixir -v): 1.7.3 - 1.9.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 5.5.5-10.3.9-MariaDB
* Ecto version (mix deps): 2.2.10 (pre ecto_sql as tested) upto 3.2.5
* Database adapter and version (mix deps): myxql 0.3.1
* Operating system: Ubuntu

### Current behavior

Inserting an entry on a table with a foreign key reference to another table (with a key not existing on the other table), raises an error 

`(Mariaex.Error) (1032): Can't find record in 'role_permission'`

or 

`%MyXQL.Error{mysql: %{code: 1032}}`

ecto table migration

```
create table(:role_permission, primary_key: false) do
      add :role_name,     references(:role, column: :name, type: :string), size: 48, primary_key: true
      add :resource_name, references(:resource, column: :name, type: :string), size: 48, primary_key: true
      add :action_name,   references(:action, column: :name, type: :string), size: 48, primary_key: true
end
```

Changeset sample

```
%RolePermission{
      role_name: role_name,
      resource_name: resource_name,
      action_name: action_name
}
|> change()
|> validate_required([:role_name, :resource_name, :action_name])
|> foreign_key_constraint(:role_name)
|> foreign_key_constraint(:resource_name)
|> foreign_key_constraint(:action_name)
|> Repo.upsert()
```

1032 is returned if we add a `on duplicate key update` in the query as what my custom `upsert` does

e.g. 

`insert into role_permission(role_name, resource_name, action_name) values ("a", "b", "c") ON duplicate key update resource_name = "b";`

### Expected behavior

changeset should've caught the foreign key constraint

**Comment by wojtekmach** [comment]
Thank you for the report,

I wasn't able to reproduce it on mariadb 10.3.20, I was getting the expected error:

```
mysql> insert into role_permission(role_name, resource_name, action_name) values ("a", "b", "c") ON duplicate key update resource_name = "b";
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`phx_myxql_dev`.`role_permission`, CONSTRAINT `role_permission_resource_name_fkey` FOREIGN KEY (`resource_name`) REFERENCES `resource` (`name`))
```

However, on 10.3.9 that you're running, I indeed got:

```
mysql> insert into role_permission(role_name, resource_name, action_name) values ("a", "b", "c") ON duplicate key update resource_name = "b";
ERROR 1032 (HY000): Can't find record in 'role_permission'
```

Unfortunately, the error message doesn't have the name of the constraint that failed so we wouldn't be able to transform it to a changeset error, I'm afraid there isn't anything we can do about that :( If you can, upgrade your server and you should be good to go.

**Comment by byronpc** [comment]
Thank you very much for the feedback

**Comment by byronpc** [comment]
I have a question though...shouldnt regular insert errors produce an error instead of raising an exception?

**Comment by wojtekmach** [comment]
Repo.insert is a high-level operation and it returns either {:ok, struct} or {:error, changeset}, if a _DB_ error cannot be transformed to a _changeset_ error, we raise.

**Comment by byronpc** [comment]
Fair enough
