### ISSUE TITLE
Missing condition {:ok, _} in execute/4 

### ISSUE THREAD

**Issue by joaothallis** [elixir-ecto/ecto_sql#17]
### Current behavior

The function `Ecto.Adapters.Postgres.Connection.execute/4` is not handling the case where `Postgrex.execute/4` returns `{: ok, Postgrex.Result.t}`

execute/4 specification: `execute(conn, Postgrex.Query.t, list, Keyword.t) ::
    {:ok, Postgrex.Result.t} | {:error, Postgrex.Error.t}`

### Expected behavior
Add condition for `{:ok, Postgrex.Result.t}`

Example:
```elixir
        {:ok _} = ok ->
           ok
```

---

Can such cases occur?
```elixir
        {:ok, %{ref: ^ref}, result} ->
          {:ok, result}

        {:ok, _, _} = ok ->
          ok
```

In the `Postgrex.execute/4` `@spec` do not have these cases

**Comment by wojtekmach** [comment]
Postgrex.execute/4 typespec is wrong, it should include the query. A PR would be appreciated.

**Comment by josevalim** [comment]
Typespec fixed in Postgres master.
