### ISSUE TITLE
Migrator ignores primary key configuration without do block

### ISSUE THREAD

**Issue by whitepaperclip** [elixir-ecto/ecto_sql#171]
### Environment

* Elixir version (elixir -v): 1.9.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql 12
* Ecto version (mix deps): 3.2.x, 3.3.x
* Database adapter and version (mix deps): postgrex 0.15.1
* Operating system: macOS Catalina

### Current behavior

`config :app, App.Repo, migration_primary_key: [type: :binary_id]`

`$ mix ecto.gen.migration create_foo`

```elixir
create table(:foo, prefix: "cms")
```

```
foo_dev# \d cms.foo
                               Table "cms.foo"
 Column |  Type  | Collation | Nullable |                  Default
--------+--------+-----------+----------+--------------------------------------------
 id     | bigint |           | not null | nextval('cms.foo_id_seq'::regclass)
```

Oddly:

```elixir
create table(:foo, prefix: "cms") do
end
```

```
foo_dev# \d cms.foo
                               Table "cms.foo"
 Column | Type | Collation | Nullable | Default
--------+------+-----------+----------+---------
 id     | uuid |           | not null |
```

### Expected behavior

A `do` block shouldn't be required to get a primary key of type `uuid`.

**Comment by wojtekmach** [comment]
Thank you for a very detailed report, closing in favour of #172!
