### ISSUE TITLE
example migration file name in documentation is not conformant

### ISSUE THREAD

**Issue by adrianomitre** [elixir-ecto/ecto_sql#176]
# Environment

This documentation problem was introduced in e0ec39a00c6ab84d4e07ee3fac5dcd3d6115e2be (Fri Jun 28 20:19:51 2019 +0200).

### Current behavior

For example, if you need to track the "weather" in your system, you can start a new file at "priv/repo/migrations/2019041714000_add_weather_table.exs" that will have the following contents:

As can be seen in [Ecto.Migration — Ecto SQL v3.3.2](https://hexdocs.pm/ecto_sql/Ecto.Migration.html).

### Expected behavior

For example, if you need to track the "weather" in your system, you can start a new file at "priv/repo/migrations/2019041714000**0**_add_weather_table.exs" that will have the following contents:

**Comment by josevalim** [comment]
Can you please send a PR? Thanks!
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D
