### ISSUE TITLE
Version 3.3.3 could contain some breaking change 

### ISSUE THREAD

**Issue by gabrielrinaldi** [elixir-ecto/ecto_sql#188]
### Environment

* Elixir version 1.9.4:
* Database and version 12.1:
* Ecto version 3.3.3:
* Database adapter and version (mix deps): postgrex 0.15.3
* Operating system: macOS 15.3

### Current behavior

After the upgrade to `ecto_sql` 3.3.3 I am getting the following errors when running tests: 

```
** (Postgrex.Error) ERROR 42883 (undefined_function) operator does not exist: timestamp without time zone = boolean

         query: SELECT p0."id", p0."card_display", p0."deleted_at", p0."expiration_month", p0."expiration_year", p0."full_name", p0."metadata", p0."payment_token", p0."primary_payment", p0."user_id", p0."inserted_at", p0."updated_at" FROM "payment_methods" AS p0 WHERE (((p0."id" = $1) AND (p0."user_id" = $2)) AND (p0."deleted_at" = (p0."deleted_at" IS NULL)))

         hint: No operator matches the given name and argument types. You might need to add explicit type casts.
```

Reverting to `ecto_sql` 3.3.2 fixes the issue. 

### Expected behavior

Since this is a patch release it should not have any breaking change.

**Comment by gabrielrinaldi** [comment]
**Update**

Changing the query from: `query = from(p in PaymentMethod, where: [id: ^id, user_id: ^user_id, deleted_at: is_nil(p.deleted_at)])` to: `query = from p in PaymentMethod, where: p.user_id == ^user_id and is_nil(p.deleted_at)` fixed the issue. 

Still a breaking change IMO, but not sure if that way of writing it is supported since I could not find it in the docs.

**Comment by wojtekmach** [comment]
I was able to reproduce this, for this query:

```elixir
query = from(u in "users", select: u.id, where: [deleted_at: is_nil(u.deleted_at)])
Ecto.Adapters.SQL.to_sql(:all, Repo, query) |> elem(0) |> IO.puts()
```

on Ecto v3.3.2 we have:

```sql
SELECT u0."id" FROM "users" AS u0 WHERE (u0."deleted_at" = u0."deleted_at" IS NULL)
```

and on Ecto v3.3.2 we have:

```sql
SELECT u0."id" FROM "users" AS u0 WHERE (u0."deleted_at" = (u0."deleted_at" IS NULL))
```

note the extra parens.

I'd argue the feature accidentally worked before and the generated SQL was not something people would write by hand, thus I wouldn't necessarily consider it a breaking change. I think the correct way to write the query using keyword syntax would be:

```elixir
from(p in PaymentMethod, where: [id: ^id, user_id: ^user_id], where: is_nil(p.deleted_at)])
```

**Comment by josevalim** [comment]
Yup, we fixed a bug and by fixing that bug, Ecto is revealing a bug in your application. You should update your query. :) In any case, thanks for the report!
