### ISSUE TITLE
Text type missing in ecto.schema documentation

### ISSUE THREAD

**Issue by clemarech** [elixir-ecto/ecto_sql#194]
**Ecto version (mix deps)**: 3.3.4

Hi people,

I have noticed the `text` sql type is missing in ecto.schema documentation.
Is that on purpose or just an oversight ?

Thanks :)

**Comment by wojtekmach** [comment]
`:string` type already covers that! Note, you'd use `:string` in your Ecto schema but you're free to use `:text` in your migration.
