### ISSUE TITLE
Add TDS streaming support

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto_sql#200]

**Comment by garretttaco** [comment]
@josevalim Would this generally work the same way as it does for the Postgres adapter? I would be happy to attempt to implement this, I just need a little guidance on what all needs to be done to make this possible.

**Comment by josevalim** [comment]
Closing this. If someone is interested, please investigate upstream on the TDS adapter.

sorry for not seeing your comment earlier @garretttaco !
