### ISSUE TITLE
Utilize prepared query handle cashing in TDS adapter to avoid multiple sp_prepare calls from the same ecto query

### ISSUE THREAD

**Issue by mjaric** [elixir-ecto/ecto_sql#205]
MSSql server can execute multiple times same prepared query if client can keep `@handle` output value during same session/connection. Ecto can generate name for query and this key can be used to cache prepared query handle value, so same connection can skip `sp_prepare` call and go straight to query execution by calling `sp_execute`.

This should be the case for streaming too (`sp_CursorPrepare`) with difference that cursor must be unprepared after close and it's handle must be removed from the cache after it is closed.

two adapter connections cannot share cached handles since MSSQL will not share them between connection. So cache table should be private to process

**Comment by josevalim** [comment]
Perfect. I would say this is more of a TDS issue though. EctoSQL already uses the proper DBConnection APIs for this, so if you implement the correct semantics in prepare, prepare_execute and execute, then everything should just work. If you have any questions, feel free to ask!

**Comment by mjaric** [comment]
should cache be stored in ETS?

**Comment by josevalim** [comment]
@mjaric yes, it must be on ETS. Remember that DBConnection does queries from clients, which requires passing the connection state between processes. So if you have a large cache in the state, then it will be copied on every operation.
