### ISSUE TITLE
postgres adapters dump float error

### ISSUE THREAD

**Issue by heavyk** [elixir-ecto/ecto_sql#226]
I think this might be a bug.. at least it isn't expected behaviour

### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
* Ecto version (mix deps):
  * postgrex 0.15.3 (Hex package) (mix)
  * ecto_sql 3.4.3 (Hex package) (mix)
  * ecto 3.4.3 (Hex package) (mix)
* Operating system: OSX 10.15.4

### Current behavior

```elixir
iex(3)> Ecto.Type.adapter_dump(Ecto.Adapters.Postgres, :float, 1588045954027)
:error
iex(4)> Ecto.Type.adapter_dump(Ecto.Adapters.Postgres, :float, 1588045954027.3)
{:ok, 1588045954027.3}
```

### Expected behavior

1588045954027 should be considered a float

**Comment by chulkilee** [comment]
> 1588045954027 should be considered a float

Why? Is postgresql actually accepting/emitting integer as float?

Otherwise, that's expected behavior since `1588045954027` is not a float.

**Comment by josevalim** [comment]
`dump` receives the data in your struct and the data in your struct should always be valid. If it isn't, it usually means you are manually setting an integer on a field that should be a float. :)

**Comment by heavyk** [comment]
I agree it's a float, and I can get around it by casting to a float, but it seems like a useless error.

what I'm suggesting is to use `is_number` instead of `is_float`, because all numbers *are* floats (I think. they are in js, anyway). the float check probably just checks to see if it's not an integer, yet they still equal. eg. `1588045954027 == 1588045954027.0` deductive reasoning says that if x = float and y = x, then y should be a float, but in this case it isn't true.

in my case I am simply getting this number from Date.now() and it comes across the wire as an "integer" (no decimal place). I can get it to become a float by adding  0.0, but I don't see any reason why I should have to do that..

```elixir
iex(25)> is_float(1588045954027)
false
iex(26)> is_float(1588045954027 + 0.0)
true
```

**Comment by josevalim** [comment]
They are the same in JS but not in Elixir. The fact two things are equal do not mean they are of the same type either and Elixir does provide `===` for strict type comparison. Treating all numbers as floats is actually a bad practice, given floats have precision issues. If they don't have to be floats, then my suggestion is to actually change your schema to make the integers. Otherwise, the explicit cast is necessary.

**Comment by heavyk** [comment]
is there an easy way to specify in the ecto changeset that I want it to be automatically cast to an integer (or a float) without throwing an error? I'm doing something like this:

```elixir
changes = %{t_created: 1588045954027}
changeset = Ecto.Changeset.change(existing)
Enum.reduce changes, changeset, fn
    {key, value}, changeset when is_number(value) ->
      Ecto.Changeset.put_change(changeset, key, value + 0.0)
    {key, value}, changeset ->
      Ecto.Changeset.put_change(changeset, key, value) # this throws if I didn't have the above specific cast
  end
```

**Comment by lukaszsamson** [comment]
> They are the same in JS

Even that is not entirely true as JS interpreter/JIT compiler chooses integer or float representation in runtime.

**Comment by heavyk** [comment]
as far as I know, all numbers in js are required to by 64bit floats. that's why you have MAX_SAFE_INTEGER

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by heavyk** [comment]
> then my suggestion is to actually change your schema to make the integers

ok, I didn't because I can store those big "integers" in the database as float4s, which loose a little bit of their precision because of them being 32-bit floats -- but I'm only loosing maybe a few ms of precision in 2020 and maybe a few seconds in 2100. it's just a space saving technique..

**Comment by heavyk** [comment]
... oh, I just thought of an idea maybe to get it automatically casting. can I make a schema type called ":number"? do I have to make a custom ecto type for it, that's all?

**Comment by josevalim** [comment]
@heavyk if you are getting the data through an API, then consider using `Ecto.Changeset.cast`, which will cast the fields for you, converting integers into floats in this case.

**Comment by josevalim** [comment]
But yes, you can use a custom type too.
