### ISSUE TITLE
SSL support for TDS

### ISSUE THREAD

**Issue by vorce** [elixir-ecto/ecto_sql#227]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.0 (compiled with Erlang/OTP 21)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Microsoft SQL Azure (RTM) - 12.0.2000.8   Apr  9 2020 16:39:55   Copyright (C) 2019 Microsoft Corporation
* Ecto version (mix deps): 
```
* ecto 3.4.3 (Hex package) (mix)
  locked at 3.4.3 (ecto) 9b6f18de
* ecto_sql 3.4.3 (Hex package) (mix)
  locked at 3.4.3 (ecto_sql) ec9e59d6
* phoenix_ecto 4.1.0 (Hex package) (mix)
  locked at 4.1.0 (phoenix_ecto) c5e666a3
```
* Database adapter and version (mix deps): tds 2.1.0
* Operating system: windows 

### Current behavior

Database communication is done in clear text even though the `ssl` option is set to true.

How to reproduce:
- Set up azure db with ssl cerificate
- Create new phoenix project with mssql: mix phx.new --datbase mssql test_tds_ssl
- Configure database in config/dev.exs, ensure `ssl` is set to true
- Start project in iex, send query:  TestTdsSsl.Repo.query("select * from INFORMATION_SCHEMA.TABLES;")
- Observe traffic with wireshark for example. Note that queries and responses are sent in clear text

### Expected behavior

Database communication should be encrypted when the `ssl` option is enabled.

**Comment by mjaric** [comment]
@jose, should we move this issue to tds repo?

**Comment by josevalim** [comment]
It is up to you!

**Comment by mjaric** [comment]
This issue is moved to [tds repo](https://github.com/livehelpnow/tds/issues/109) since it is not related directly to tds adapter.
