### ISSUE TITLE
Version 3.4.4 breaking change - removed Ecto.Adapters.SQL.load_embed/2

### ISSUE THREAD

**Issue by darrenklein** [elixir-ecto/ecto_sql#230]
Hello, thank you so much for all of your hard work on the Ecto project.

I work on a team that's been developing an Ecto adapter for DynamoDB, and I noticed that you introduced a potentially breaking change in the 3.4.4 release of `ecto_sql` - it seems that you've removed `Ecto.Adapters.SQL.load_embed/2` from the public API, which caused our adapter to break as it made use of that method.

No worries, as we were able to quickly "adapt" (ha!) and make use of `Ecto.Type.embedded_load/3` instead, but I thought you might like to be aware of this and perhaps add it to the release notes for 3.4.4.

Much appreciated.

**Comment by josevalim** [comment]
Thanks @darrenklein for the heads up. You are correct, this was a mistake from our side. We could add the function back but since you have adapted, we will probably leave things as is, unless someone needs it back, which they are welcome to mention here.

**Comment by darrenklein** [comment]
Thank you, José - yes, we're all good now.
