### ISSUE TITLE
[Feature] Support foreign tables in migrations

### ISSUE THREAD

**Issue by jjl** [elixir-ecto/ecto_sql#238]
Here's an example from the [cstore_fdw README](https://github.com/citusdata/cstore_fdw)

```
CREATE FOREIGN TABLE customer_reviews
(
    customer_id TEXT,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title TEXT,
    product_sales_rank BIGINT,
    product_group TEXT,
    product_category TEXT,
    product_subcategory TEXT,
    similar_product_ids CHAR(10)[]
)
SERVER cstore_server
OPTIONS(compression 'pglz')
```

We can add SERVER and options slightly unergonomically, but there is no way to insert that 'foreign'. The minimum fix would be to add a boolean `foreign` option that defaults to false. I don't know if there are other things that might replace 'foreign' there that might justify free sql.

Thoughts?

**Comment by jjl** [comment]
Usually I'm asking about things that require deep knowledge of ecto, but this one seems simple enough, so I can give it a go. Any pointers?

**Comment by josevalim** [comment]
You will want to take a look at the Table struct in Ecto.Migrations. Then each adapter has to handle `{:create, %Table{}}` and `{:drop, %Table{}}` events, so it is a matter of adapting those to emit the proper SQL and then changing `test/ecto/adapters/*_test.exs` to have unit tests. Note this feature is part of `ecto_sql` (I have moved the issue). Ping me on IRC if you need help!

**Comment by josevalim** [comment]
Closing in favor of PR!
