### ISSUE TITLE
Ecto.Migrator.run/4 uses wrong `schema_migrations` table

### ISSUE THREAD

**Issue by zimt28** [elixir-ecto/ecto_sql#243]
### Environment

* Elixir version (elixir -v): 1.10.1
* Database and version: PostgreSQL 9.4
* Ecto version (mix deps): 3.4.5

### Current behavior

`Migrator.run(Repo, @migrations, :up, all: true, prefix: "prefix")` creates a `prefix.schema_migrations` table and runs the given migration inside of the `"prefix"` schema, but writes migration logs to `public.schema_migrations`.

### Expected behavior

Migrations should be written to the `prefix.schema_migrations` table.

**Comment by josevalim** [comment]
Thanks for the report. I cannot reproduce it. Calling prefix in my case set all of the prefixes publicly and the logs were also written to the prefix. Can you please provide a small app that reproduces the error?

**Comment by zimt28** [comment]
I was able to find the reason: I have some code that basically evaluated to this:

```elixir
defmodule App.Repo do
  use Ecto.Repo,
    otp_app: :app,
    adapter: Ecto.Adapters.Postgres

  def default_options(_operation) do
    [prefix: nil]
  end
end
```

I _assumed_ that using the `prefix` option on `Ecto.Migrator.run/4` would override the default option – and for creating the tables, it does. However, when writing data, it's using the repo's default value. Is this the intended behavior?

**Comment by josevalim** [comment]
I will play with it. The default options should be overridden in this case, I am not sure why it isn't.
