### ISSUE TITLE
[Feature] Leverage IF NOT EXISTS / IF EXISTS syntax with create index / drop index (Postgres)

### ISSUE THREAD

**Issue by tlvenn** [elixir-ecto/ecto_sql#247]
As discussed in https://github.com/jumpn/ecto_cockroachdb/issues/4, the way Ecto deal with creating / dropping indexes when `if_not_exists` / `if_exists` is used does not leverage support for "IF NOT EXISTS" / "IF EXISTS" added to Postgres 9.5 when dealing with indexes.

Instead it uses a workaround using the `$$ do` syntax which is not supported by CockroachDB.

I noticed that the usage of "IF NOT EXISTS" / "IF EXISTS" when dealing with tables was added to Postgres with the 9.1 version and is already being used by the adaptor:
> https://github.com/elixir-ecto/ecto_sql/blob/cd7f585d992f14331874698b1851152fe09f8304/lib/ecto/adapters/postgres/connection.ex#L803

We could simply do the same for indexes but this would introduce a breaking change for anyone leveraging this feature and still using any Postgres version below 9.5.

But 9.5 is the oldest version actually still supported by Postgres so that might be ok ?
It's not clear what compatibility with Postgres is actually currently targeted by the adaptor. As noted above, given the usage of `IF NOT EXISTS` with tables, it seems to indicate it is at least 9.1.

**Comment by josevalim** [comment]
Next version will be v3.5 so it may be fine to drop support for Postgres earlier than v9.5 as they are no longer supported. I have sent a PR here: https://github.com/elixir-ecto/ecto_sql/pull/248

Meanwhile, a PR to update the syntax we use for indexes is welcome. Thank you!

**Comment by tlvenn** [comment]
Awesome, I will take care of that, thanks @josevalim !

**Comment by josevalim** [comment]
Ping! :)

**Comment by tlvenn** [comment]
I will pong back very soon @josevalim ;)

**Comment by tlvenn** [comment]
Any idea of the `"concurrent index and create_if_not_exists is not supported by the Postgres adapter"` was a product of using the `$$ do` syntax or something else is at play here ?

**Comment by josevalim** [comment]
@tlvenn see discussion here: https://github.com/elixir-ecto/ecto/issues/2703#issuecomment-424792318

It seems we can enable this functionality once we rewrite since we now provide a mechanism to disable the lock too.
