### ISSUE TITLE
Preparing for Ecto v3.5

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto_sql#249]
Hi @mjaric and @leandrocp,

We will likely release Ecto v3.5 in a week or two, so if there is any feature you want to get in regarding TDS or the EXPLAIN support, please let me know. I would say it would be important to at least get EXPLAIN working, but I am following if there is already a release of the TDS adapter that includes the necessary features. :)

Thanks and have a great week!

**Comment by leandrocp** [comment]
Hey @josevalim,

Yeah I'd like to implement EXPLAIN for TDS adapter. @mjaric already released a version supporting multiple calls, which is required to run explain. Ref: https://github.com/livehelpnow/tds/issues/108#issuecomment-643824465

Although I'm not sure what path to take here. Please read @mjaric comment https://github.com/elixir-ecto/ecto_sql/pull/231#discussion_r434312982. Considering that STATISTICS IO/TIME doesn't give too much information and STATISTICS XML returns results in Xml (and there's no Xml parser available), looks like the best approach is to implement PROFILE for now.

@josevalim and @mjaric wdyt?

**Comment by josevalim** [comment]
Erlang comes with xmerl, which can parse XML. It is not safe for external input but it should be safe for parsing XML results from SQL Server. So that would be my choice if we can make the results somewhat readable. If not, I would say the feature is just not supported, as profiling/statistics are effectively another feature.

**Comment by leandrocp** [comment]
Ok good I'll try that. I'll send a draft PR this week to hopefully get it into v3.5 release so we have full support for EXPLAIN :)

**Comment by josevalim** [comment]
Actually, while going through Ecto issues tracker, I remembered of some on going work that will probably tackle a month or even more, so take your time. :)

**Comment by josevalim** [comment]
To keep everyone on the same page, we are making progress on the Ecto front, so I am hoping for a release in about month. :)

**Comment by josevalim** [comment]
More updates: Ecto v3.5 is ready from the Ecto side of things. We will probably ship a RC, so people can try it out as it has some non-minor changes, so this is still buys us a bit of time in case we want to get EXPLAIN in.

**Comment by josevalim** [comment]
RC is out. Thanks everyone!
