### ISSUE TITLE
Ecto.Adapters.Postgres.storage_status/1 wrong implementation

### ISSUE THREAD

**Issue by oliver-kriska** [elixir-ecto/ecto_sql#250]
Hello,

I think there is wrong implementation of [Ecto.Adapters.Postgres.storage_status/1](https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/postgres.ex#L172-L175) function.

```Elixir
def storage_status(opts) do
    database = Keyword.fetch!(opts, :database) || raise ":database is nil in repository configuration"
    maintenance_database = Keyword.get(opts, :maintenance_database, @default_maintenance_database)
    opts = Keyword.put(opts, :database, maintenance_database)

    check_database_query = "SELECT datname FROM pg_catalog.pg_database WHERE datname = '#{database}'"

    case run_query(check_database_query, opts) do
      {:ok, %{num_rows: 0}} -> :down
      {:ok, %{num_rows: _num_rows}} -> :up
      other -> {:error, other}
    end
  end
```

As you can see it load database name into `database`. But next two lines are problem. It try to load `:maintenance_database` and if not exist use default. So if user doesn't have config with `maintenance_database`. It will use default (`postgres`). After that it rewrites `database` with this  `maintenance_database`.  Query is created with right database name but query is executed with new opts. It try to make connection with default maintenance_database which is postgres. 

I think it should use `maintenance_database` or regular `database`. It's not good idea to use `postgres` database for connection. We don't have access to this database outside of our local development environment. Even staging environments are restricted to use only one db user with one database. 

So it creates this kind of error when we deployed on our test environment.

```
[error] GenServer #PID<0.22987.1> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "172.16.110.111", user "our_application_db_user", database "postgres", SSL off
    (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

I suggest to update documentation about this feature and add requirement about this configuration. Because when it used with another library, for example [Phoenix Ecto](https://hexdocs.pm/phoenix_ecto/Phoenix.Ecto.CheckRepoStatus.html) ([code](https://github.com/phoenixframework/phoenix_ecto/blob/v4.1.0/lib/phoenix_ecto/check_repo_status.ex#L41)), it creates mess. It took more than 10 hours to find where is the issue in our projects. Or change implementation to use only regular database name if maintenance_database is not provided. 

btw: huge thanks for all contributors, amazing work. Thank you

Update:
The `check_database_query` works also with db connection made with same database. 
Tests didn't find this issue because default db url is used for test run. Default url for connection is with postgres user with full access.

**Comment by josevalim** [comment]
Hi @oliver-kriska!

These collection of functions are used to create and remove databases. As one may expect, to create a database, we need to connect to a separate database than the one we intend to create. So all functions here, create, status, and drop, need a maintenance database.

I understand the check status plug was failing for you, but the whole point of the check status plug is to show the user a button to create the database if one is missing, but if you can't connect to the maintenance database, you wouldn't be able to create it either. So check status plug would still fail, just later on.

So my initial reaction is that the behaviour here is correct. My questions right now are: why was the check status plug being executed in anywhere beyond development and if you have ran into this issue elsewhere.

Thanks.

**Comment by josevalim** [comment]
Closing per the above, thanks!
