### ISSUE TITLE
Allow string type

### ISSUE THREAD

**Issue by kuon** [elixir-ecto/ecto_sql#251]
I have a use case where I `ecto_to_db/1` is called with dynamic types, and because I run some ddl at runtime, I'd like to avoid polluting the atom table with types.

Because of this, I think, in addition to the following:

```elixir
    defp ecto_to_db(other),                do: Atom.to_string(other)
```

This could be added:

```elixir
    defp ecto_to_db(other) when is_binary(other), do: other
```

https://github.com/elixir-ecto/ecto_sql/blob/74fe20a02479e71d7efe4f1391467f7e79ac7025/lib/ecto/adapters/postgres/connection.ex#L1254

I did not create a pull request, because I am not sure of the security implication, and maybe you have a better idea.

For context, my end usage looks like this:

```elixir

cols = [
         {:add, "_id", :bigint, [null: false]},
# here some_dynamic_column_type is a binary, but I am forced to convert it to an atom which is polluting atom table
         {:add, some_dynamic_column_name, String.to_atom(some_dynamic_column_type), [null: false]},
]

[
       {:create, Migration.table(t_name), cols},
]
|> Connection.execute_ddl()
|> IO.iodata_to_binary()
|> repo.query()

```

**Comment by josevalim** [comment]
Unless you are running thousands of migrations per day, you will be fine. Are the names dynamic based on unprotected user input? Or is it an admin thing?

**Comment by kuon** [comment]
Well, users can create entities with a name they choose, and the name is "sluggified" (length limited, converted to ascii and space to underscores). I could use something like hex ids for the names, but I thought it would be a nightmare for debuging if postgresql entities have "random" names.

The number of entity they can create is also limited to a few per user, but if the service scale to many users, it can be hundreds.

**Comment by josevalim** [comment]
Sounds good. We will gladly accept a PR!

**Comment by josevalim** [comment]
Closing in favor of PR!
