### ISSUE TITLE
dynamic repositories and ecto sandbox

### ISSUE THREAD

**Issue by sasa1977** [elixir-ecto/ecto_sql#258]
### Environment

* Ecto version (mix deps): 3.4.6 (ecto_sql 3.4.5)

### Current behavior

I was playing with dynamic repositories, using one database per each repository, backed by a single repo module. At runtime I start multiple instances of the repo, with all instances being nameless (`name: nil`). Then I use `put_dynamic_repo` to select the actual instance of the repository I want to work with. 

While this works fine with functions such as `Repo.all` & friends, I had some problems making the Ecto sandbox behave. In particular, functions such as `Ecto.Adapters.SQL.Sandbox.mode` and `Ecto.Adapters.SQL.Sandbox.checkout` crashed. It seems to me that these functions requires the presence of the `:default_dynamic_repo` setting, which is something I'd like to avoid.

I took a peek at the sandbox code, and was able to fix the problem by changing [this line](https://github.com/elixir-ecto/ecto_sql/blob/v3.4.5/lib/ecto/adapters/sql/sandbox.ex#L534):

```diff
- %{opts: opts} = meta = Ecto.Adapter.lookup_meta(repo)
+ %{opts: opts} = meta = Ecto.Adapter.lookup_meta(repo.get_dynamic_repo())
```

With this change, I can now do something like:

```elixir
MyDynamicRepo.put_dynamic_repo(pid)
Ecto.Adapters.SQL.Sandbox.mode(MyDynamicRepo, :manual)
Ecto.Adapters.SQL.Sandbox.checkout(MyDynamicRepo)
```

I'm not sure if this is the correct approach and if there are any unwanted implications of such change.

### Expected behavior

In any case, it would be nice if sandbox functions correctly used the repo instance configured with `put_dynamic_repo`.

**Comment by josevalim** [comment]
That's definitely the fix, a PR is welcome!

**Comment by sasa1977** [comment]
Can't assign myself to this issue, but I'll provide the fix in the next few days.

**Comment by samvalidere** [comment]
For anyone else out there who happens to stumble upon this issue because you are using `put_dynamic_repo/1` in your code, in order for your connections to be rolled back between test runs, you need to set the sandbox mode to manual and then checkout a connection.

The issue we were having is that our default repo had it's transactions rolled back, but when testing dynamic repos, those repos were committing their transactions.
