### ISSUE TITLE
Got (Postgrex.Error) ERROR 26000 (invalid_sql_statement_name) prepared statement "ecto_162" does not exist

### ISSUE THREAD

**Issue by oscarjg** [elixir-ecto/ecto_sql#275]
Hi!

I have a random errors like the title says and I'm a little lost about the origin about it. Maybe race conditions? I've experienced this errors on production environment only. The app is deployed in Digital Ocean Cloud inside a Kubernetes Cluster (2 pods).

The code that produce this error is very simple, only fetch a resource from id and I have seen similar errors from other parts of the code, all of them related with not found statements.

The error appears randomly but constantly. Maybe ( 1 ok 1 fails), (1 ok 2 fails), (2 ok, 3 fails) and so on.

**Deps**
`"postgrex": {:hex, :postgrex, "0.15.6", "a464c72010a56e3214fe2b99c1a76faab4c2bb0255cabdef30dea763a3569aa2", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:db_connection, "~> 2.1", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.5 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "f99268325ac8f66ffd6c4964faab9e70fbf721234ab2ad238c00f9530b8cdd55"},`

**Code**
```  
def get_client(id) when is_integer(id) do
  Repo.one from client in Client,
  where: client.id == ^id,
  left_join: client_credentials in assoc(client, :credentials),
  preload: [credentials: client_credentials]
end
```

**Error**
```
iex(meetrika@10.244.0.242)12> Meetrika.Accounts.Persistence.Client.get_client(12)
** (Postgrex.Error) ERROR 26000 (invalid_sql_statement_name) prepared statement "ecto_162" does not exist
    (ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

Any idea? 

Thanks!

**Comment by josevalim** [comment]
Unfortunately without a way to reproduce it is hard for us to say. I have some questions though:

1. What is your Ecto and Ecto SQL versions?

2. When it fails again, are you invoking the exact same command with the same parameters? For example: `Meetrika.Accounts.Persistence.Client.get_client(12)` and then `Meetrika.Accounts.Persistence.Client.get_client(12)` could have one failing and the other working? And they fail with the same error or does the `ecto_XYZ` bit change?

**Comment by oscarjg** [comment]
```
"ecto": {:hex, :ecto, "3.4.4", "a2c881e80dc756d648197ae0d936216c0308370332c5e77a2325a10293eef845", [:mix], [{:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "cc4bd3ad62abc3b21fb629f0f7a3dab23a192fca837d257dd08449fba7373561"},
"ecto_sql": {:hex, :ecto_sql, "3.4.3", "c552aa8a7ccff2b64024f835503b3155d8e73452c180298527fbdbcd6e79710b", [:mix], [{:db_connection, "~> 2.2", [hex: :db_connection, repo: "hexpm", optional: false]}, {:ecto, "~> 3.4.3", [hex: :ecto, repo: "hexpm", optional: false]}, {:myxql, "~> 0.3.0 or ~> 0.4.0", [hex: :myxql, repo: "hexpm", optional: true]}, {:postgrex, "~> 0.15.0", [hex: :postgrex, repo: "hexpm", optio
```

Exactly, always same error in this case "ecto_162"

**Comment by oscarjg** [comment]
I've updated my deps to `ecto:3.4.6` and `ecto_sql:3.4.5` and the error persist but the code is a different one "ecto_323" in this case

```
iex(meetrika@10.244.0.146)11> Meetrika.Accounts.Persistence.Client.get_client(12)
** (Postgrex.Error) ERROR 26000 (invalid_sql_statement_name) prepared statement "ecto_323" does not exist
    (ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

Hope this helps . Thanks!

**Comment by josevalim** [comment]
Are you using pgpool or anything in front of postgres?

**Comment by oscarjg** [comment]
Yes, a connection pool is enabled inside Digital Ocean. If I delete it I have this message.

```
iex(meetrika@10.244.0.146)11> Meetrika.Accounts.Persistence.Client.get_client(12)
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2871ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. By tracking down slow queries and making sure they are running fast enough
  2. Increasing the pool_size (albeit it increases resource consumption)
  3. Allow requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

**Comment by josevalim** [comment]
Can you please share your prod configuration? Please remove the password and username bits. Ecto has its own pool, you shouldn't  need to add your own pool on top.

**Comment by oscarjg** [comment]
This is my releases.exs file . The value of DB_POOL_SIZE is set to 15 currently
```
import Config

service_name = System.fetch_env!("SERVICE_NAME")
db_url = System.fetch_env!("DB_URL")
secret_key_base = System.fetch_env!("SECRET_KEY_BASE")
port = System.fetch_env!("PORT")
pool_size = System.fetch_env!("DB_POOL_SIZE") |> String.to_integer

config :meetrika,
  client_domain: System.get_env("MTK_CLIENT_DOMAIN")

config :meetrika, Meetrika.Repo,
  url: db_url,
  pool_size: pool_size,
  ssl: true

config :meetrika, MeetrikaWeb.Endpoint,
  http: [port: port],
  secret_key_base: secret_key_base,
  url: [host: {:system, "APP_HOST"}, port: {:system, "PORT"}]

config :peerage, via: Peerage.Via.Dns,
  dns_name: service_name,
  app_name: "meetrika"
```

**Comment by josevalim** [comment]
I have pushed a commit to Postgrex master. It doesn't fix the root cause of the error, which I don't understand what it is, but it at least allows the connection to recover from the error, so you are least get unstuck from this permanent error state. Can you please try it out?

**Comment by josevalim** [comment]
Also, every time you do a new deployment, you can immediately reproduce the error, right?

**Comment by josevalim** [comment]
Ok, after reading DO docs, it is clear they are using pgbouncer, so you need to set `prepare: :unnamed` in your repo configuration. There is more info in Postgrex' readme: https://github.com/elixir-ecto/postgrex/#pgbouncer

**Comment by oscarjg** [comment]
Fantastic, is working, although I must to enabled DO pooling otherwise I get the "connection not available and request was dropped" error but maybe it is normal (It's my first time working with Elixir and Cloud environments)

Thank you for your support @josevalim. Very appreciated.

**Comment by sergiotapia** [comment]
Adding `prepare: :unnamed` to my Repo config also fixed the issue with my Supabase database connection.

```
config :my_app, MyApp.Repo,
  pool_size: 10,
  url: database_url,
  prepare: :unnamed
```
