### ISSUE TITLE
SQL Server 3-Part Schema Naming

### ISSUE THREAD

**Issue by aoswalt** [elixir-ecto/ecto_sql#278]
### Environment

* Elixir version (elixir -v): 1.11.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): SQL Server 2017 14.0.3335.7
* Ecto version (mix deps): phoenix_ecto: "\~> 4.2", ecto_sql: "~> 3.5"
* Database adapter and version (mix deps): tds: "\~> 2.1", tds_encoding: "~> 1.0"
* Operating system: macOS Catalina 10.15.6

### Current behavior

SQL Server allows for having separate databases on the same server that are accessible by a `[database].[schema].[table]` structure. The first element defaults to the database in the connection information, and the second element defaults to `dbo`.

I am attempting to rewrite some raw string queries referring to a legacy database into Ecto schemas but have been unable to construct the schemas because of a naming limitation.

For example, with a simple query like this:
```elixir
query = """
select top 5
  GlobalMemberID id
from ref.dbo.ProviderAttribution_ALL
"""

Ecto.Adapters.SQL.query!(Orc.ODS, query)
```

Making some assumptions, I attempted to create an Ecto schema as
```elixir
@schema_prefix "ref.dbo"
@primary_key {:id, :text, source: :GlobalMemberID}
schema "ProviderAttribution_ALL" do
end
```

Unfortunately, I am greeted with an Invalid Object Name error
```
iex(2)> Orc.ProviderSearch.Attribution |> limit(5) |> Orc.ODS.all()
** (Tds.Error) Line 1 (Error 208): Invalid object name 'ref.dbo.ProviderAttribution_ALL'.
    (ecto_sql 3.5.0) lib/ecto/adapters/sql.ex:683: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.0) lib/ecto/adapters/sql.ex:616: Ecto.Adapters.SQL.execute/5
    (ecto 3.5.0) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.0) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```

If I am connected to the same database and leave it out of the schema with just a schema prefix of `dbo` or even without, the schema works fine.

The legacy queries join across multiple databases at times, so changing the connection to a particular database is unfortunately not a fix.

### Expected behavior

I assumed that I would be able to append the database name to the `@schema_prefix` such as `ref.dbo` or have a separate module attribute for the database name of the schema.

Thank you!

**Comment by josevalim** [comment]
@aoswalt The reason why it fails is because we quote the name to avoid SQL injection attacks. We could check if the string has a dot and escape around the dots but this can cause compatibility issues with schemas names with dots in them. Another option is to allow the prefixes to be `{"ref", "dbo"}`, but I am not sure how much work would be required on Ecto's side.

**Comment by josevalim** [comment]
Here is what I suggest for now, try passing `@schema_prefix {"ref", "dbo"}` and see where it breaks. If it breaks only on Ecto.Adapters.TDS.Connection, then that's an easy fix and all we need to do is to change said module to escape tuples correctly.

**Comment by mjaric** [comment]
I suggest creating table synonim in database that repo is connected to. Same thing is solution for case where query have to us table from linked server.

**Comment by aoswalt** [comment]
Looks like it does just error in `Ecto.Adapters.TDS.Connection` and Ecto itself doesn't care what type of value it is.

```
iex(2)> Orc.ProviderSearch.Attribution |> limit(5) |> Orc.ODS.all()
** (FunctionClauseError) no function clause matching in String.contains?/2

    The following arguments were given to String.contains?/2:

        # 1
        {"ref", "dbo"}

        # 2
        "["

    Attempted function clauses (showing 3 out of 3):

        def contains?(string, []) when is_binary(string)
        def contains?(string, contents) when is_binary(string) and is_list(contents)
        def contains?(string, contents) when is_binary(string)

    (elixir 1.11.0) lib/string.ex:2264: String.contains?/2
    (ecto_sql 3.5.0) lib/ecto/adapters/tds/connection.ex:1462: Ecto.Adapters.Tds.Connection.quote_table/1
    (ecto_sql 3.5.0) lib/ecto/adapters/tds/connection.ex:1457: Ecto.Adapters.Tds.Connection.quote_table/2
    (ecto_sql 3.5.0) lib/ecto/adapters/tds/connection.ex:917: Ecto.Adapters.Tds.Connection.create_name/3
    (ecto_sql 3.5.0) lib/ecto/adapters/tds/connection.ex:903: Ecto.Adapters.Tds.Connection.create_names/4
    (ecto_sql 3.5.0) lib/ecto/adapters/tds/connection.ex:899: Ecto.Adapters.Tds.Connection.create_names/2
    (ecto_sql 3.5.0) lib/ecto/adapters/tds/connection.ex:138: Ecto.Adapters.Tds.Connection.all/2
    (ecto_sql 3.5.0) lib/ecto/adapters/tds.ex:136: Ecto.Adapters.Tds.prepare/2
    (ecto 3.5.0) lib/ecto/query/planner.ex:180: Ecto.Query.Planner.query_without_cache/4
    (ecto 3.5.0) lib/ecto/query/planner.ex:150: Ecto.Query.Planner.query_prepare/6
    (ecto 3.5.0) lib/ecto/query/planner.ex:125: Ecto.Query.Planner.query_with_cache/7
    (ecto 3.5.0) lib/ecto/repo/queryable.ex:176: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.0) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```

**Comment by aoswalt** [comment]
@mjaric I had no idea about synonyms in SQL Server, so thanks for that info!

Ideally, it can be translated directly so that I do not have to make any changes to this database we are minimally interfacing with, but that is a good fallback. :)

**Comment by mjaric** [comment]
I found it preferred way over `create view` alternative. Reason is that when you are creating `synonym` the object it is referring to don't have to exists.  This means that you can create migration that create synonym to other db table and run it before you run migrations for the "other" database. Neat, right :) ?

Con side of synonym is that you can not set permissions to it, it simply inherit everything from "base" object it refers to which is not the case with view-s.

**Comment by mjaric** [comment]
@josevalim should we support `{"ref", "dbo"}` for @schema attribute?

**Comment by aoswalt** [comment]
Since it seemed like a fairly straightforward change, I made a naive PR for 3-part as well as 4-part naming.

**Comment by josevalim** [comment]
@mjaric that's a bigger change unfortunately so I would keep this exclusively in the prefix handling.

**Comment by aoswalt** [comment]
Adding tests to the PR revealed that there is a concern inside of Ecto itself when specifying the prefix inside of a `from` expression.

The `from` has a verification that the prefix is a compile-time string.

With part of the test being
```elixir
Schema
|> select([r], r.x)
|> from(prefix: {"first", "first_schema"})
|> Map.put(:prefix, {"database", "db_schema"})
|> plan()
```

I get an error of

```
** (Ecto.Query.CompileError) `prefix` must be a compile time string, got: `{:ok, {"first", "db_schema"}}`
    (ecto 3.5.2) expanding macro: Ecto.Query.from/2
    test/ecto/adapters/tds_test.exs:100: Ecto.Adapters.TdsTest."test from with 2-part prefix"/1
    (elixir 1.11.0) expanding macro: Kernel.|>/2
    test/ecto/adapters/tds_test.exs:102: Ecto.Adapters.TdsTest."test from with 2-part prefix"/1
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:416: Kernel.ParallelCompiler.require_file/2
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:316: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Is it acceptable to add the functionality to the schema without it working in a `from` expression, or would it be best to hold off on it?

**Comment by josevalim** [comment]
Go ahead with only trying the prefix in a query. Then once we improve from/join in Ecto, then it will just work here too.
