### ISSUE TITLE
Unnecessary INNER JOIN When Preloading in a Many to Many with join_through

### ISSUE THREAD

**Issue by GabrielAlacchi** [elixir-ecto/ecto_sql#282]
### Environment

* Elixir version (elixir -v):
 ```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.1 (compiled with Erlang/OTP 21
)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 12.4
* Ecto version (mix deps): 3.5.3
* Database adapter and version (mix deps): postgrex 0.15.7 with `Ecto.Adapters.Postgres`
* Operating system: `Linux [HOSTNAME] 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Current behavior

Hi everyone! I believe there is an inner join in the generated SQL for preloading many to many relationships. The setup is that I have a `products` table with a many to many association to a `traits` table. The join table is called `products_traits`. I've defined the schemas as follows

```
  schema "products" do
    ...

    many_to_many :traits, Trait, join_through: "products_traits"

    timestamps()
  end

  schema "traits" do
    field :name, :string

    many_to_many :products, UniqueShop.Shop.Product, join_through: "products_traits"
  end
```

Selecting products and preloading traits generates the following SQL.
```
from(p in Product) |> limit(10) |> preload(:traits) |> Repo.all
[debug] QUERY OK source="products" db=1.7ms queue=1.9ms idle=982.7ms
SELECT p0."id", p0."inserted_at", p0."updated_at" FROM "products" AS p0 LIMIT 10 []
[debug] QUERY OK source="traits" db=1.2ms queue=1.1ms idle=994.5ms
SELECT t0."id", t0."name", p1."id" FROM "traits" AS t0 INNER JOIN "products" AS p1 ON p1."id" = ANY($1) INNER JOIN "products_traits" AS p2 ON p2."product_id" = p1."id" WHERE (p2."trait_id" = t0."id") ORDER BY p1."id" [[12, 11, 10, 9, 8, 7, 6, 5, 3, 2]]
```

The preloading query is first inner joining on `products` using `p1.id=ANY(list_of_ids)` then joining on `products_traits`. The same thing is happening when going from `traits` to `products`:

```
[debug] QUERY OK source="products" db=1.3ms queue=1.2ms idle=1401.5ms
SELECT p0."id", p0."title", p0."handle", p0."long_description", p0."page_visits", p0."price_cents", p0."short_description", p0."labels", p0."inserted_at", p0."updated_at", t1."id" FROM "products" AS p0 INNER JOIN "traits" AS t1 ON t1."id" = ANY($1) INNER JOIN "products_traits" AS p2 ON p2."trait_id" = t1."id" WHERE (p2."product_id" = p0."id") ORDER BY t1."id" [[2]]
```

### Expected behavior

I would expect the following query to be both equivalent and more efficient since it involves 1 less join and thus less index lookups and IO. Since we only require the primary key of the product to we should only need to join from the associated table to the join table.

```
SELECT t0."id", t0."name", p1."product_id" FROM "traits" AS t0
INNER JOIN "products_traits" as p1 ON p1."trait_id" = t0."id"
WHERE p1."product_id" = ANY($1) ORDER BY p1."product_id" [[12, 11, 10, 9, 8, 7, 6, 5, 3, 2]]
```

When using the join table pattern in other frameworks / projects I typically create a unique index on my join table on `[:product_id, :trait_id]` and an index on `[:trait_id]` so that joining from either side can efficiently use the index.

Let me know if there's any reason that I'm missing for why the current behavior should be kept. I'd be happy to submit a PR for this!

**Comment by GabrielAlacchi** [comment]
I'll also note that the current behavior is necessary if the join table is not joined using the primary key of the source table. In other words any solution would need to reflect on the `join_keys` options and check whether the source table is joined using `:id`.

**Comment by josevalim** [comment]
> I'll also note that the current behavior is necessary if the join table is not joined using the primary key of the source table. 

We also need to guarantee there is a full match on the unique index, otherwise we may return entries that no longer have an associated product because the product has been removed? Remember preloads may happen at any moment after the data is loaded and this change could open up spaces for inconsistencies. Thoughts?

**Comment by josevalim** [comment]
Actually, my argument above is wrong. We don't do the check above for other associations, so we shouldn't do it here either. Therefore, I think we can go ahead with this and skip the original table if the join key is the primary key of the source table. PR is welcome. Note the PR should apply to the Ecto repo though and not this one!

**Comment by GabrielAlacchi** [comment]
Thanks @josevalim. I will work on a PR over the next few days.
