### ISSUE TITLE
Add support for :inner_lateral and :left_lateral to Tds adapter

### ISSUE THREAD

**Issue by deepankar-j** [elixir-ecto/ecto_sql#285]
### Environment

* Elixir version (elixir -v): 1.11.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MS SQL Server 2016
* Ecto version (mix deps): 3.5.5
* Database adapter and version (mix deps): ecto_sql 3.5.3
* Operating system: OS X

### Current behavior

Currently, a join query containing a `:left_lateral` or `:inner_lateral` will result in an error because the `Ecto.Adapters.Tds` adapter does not map those joins to an appropriate join for MS SQL Server.  

### Expected behavior

- :left_lateral should be mapped to OUTER APPLY 
- :inner_lateral should be mapped to CROSS APPLY

**Comment by deepankar-j** [comment]
https://github.com/elixir-ecto/ecto_sql/pull/284 has been submitted to add this support.

**Comment by josevalim** [comment]
Closing in favor of the PR!
