### ISSUE TITLE
Missing documentation for Sandbox.mode/2

### ISSUE THREAD

**Issue by hissssst** [elixir-ecto/ecto_sql#286]
First of all, thanks for this awesome library and elixir as a whole.

It would be nice to have some more explicit documentation about `Ecto.Adapters.SQL.Sandbox.mode/2`, because current documentation says it has only 2 modes, while function accepts 3 different modes: `:manual`, `:auto` and `{:shared, pid}`.

I am confused with this and I've decided to open an issue, since documentation should at least have some description of these modes.

You can show me some links with description of modes and how they work and I can create a PR with new documentation

**Comment by josevalim** [comment]
You are right, good call. I can submit some improvements soon!

> because current documentation says it has only 2 modes

Although I could not find the part where we have 2 modes only. Can you please link to the part we say so? I want to make sure I won't miss it. Thanks!

**Comment by hissssst** [comment]
![scrot_201201133632](https://user-images.githubusercontent.com/37012324/100729883-3e307580-33c1-11eb-8e89-2c83cb58aebb.png)
Head of documentation page says that sandbox has two modes and there are no examples, metions or explanations of `:auto` mode on the whole page (except documentation for function `mode/2` where `:auto` is only mentioned). I mean, it has a line which says that sandbox is started in "automatic" mode, but It has no explanations how it differs from `shared` or `manual` modes and when should I choose one.

I've found a lot of issues and forum topics related to sandbox mode and it would be nice to aggregate all knowledge in documentation

**Comment by josevalim** [comment]
Thanks!

I hope *most* of knowledge is in the docs because I have the habit of updating the docs whenever I answer a question (which is why we even have a FAQ :D) but if you find anything is missing, a PR is definitely welcome.

I will add more information about the modes today. :)
