### ISSUE TITLE
Cannot use Ecto to write to timestamptz columns

### ISSUE THREAD

**Issue by jamesvl** [elixir-ecto/ecto_sql#29]
### Precheck

* investigated issue with `timestamp` vs `timestamptz` columns, and am aware of (and agree with) Ecto just using `timestamp`
* checked on IRC channel to see if solution other than custom extensions is possible

### Environment

* Elixir 1.7.3 on OTP 21
* Postgres 10.5
* Ecto 3.01 / ecto_sql 3.0.0
* postgrex 0.14
* Operating system: Fedora 28

### Current behavior

If I have a legacy table (defined in another system) with a column of type `timestamptz`, I cannot use Ecto to write to that column.

```elixir
    TzTest.changeset(%TzTest{}, %{tz_col: DateTime.utc_now()}) |> Repo.insert()
```
results in this in the log:
```
11:44:59.028 [debug] QUERY ERROR db=13.7ms queue=1.1ms
INSERT INTO "tz_test" ("tz_col") VALUES ($1) RETURNING "id" [~N[2018-11-05 16:44:58.996802]]
```
even though schema is defined as
```elixir
  schema "tz_test" do
    field(:tz_col, :utc_datetime_usec)
  end
```

Full source available in test project at https://github.com/jamesvl/ecto_tz_test

### Expected behavior

Insert or updates write a DateTime value.

**Comment by qcam** [comment]
I believe this is [where](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L422) the data got encoded into `NaiveDateTime` but I'm not sure if it's a desired fix. Since now we support [encoding `DateTime`](https://github.com/elixir-ecto/postgrex/pull/418) in Postgrex `timestamp`, perhaps sending `DateTime` here is fine?

**Comment by josevalim** [comment]
If you want to use a Postgrex type that is not supported by Ecto you need
to define a custom type. Please see Ecto.Type for more information.
Alternatively you can use Calecto or similar, that does introduce types
aware of time zones.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jamesvl** [comment]
Got it - that's easily workable for me.

I filed here because between the manuals and IRC, I wasn't sure if this was desired / intended behavior or not.

Closing this issue as "not a bug".

**Comment by josevalim** [comment]
Totally. Thanks for checking!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
