### ISSUE TITLE
Mix.Tasks.Ecto.Load task fails to connect to db using unix socket

### ISSUE THREAD

**Issue by jesenko** [elixir-ecto/ecto_sql#306]
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 13.0
* Ecto version (mix deps): ecto_sql 3.5.3
* Database adapter and version (mix deps): postgrex 0.15.7
* Operating system: Ubuntu 18.04

### Current behavior

When connecting to db using following repo config: 
```
config :my_app, MyApp.Repo,
  database: "my_db",
  username: "my_user",
  socket_dir: "/var/run/postgresql"
```
and having only local `peer` auth enabled in `pg_hba.conf`, executing
```
mix ecto.load
```
fails with
```
mix stderr: ** (Mix) The structure for MyApp.Repo couldn't be loaded: psql: error: FATAL:  no pg_hba.conf entry for host "::1", user "mu_user", database "my_db", SSL off
```

Ecto.Load apparently tries to connect using tcp instead of using unix socket on specified socket dir, as `psql` command used for loading schema always specifies `--host` param:
https://github.com/elixir-ecto/ecto_sql/blob/1952ce2604419816f327833df858f0125eba5201/lib/ecto/adapters/postgres.ex#L346

Thus `localhost` is specified by command if `hostname` is not explicitly configured on repo. According to `psql` documentation, socked dir might be passed instead to connect using unix sockets.

### Expected behavior

When `socket_dir` is specified, it should be used for connecting to db for commands using `psql` in the background.

### Workaround

As `hostname` is passed to `psql`, just adding it to repo config allows ecto.load to run successfully:
```
config :my_app, MyApp.Repo,
  database: "my_db",
  username: "my_user",
  socket_dir: "/var/run/postgresql"
  hostname: "/var/run/postgresql"
```

**Comment by josevalim** [comment]
Good catch! A pull request that changes Postgres to consider the socket option and pass the proper flag to psql will be welcome!

**Comment by jesenko** [comment]
@josevalim Great, I will try to prepare a PR in the following days...

Btw, is there a reason `--host` is explicitly passed to `psql` even if it is not defined in connection params?

```
host = opts[:hostname] || System.get_env("PGHOST") || "localhost"
```

I guess that `psql` should already use `PGHOST` environment variable if set - if `hostname` or `socked_dir` is not specified, it might be best if `--host` is not specified at all and `psql` uses its defaults?

E.g.:
```
host = opts[:hostname] || opts[:socket_dir] || opts[:socket]
args =
      if host, do: ["--host", host|args], else: args
```

**Comment by josevalim** [comment]
I don't recall at the moment if there was any particular reason. Although being explicit about it perhaps doesn't hurt?

**Comment by wojtekmach** [comment]
```
~% PGHOST=foo psql
psql: error: could not translate host name "foo" to address: nodename nor servname provided, or not known

~% PGHOST=foo psql --host bar
psql: error: could not translate host name "bar" to address: nodename nor servname provided, or not known
```

so the --host takes precedence over PGHOST, which makes sense.

From [`Postgrex.start_link/1`](https://hexdocs.pm/postgrex/Postgrex.html?#start_link/1) (emphasis mine)

> :socket_dir - Connect to PostgreSQL via UNIX sockets in the given directory; The socket name is derived based on the port. This is the preferred method for configuring sockets and **it takes precedence over the hostname**. If you are connecting to a socket outside of the PostgreSQL convention, use :socket instead;

(https://hexdocs.pm/ecto_sql/Ecto.Adapters.Postgres.html seems to exactly mirror that behaviour)

I think we have two options:

Option 1: following Postgrex defaults:

```
host = opts[:socket_dir] || opts[:hostname] || System.get_env("PGHOST") || "localhost"
args = ["--host", host | args]
```

Option 2: following psql defaults:

```
host = opts[:socket_dir] || opts[:hostname]
args = if host, do: ["--host", host | args], else: args
```

(that is, if neither socket_dir or hostname is set, we let psql do it's thing which is default to using unix socket but also treat PGHOST and friends accordingly)

I'd probably go with Option 1 Postgrex defaults since I think that's probably what users would expect given the behaviour for the regular connection options.

(FWIW MyXQL defaults to using unix sockets by default exactly because so does mysql cli so we differ a bit from Postgrex.)

**Comment by jesenko** [comment]
+1 for Option 1.

What about `socket` param - it takes precedence over `socket_dir`:

> `:socket` - Connect to PostgreSQL via UNIX sockets in the given path. This option takes precedence over the `:hostname` and `:socket_dir`;

Not sure however if `psql` supports passing `socket` as `--host` param...

```
host = opts[:socket] || opts[:socket_dir] || opts[:hostname] || System.get_env("PGHOST") || "localhost"
args = ["--host", host | args]
```

**Comment by wojtekmach** [comment]
> Not sure however if psql supports passing socket as --host param...

it does not, it tries to use the socket (file) as dir.

**Comment by jesenko** [comment]
Hm should it probably raise then?

I opened related PR - not sure if integration tests would be needed for this (probably involves configuring related Postgres db used in test)?

**Comment by wojtekmach** [comment]
raising sounds good, printing a warning that :socket is ignored would be ok too because then we'd fallback to other options and if we still can't connect we'd error anyway.
