### ISSUE TITLE
How to add a lock timeout to migrations?

### ISSUE THREAD

**Issue by samphilipd** [elixir-ecto/ecto_sql#31]
We ran into a scenario recently where we had downtime for the following reason:

1. We had a long running transaction open
2. We had a migration that attempted to take an ACCESS EXCLUSIVE lock (happens for all `ALTER TABLE` commands)

This caused all queries to be queued behind the migration, which was waiting to get a lock.

We'd like to automatically set a lock timeout on migrations to avoid this problem in future. The command is:

`SET lock_timeout TO '5s'`

We could add this manually inside every migration we create but that is tedious and prone to people forgetting. Is there a way to use ecto to automatically execute this SQL at the start of every DDL transaction?

**Comment by josevalim** [comment]
I see. Then we should find out a mechanism to make this possible. I have nothing from the top of my head. Suggestions are welcome.

**Comment by samphilipd** [comment]
How about configuring the lock timeout via Ecto config and adding a special case for this?

**Comment by samphilipd** [comment]
@josevalim it's not quite the same as having the timeout on Elixir side.

You can have a short "lock wait" timeout with an arbitrarily long migration. If you use an Elixir timeout it places a limit on the overall migration time.

**Comment by josevalim** [comment]
@samphilipd not sure if we are talking about the same thing, but I was thinking about a timeout for each individual migration.

**Comment by samphilipd** [comment]
You mean a timeout inside of Elixir, right? This still will not accomplish the same goal.

A lock timeout is specifically about how long each statement will wait to get a lock. e.g. ALTER TABLE requires an ACCESS EXCLUSIVE lock, so a lock timeout of 5s will mean that this statement will wait up to 5s before taking that lock, otherwise the transaction will fail.

This is not the same as a timeout on the entire transaction. Since the transaction could have statements in it that take much longer than 5s to execute, and this is fine even with a 5s lock timeout.

**Comment by josevalim** [comment]
@samphilipd oh, perfect, I see it now. Thanks for explaining! :+1:

I think the best way then is to have a `before_change` and `after_change` callback and you could do `use MyApp.Migration` that defines those automatically. Thoughts?

**Comment by samphilipd** [comment]
That would be perfect!

**Comment by samphilipd** [comment]
FWIW, lock timeouts are a good idea because of the way database lock queues work. If you have a long running transaction, the migration will wait for an ACCESS EXCLUSIVE lock until that transaction completes.

During the time it is waiting **every other type of lock** will get queued up behind it, including even SELECT statements.

This has caused production downtime for us on several occasions.

**Comment by josevalim** [comment]
@wojtekmach @michalmuskala @zachdaniel @qcam what do you think about the solution I propose in my last comment? I am not a big fan of callbacks but since the callbacks are directly defined in the module that uses it, it should be fine.

**Comment by zachdaniel** [comment]
I think it follows some preexisting standards like `use MyApp.Schema`, so it follows the principle of least surprise fairly well. I also see sam’s point about setting some kind of default, but I think ecto’s job on that front is pretty much done, since you can timeout individual operations via code and entire migrations via config. Timing out per lock is too granular to be a config in ecto.

Lots of words to say that I agree :) `before_change` might be too confusing of a name, since migrations can have a `def change` and people might think you’re talking about that. Maybe like `before_operation` or modeling them like exunit callbacks as `setup`.

**Comment by zachdaniel** [comment]
I think `before_migration` is best actually. Just put it in the docs that its in the transaction with the migration and then its good to go.

**Comment by zachdaniel** [comment]
Also, this sounds like a good thing for me to do! I can get started tomorrow, if that works!

**Comment by wojtekmach** [comment]
+1 for callbacks in this particular case.

**Comment by qcam** [comment]
Would these callbacks be invoked for each `change` in migrations or per DDL statement, since there could be multiple statements in `change`?

If the latter is the case, would it be more flexible to introduce `options` in `create`, `alter`, and `create_if_exists` and conveniently avoid having callbacks in config (if I comprehended the thread correctly)?

```ex
options = [
  before_callback: before_fun
  after_callback: after_fun
]

table = table(:foo) do
  ...
end

create(table, options)
```

**Comment by samphilipd** [comment]
I am imagining two places:

1. After transaction `BEGIN`, before any statements
2. Before transaction `COMMIT`, after any statements

With this in mind, perhaps `after_begin` and `before_commit` might be better names.

I wonder if they should also raise in the case that DDL transactions are disabled?

**Comment by josevalim** [comment]
I would like to keep it `before_change` and `after_change` because we don't need to make them transaction specific and it would still address your use case. We may need to introduce transaction specific ones... but I don't think that should be the starting point. If it makes any sense. That's also why I wanted something more specific than before_migration / after_migration, because if we introduce transaction specific ones, the ordering of it in regards to before_migration/after_migration wouldn't be clear.

**Comment by zachdaniel** [comment]
So the transaction lock timeout needs to be set in every single transaction? Or before every statement? I thought we could just do it once at the beginning.

**Comment by josevalim** [comment]
It needs to run inside each migration's transaction before we invoke change/up/down.

**Comment by zachdaniel** [comment]
I think `before_migration` would be clearer then, to avoid people thinking that `before_change` *doesnt* fun when you move a migration from `def change` to `def up/down`. I don’t mind if others don’t think that would be a point of confusion though, it’s a small detail.

**Comment by josevalim** [comment]
I have not. :) please go ahead.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by zachdaniel** [comment]
Got it mostly done, just need to figure out how to test it. I'll wrap it up tomorrow.

**Comment by zachdaniel** [comment]
So I started in on testing this, and I realized a sort of interesting/confusing aspect to it. Lets say you had a migration like:

```
defmodule MyMigration do
  def before_change() do
    execute "setup some stuff"
  end

  def after_change() do
    execute "tear down some stuff"
  end

  def change() do
    execute "do some stuff"
  end
end
```

The confusing part of this is that `before_change` and `after_change` would be adding *no behavior* to the `down` of the migration. If you wanted to do that, you'd have to use `execute/2`. Not really sure what I'm getting at here aside from the fact that it seems a bit weird to have these wrappers that read like they will wrap both the up and the down in sql, but in reality they don't.

Any thoughts? Is that confusion just in my head?

**Comment by zachdaniel** [comment]
So if its called `after_begin` and `before_commit` would these callbacks not be run if the transaction is disabled? Since w/o a transaction there aren't explicit begin/end steps.

**Comment by josevalim** [comment]
@zachdaniel yes, exactly.

**Comment by zachdaniel** [comment]
I think that can work, we'll just want to make it clear then that if you do something like this:

```
defmodule MyMigration do
  @disable_ddl_transaction true

  def after_begin() do
    ...
  end
end

 def change() do
    ...
  end
```
that your callback is not run.

It won't be user friendly to `raise` now that we're doing this mixin style where they might do `use MyApp.Migration`. But silently not doing it may not be great also. Probably just something that is resolved with documentation.

**Comment by josevalim** [comment]
Yeah, agreed with solving it with docs.

**Comment by josevalim** [comment]
Closing in favor of the PR. @samphilipd, can you please take a look at #53 as well? Thanks.
