### ISSUE TITLE
Specifying custom "schema_migrations" broken

### ISSUE THREAD

**Issue by anthonator** [elixir-ecto/ecto_sql#315]
### Environment

* Elixir version (elixir -v): 1.11.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.2
* Ecto version (mix deps): 3.6.0
* Database adapter and version (mix deps): postgrex  0.15.8
* Operating system: Alpine Linux

### Current behavior

When running migrations on a repo that has a `:migration_source` specified we get the following error.

```
** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: 45, message: nil, postgres: %{code: :undefined_table, file: "namespace.c", line: "431", message: "relation \"schema_migrations\" does not exist", pg_code: "42P01", routine: "RangeVarGetRelidExtended", severity: "ERROR", unknown: "ERROR"}, query: nil}}
    (ecto_sql 3.6.0) lib/ecto/adapters/postgres.ex:223: anonymous fn/4 in Ecto.Adapters.Postgres.lock_for_migrations/3
    (ecto_sql 3.6.0) lib/ecto/adapters/sql.ex:1005: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
    (ecto_sql 3.6.0) lib/ecto/adapters/postgres.ex:218: Ecto.Adapters.Postgres.lock_for_migrations/3
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:487: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:388: Ecto.Migrator.run/4
    (ecto_sql 3.6.0) lib/ecto/adapters/sql/sandbox.ex:558: Ecto.Adapters.SQL.Sandbox.unboxed_run/2
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
```

I have confirmed that migrations do work after removing `:migration_source` from the repo config.

### Expected behavior

Migrations should run successfully.

**Comment by josevalim** [comment]
Thank you for the report. This should be fixed on bf80ce94a36538823712785e160332a58920e2f6. Can you please give it a try?

**Comment by anthonator** [comment]
This does seem to fix the the issue.

**Comment by wojtekmach** [comment]
Thanks for verifying the fix!

**Comment by anthonator** [comment]
Just curious if we will see this in a patch release.
