### ISSUE TITLE
Error when altering schema prefix with locked schema_migrations table. (3.6.0 release)

### ISSUE THREAD

**Issue by abMatGit** [elixir-ecto/ecto_sql#326]
### Environment

* Elixir version (elixir -v): `1.11.3`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `PostgreSQL 13.1`
* Ecto version (mix deps): `3.6.1`
* Database adapter and version (mix deps): `Postgrex 0.15.9`
* Operating system: `Mac OS Catalina 10.15.7` 
* Suspected culprit version: `3.6.0`

### Current behavior
Hello! We are trying to run schema migrations where we set the `schema_prefix` to a non-`public` value. 

The migration looks like: 
```elixir
  def up do
    execute("ALTER SCHEMA public RENAME to new_schema;")

    execute("""
      DO $$
      BEGIN
          EXECUTE 'ALTER DATABASE ' || current_database() || ' SET search_path TO new_schema, public';
      END$$;
    """)
  end
```

(Obviously code could be better however c'est la vie). The issue we're finding is that because the `schema_migrations` table is locked, it will actually prevent writing this migration number since the search_path has changed! 

The error we are getting is: 
```
00:55:54.136 [info]  execute "  DO $$\n  BEGIN\n      EXECUTE 'ALTER DATABASE ' || current_database() || ' SET search_path TO new_schema, public';\n  END$$;\n"

00:55:54.137 [info]  == Migrated 20210419105909 in 0.0s
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "schema_migrations" does not exist
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1
```

If this is not in fact a bug, what would be the recommended way of ensuring the `schema_migrations` table is also ported to the `new_schema`? 

### Expected behavior

Migration is successful. 
Postgres `schema_migrations` lives on the `new_schema` schema (instead of `public`).
Migrator successfully commits migration number to `schema_migrations` table.

**Comment by josevalim** [comment]
There may be other options but the best option I can think for now is to send a PR to Ecto to configure what is the prefix (i.e. schema) the migration table is written to. After all, the reason we lock the table is to avoid concurrent migrations from running.

**Comment by josevalim** [comment]
Oh, note you can also pass a --prefix option when calling `mix ecto.migrate`, and that will run the migrations on the given prefix/schema. That's the most straight-forward way right now: https://github.com/elixir-ecto/ecto_sql/blob/6276527714ebb863ab0c8239816c2c03784c14d5/lib/mix/tasks/ecto.migrate.ex#L81

**Comment by abMatGit** [comment]
@josevalim wow thank you for the super fast reply 🙏 !! 

We unfortunately did try using the `--prefix` option however it arrived at a deadlock (I should have said so in the initial post). 
Here is how we ran the code: 
```
>> mix ecto.migrate --prefix new_schema

01:20:03.742 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :project, Project.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) schema "new_schema" does not exist
```
Should we take this to the ecto repository still? The error mentions `The "schema_migrations" table, which Ecto uses for managing migrations, was defined by another library` which is presumably this library right?

**Comment by josevalim** [comment]
You need to create/rename the schema before you run migrations. Once you do that, it should work.

**Comment by abMatGit** [comment]
@josevalim perfect that's what we'll do. Thanks again for your time! 🙏
