### ISSUE TITLE
Migrations under "test/support" not detected

### ISSUE THREAD

**Issue by mbuhot** [elixir-ecto/ecto_sql#33]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11
* Ecto version (mix deps): 3.0.0
* Database adapter and version (mix deps): Postgrex 0.14.0
* Operating system: MacOS 10.14.1

### Current behavior

I'm migrating a library from ecto 2.2 to ecto 3.0.
The library contains a test Repo under `test/support/repo.ex` and associated migrations under `test/support/migrations/*.exs`.

I've configured the `priv:` option for the repo accordingly for the `test` Mix config:

```elixir
config :my_lib, MyLib.Test.Repo,
  database: "my_lib_test",
  username: "postgres",
  password: "postgres",
  priv: "test/support"
```

Running `MIX_ENV=test mix ecto.migrations` produces:

```
Repo: MyLib.Test.Repo

  Status    Migration ID    Migration Name
--------------------------------------------------
```

Similarly, `MIX_ENV=test mix ecto.migrate` does not apply any migrations:

```
mix ecto.migrate

21:30:12.472 [debug] QUERY OK source="schema_migrations" db=1.0ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0 FOR UPDATE []

21:30:12.474 [info]  Already up
```

### Expected behavior

The migration scripts in the `test/support/migrations` directory should be applied.

I believe this behaviour is due to the migrations path being initially validated relative to the mix project: https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/ecto_sql.ex#L92 

Then later re-evaluated relative to the `Application.app_dir`: https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/migrator.ex#L36 which evaluates to `_build/test/lib/my_lib/test/support/migrations`.  As this directory doesn't exist, no migrations are found.

If the new behaviour is intended, then any advice on managing a test-only repository and migrations for a library, such that the migrations are not included in the final hex package would be appreciated.

Thanks

**Comment by josevalim** [comment]
Can you please provide a simple app that reproduces this? It will make it
much easier to fix the bug. Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
I think I got a fix, can you please try master out? Thank!
