### ISSUE TITLE
"Surprising" difference when running query as a subquery and as a top level query

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto_sql#331]
### Environment

* Elixir version (elixir -v): any
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12, but any DB apply
* Ecto version (mix deps): 3.6.2
* Database adapter and version (mix deps): `postgrex` 0.15.9
* Operating system: macOS 11

### Current behavior

```elixir
# We need to use `fragment/1` here to refer to `val_p1` from the `:select`
q1 = from f in "foos", select: %{val_p1: f.val + 1}, order_by: fragment("val_p1")

q2 = from v in subquery(q1), select: %{val_p1: v.val_p1}

Repo.all(q2)
# [debug] QUERY OK db=0.3ms queue=0.5ms idle=1575.2ms
# SELECT s0."val" FROM (SELECT ss0."id" + 1 AS "val" FROM "foos" AS ss0 ORDER BY val) AS s0 []
# …

Repo.all(q1)
# [debug] QUERY ERROR source="foos" db=0.0ms queue=10.4ms idle=1044.5ms
# SELECT s0."id" + 1 FROM "foos" AS s0 ORDER BY val []
# ** (Postgrex.Error) ERROR 42703 (undefined_column) column "val" does not exist
#
#     query: SELECT s0."id" + 1 FROM "foos" AS s0 ORDER BY val
#     (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
#     (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
#     (ecto 3.6.2) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
#     (ecto 3.6.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

This can be obvious for people familiar with the Ecto internals, but it may be surprising for some newcomers.

### Expected behavior

Ideally both queries would work. How to make them work is up to debate. I see few possible solutions:

- always alias selected column, but that can significantly increase queries size
- somehow detect when to do aliasing in top-level queries and alias only when required
- alias all fields when `:select` or `:select_merge` is used

**Comment by josevalim** [comment]
Whenever you use a `fragment`, you are going into "no men's land". You can refer to things that may be there but, such as column names or intermediate table names but, generally speaking, relying on anything in the generated query may break at any time and I don't think we should try to make bad behaviour consistent. The remaining of the discussion can happen in https://github.com/elixir-ecto/ecto/issues/3159. Thanks.
