### ISSUE TITLE
Suggestion to make structure_load/2 and structure_dump/2 public

### ISSUE THREAD

**Issue by staring-frog** [elixir-ecto/ecto_sql#332]
Hi,
squashing migrations into a single sql file seems to be a useful feature when there are a lot of them accumulated over time. It seems like currently this sql file is usually loaded in migration in one go via `Ecto.Adapters.__adapter__.structure_load/2` like it's done in Ruby on Rails, but that is a private API, which could break in the future.  What do you think about making `structure_load/2` and `structure_dump/2` (?) public, so they could be used in migrations safely? `Ecto.Adapters.SQL` seems to be a suitable place for that. I think I could make a PR.

**Comment by wojtekmach** [comment]
I believe it's considered public API, these callbacks are documented:

- [`c:Ecto.Repo.__adapter__/0`](https://hexdocs.pm/ecto/Ecto.Repo.html#c:__adapter__/0)
- [`c:Ecto.Adapter.Structure.structure_load/2`](https://hexdocs.pm/ecto_sql/Ecto.Adapter.Structure.html#c:structure_load/2)

I suppose the contract are somewhat more important for people implementing the adapters, not necessarily consuming them, but I think it's fine to call them. But let's wait for @josevalim opinion.

**Comment by josevalim** [comment]
Yes, they are definitely public. I also think you should be able to do: `execute File.read!("foo.sql")` in your migration files.

**Comment by staring-frog** [comment]
Oh, cool, thanks guys, totally missed that!

**Comment by staring-frog** [comment]
I'll make a note here just for fellow googlers: `execute` approach failed on me with
```
(ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
(elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
(ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:848: Ecto.Adapters.SQL.execute_ddl/4
(ecto_sql 3.6.2) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
(ecto_sql 3.6.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
(elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
(ecto_sql 3.6.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
(ecto_sql 3.6.2) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
(stdlib 3.12.1) timer.erl:166: :timer.tc/1
(ecto_sql 3.6.2) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
(ecto_sql 3.6.2) lib/ecto/migrator.ex:324: Ecto.Migrator.attempt/8
(ecto_sql 3.6.2) lib/ecto/migrator.ex:250: anonymous fn/5 in Ecto.Migrator.do_up/5
(ecto_sql 3.6.2) lib/ecto/migrator.ex:295: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
(ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:1017: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
(db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
(ecto_sql 3.6.2) lib/ecto/migrator.ex:313: Ecto.Migrator.run_maybe_in_transaction/4
(elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
(stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
But Ecto.Repo.__adapter__/0 one works fine.

**Comment by wojtekmach** [comment]
Out of curiosity, what was the exception? It is missing from the stacktrace.

**Comment by josevalim** [comment]
Oh, it may be that execute expects a single instruction. Maybe wrapping in BEGIN/END helps but maybe not.

**Comment by staring-frog** [comment]
Right, looks like it, it was:
`** (Postgrex.Error) ERROR 42601 (syntax_error) cannot insert multiple commands into a prepared statement`

**Comment by staring-frog** [comment]
Wrapping into a BEGIN/END block still gives:
```
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "SET"
query: --
-- PostgreSQL database dump
--
-- Dumped from database version 11.8 (Debian 11.8-1.pgdg90+1)
-- Dumped by pg_dump version 13.3 (Debian 13.3-1.pgdg100+1)
BEGIN
SET statement_timeout = 0;
...
```
Anyway, structure_load/2 is fine...

**Comment by brainlid** [comment]
I [wrote up a post](https://fly.io/phoenix-files/loading-structure-sql-on-prod-without-mix/) on how to do this in our `MyApp.Release` module without `mix` on the server. I think there is an opportunity to make it easier to call and possibly those changes could be upstreamed. 

But hopefully this can help others looking for a similar solution.

**Comment by wojtekmach** [comment]
Nice write-up! I agree, I think it would be really nice if we could do structure load with less hassle, akin to generated MyApp.Release migrate() and rollback() functions by Phoenix.

PR welcome!

If `repo.config()[:priv]` would return an absolute path (in config/0 we know the :otp_app so can compute application root) and then maybe we replace `structure_load(default, repo.config())` with `structure_load(repo.config())`.
