### ISSUE TITLE
Missing documentation for `change` option in ecto.gen.migration

### ISSUE THREAD

**Issue by staring-frog** [elixir-ecto/ecto_sql#334]
Option is here 
https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.gen.migration.ex#L16
https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.gen.migration.ex#L80
but it's not documented in a help message:
https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.gen.migration.ex#L45

**Comment by josevalim** [comment]
Do you have a use case for it? Given it is he migration change itself, it is not really meant to be given in the command line, but from other tasks, but I don’t think it is used anywhere.

**Comment by staring-frog** [comment]
Oh, actually I thought it's a feature for code-generation. Just came across while viewing the code. I think it's worth adding a comment that it's an option for internal usage then.

**Comment by josevalim** [comment]
Can you please send a PR? :)

**Comment by staring-frog** [comment]
Ok, will do :D

**Comment by josevalim** [comment]
Fixed, thanks.
