### ISSUE TITLE
ecto.gen.migration doesn't pass through `migrations_path` option to `mix ecto.migrate`

### ISSUE THREAD

**Issue by staring-frog** [elixir-ecto/ecto_sql#335]
Both commands have `migrations_path` option:
https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.gen.migration.ex#L20
https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.migrate.ex#L25

The call is here: https://github.com/elixir-ecto/ecto_sql/blob/master/lib/mix/tasks/ecto.gen.migration.ex#L84
It should pass that option for consistent behaviour.

**Comment by josevalim** [comment]
Can you please send a PR? :)

**Comment by staring-frog** [comment]
Ok, will do :D

**Comment by staring-frog** [comment]
Great, thanks!
