### ISSUE TITLE
Missing function 

### ISSUE THREAD

**Issue by pcarvsilva** [elixir-ecto/ecto_sql#337]
Just got this error migrating to new version.

** (UndefinedFunctionError) function Ecto.Adapters.Postgres.checked_out?/1 is undefined or private
        (ecto_sql 3.6.1) Ecto.Adapters.Postgres.checked_out?(%{cache: #Reference<0.1778473297.1164050433.236011>, op
ts: [timeout: 15000, pool_size: 10, pool: DBConnection.ConnectionPool], pid: #PID<0.3227.0>, repo: MyApp.Repo, sql: E
cto.Adapters.Postgres.Connection, telemetry: {MyApp.Repo, :debug, [:my_app, :repo, :query]}})
        (ecto 3.6.2) lib/ecto/repo/queryable.ex:230: Ecto.Repo.Queryable.execute/4
        (ecto 3.6.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (ecto 3.6.2) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3

**Comment by josevalim** [comment]
Please upgrade ecto_sql to 3.6.2 too.
