### ISSUE TITLE
Add `--log-full-sql` flag

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto_sql#345]
This migration:

```elixir
defmodule MyApp.Repo.Migrations.CreateTestTable do
  use Ecto.Migration

  def change do
    create table("test") do
      add :city,    :string, size: 40
      add :temp_lo, :integer
      add :temp_hi, :integer
      add :prcp,    :float

      timestamps()
    end
  end
end
```

Will print this SQL:

```
$ mix ecto.migrate --log-sql
21:29:36.461 [info]  == Running 20210702012346 MyApp.Repo.Migrations.CreateTestTable.change/0 forward
21:29:36.462 [info]  create table test
21:29:36.466 [debug] QUERY OK db=3.2ms
CREATE TABLE "test" ("id" bigserial, "city" varchar(40), "temp_lo" integer, "temp_hi" integer, "prcp" float, "inserted_at" timestamp(0) NOT NULL, "updated_at" timestamp(0) NOT NULL, PRIMARY KEY ("id")) []
21:29:36.467 [info]  == Migrated 20210702012346 in 0.0s
```

however it doesn't tell the whole story. Under the hood, Ecto would wrap it in a transaction, lock the schema migrations table, run the migration, insert an entry into schema migrations afterwards, etc.

Currently there's no way way to get this information other than tailing the DB log. By having an easier way to debug what's going on, users would have more visibility into what `@disable_ddl_transaction true` and `@disable_migration_lock true` does too.

Let's add an `--log-full-sql` flag that'd print all executed sql statements.

cc @dbernheisel

**Comment by josevalim** [comment]
Instead of a boolean, I would probably introduce `--log-sql-mode all | commands`.

**Comment by wojtekmach** [comment]
Sounds good!

**Comment by v0idpwn** [comment]
@josevalim I'm not sure if I understand your suggestion. In this case, the user would run:

```shell
mix ecto.migrate --log-sql --log-sql-mode all
```

and

```shell
mix ecto.migrate --log-sql
```

would assume a default mode of "commands"?

**Comment by josevalim** [comment]
@v0idpwn precisely!

**Comment by dbernheisel** [comment]
I'd love to implement this. Give me a week and I should have a PR
