### ISSUE TITLE
no function clause matching in :logger_config.less_or_equal_level/2

### ISSUE THREAD

**Issue by tlvenn** [elixir-ecto/ecto_sql#351]
### Environment

* Elixir version (elixir -v): 1.12.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): CockroachDB 21.1.9
* Ecto version (mix deps): 3.7.0
* Database adapter and version (mix deps): postgrex 0.15.11 / db_connection 2.4.0
* Operating system: OS X 12

### Current behavior

Upon invocation of this code:
`Ecto.Adapters.SQL.query(__MODULE__, "SAVEPOINT cockroach_restart", [], log: log)` with `log` = `true`

The following error occurs:
>** (FunctionClauseError) no function clause matching in :logger_config.less_or_equal_level/2 
(kernel 8.1) logger_config.erl:75: :logger_config.less_or_equal_level(false, 6)
(logger 1.12.3) lib/logger.ex:767: Logger.__should_log__/2
(ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:924: Ecto.Adapters.SQL.log/4
(db_connection 2.4.0) lib/db_connection.ex:1460: DBConnection.log/5
(postgrex 0.15.11) lib/postgrex.ex:287: Postgrex.query_prepare_execute/4

I am not exactly sure when it got broken or the behavior changed, but this used to work before.

### Expected behavior

Invoking `Ecto.Adapters.SQL.query/4` with `log:false` in the `opts` should work without raising any error

**Comment by tlvenn** [comment]
Ha i found the culprit and what actually changed on my side to trigger this:
> `config :backend, MyRepo, log: false` in config/prod.exs

I am not exactly sure what is the expected behavior here. I disable the logging globally at the repo level but i ask to log when I invoke a pretty low level function such as `Ecto.Adapters.SQL.query/4`.

**Comment by josevalim** [comment]
Can you please try master? I believe this has been recently addressed.

**Comment by tlvenn** [comment]
Sure thing @josevalim, let me try, i keep you posted, many thanks.

**Comment by tlvenn** [comment]
Unfortunately, I got the same issue on master @josevalim

**Comment by v0idpwn** [comment]
@tlvenn if I understand you correctly, you're passing `log: true`?

The `:log` option is supposed to be either a logger level (see https://hexdocs.pm/logger/1.12/Logger.html#module-levels) or false.

**Comment by tlvenn** [comment]
Good catch @v0idpwn, that was indeed as trivial as this but was somehow masked down the line because the error was on a no clause matching on `false`.

Sorry for the noise @josevalim.

**Comment by vlad-rw** [comment]
This is really confusing behaviour - if it was up to me then I would remove the boolean part of the value entirely or create a function clause matching it and then log out a proper error explaining that the configuration is wrong.
