### ISSUE TITLE
New migration locking not compatible with Percona XtraDB Cluster in strict mode

### ISSUE THREAD

**Issue by TBK145** [elixir-ecto/ecto_sql#360]
### Environment

* Elixir version (elixir -v): 1.12.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): mysql 5.9 (Percona XtraDB Cluster)
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps): myxql 0.5.1
* Operating system: ~$ Ubuntu Focal

### Current behavior

We've upgraded our ecto_sql version from 3.3.4 to 3.7.1, and now we can't run migrations anymore. This is the error:
```
** (MatchError) no match of right hand side value: {:error, %MyXQL.Error{connection_id: 655406506, message: "Percona-XtraDB-Cluster prohibits use of RELEASE_LOCK with pxc_strict_mode = ENFORCING", mysql: %{code: 1105, name: nil}, statement: "SELECT RELEASE_LOCK(\"ecto_Repo.Test\")"}}
    (ecto_sql 3.7.1) lib/ecto/adapters/myxql.ex:240: anonymous fn/4 in Ecto.Adapters.MyXQL.lock_for_migrations/3
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.1) lib/db_connection.ex:1531: DBConnection.run_transaction/4
    (ecto_sql 3.7.1) lib/ecto/adapters/myxql.ex:237: Ecto.Adapters.MyXQL.lock_for_migrations/3
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:526: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (stdlib 3.16.1) erl_eval.erl:685: :erl_eval.do_apply/6
```
After some digging I found this is caused by the change in locking in 3.6.0, and there was a note saying to open an issue in case of regressions.

The Percona documentation states this on the new `RELEASE_LOCK` method: https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html#explicit-table-locking

### Expected behavior

Obviously one solution is to change `pxc_strict_mode`, but if this could be made configurable to again support the `FOR UPDATE` lock, we could still use this strict mode.

**Comment by josevalim** [comment]
We are intentionally locking the table to avoid multiple migration runners accessing the same table. I understand why you would want to avoid table locking in general, but in this case table locking is exactly what we want. I would suggest reaching out to Percona folks and ask them to allow disabling strict mode in certain tables. Removing the functionality here could lead your deploys to fail in the future.

**Comment by josevalim** [comment]
And thanks for the report!
