### ISSUE TITLE
Clarification around "Ecto tasks can only be executed once" in docs

### ISSUE THREAD

**Issue by sevenseacat** [elixir-ecto/ecto_sql#373]
### Environment

* Elixir version (elixir -v): 1.12.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps): postgrex 0.15.9
* Operating system: MacOS Monterey

### Current behavior

I have a `mix setup` alias defined in my `mix.exs` file, that runs two different sets of migrations:

```
defp aliases do
  [ 
    setup: ["deps.get", "ecto.setup", "ecto.migrate --migrations-path=priv/repo/data_migrations", "assets"]
  ]
end
```

(I know that `ecto.migrate` can accept multiple migration paths, but not what I'm talking about)

When running this command, the second call to `ecto.migrate` silently does nothing at all, even if I put some `IO.inspect()` calls in ecto_sql itself and recompile. The previous Mix tasks run, the following Mix tasks run, only the second `ecto.migrate` is skipped.

I also replicated it with a dummy task that printed out the migrations in the folders (`[print_migrations: ["ecto.migrations", "ecto.migrations --migrations-path=priv/repo/data_migrations"]]`) and again only the first ran. Running the second standalone does work, but not two at once.

I stumbled across the following in the docs that might be related:

https://hexdocs.pm/ecto_sql/Mix.Tasks.Ecto.Migrate.html

> Since Ecto tasks can only be executed once, if you need to migrate multiple repositories, set :ecto_repos accordingly or pass the -r flag multiple times.

So I think this is related to "Ecto tasks can only be executed once"?

### Expected behavior

I'd either expect it to work (run both sets of migrations) as the commands are being run sequentially, or to get some warning/error when the second command "executes" (though I don't think it is executing at all). As it is, it's a totally silent skipping of the second iteration of the command, no matter what the command is, and that's reeeeeally confusing.

**Comment by josevalim** [comment]
Hi @sevenseacat! This is not really an Ecto behaviour: all Mix tasks are only executed once, unless reenabled. This is because we sometimes create tasks, that depend on other tasks, some repeated, and that could lead to a lot of slowness and duplicate work.

So yes, tasks are only run once, and any clarifications in the docs to make this clearer would be welcome.

**Comment by sevenseacat** [comment]
oh I see! So it's not an Ecto thing, but a general Mix thing. That makes sense, if two tasks both rely on the same task, you don't want to run that dependency twice. Still... Hmm. 

I'll have a look at the Mix docs around aliases and see if its mentioned, and if not, where a note might be worth dropping in. Thanks! :D
