### ISSUE TITLE
Ecto.Adapters.SQL.explain/4 seems to ignore a given timeout parameter although advertising that it is supported

### ISSUE THREAD

**Issue by PragTob** [elixir-ecto/ecto_sql#374]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11.9
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps): postgrex 0.15.13
* Operating system: Mac OSX 11.6.1

### Current behavior

Currently trying to override the default timeout straight in the explain call seems to have no effect and an explain analyze will still timeout after 15 seconds. Use case: I want to explain and analyze and extremely slow query.

Example affected code: `Ecto.Adapters.SQL.explain(repo, :all, query, analyze: true, timeout: 120_000)` although it does look just like [the docs](https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#explain/4-examples): `Ecto.Adapters.SQL.explain(Repo, :all, Post, analyze: true, timeout: 20_000)`

I have minimally reproduced it away from our application in this repo: https://github.com/PragTob/ecto_explain_timeout

Just that there I use a very small time out showing that for explain analyze it doesn't trigger. It seems other calls like a pure `Ecto.Adapters.SQL.query!` are unaffected.

### Expected behavior

I'd like it to respect the timeout override :)

-----------------------------------

Thank you most amazing ecto team for all you do! Go have a bunny!

![WhatsApp Image 2021-10-31 at 09 15 39](https://user-images.githubusercontent.com/606517/148565452-efb7a790-d5a2-4b3f-83b4-0e2514c7c467.jpeg)

**Comment by v0idpwn** [comment]
Fixed on master, thanks for the report (and the bunny!) 💚

**Comment by PragTob** [comment]
Thanks a lot for the quick fix
![IMG_20190407_104422_Bokeh](https://user-images.githubusercontent.com/76113666/148793360-ff17320d-468b-4405-a6fc-90e7fc2c56cf.jpg)
!
