### ISSUE TITLE
Custom types in a migration need triple quotes

### ISSUE THREAD

**Issue by Th3-M4jor** [elixir-ecto/ecto_sql#381]
### Environment

* Elixir version (elixir -v): `1.13.0`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres `12.9`
* Ecto version (mix deps): `3.7.1`
* Database adapter and version (mix deps): postgrex `0.16.1`
* Operating system: Ubuntu 20.04

### Current behavior

If in a migration I attempt to use a custom type whose name is in PascalCase I have to use `:'"CustomType"'` for it to not be passed to the Database as `customtype`.

Example:
```elixir
def change do
    alter table("table_name") do
        add :new_column, :"CustomType"
    end
end
```

It will return an error of `type customtype does not exist`

### Expected behavior

The table is successfully altered.

I understand that this is a bit of an edge case, in that using capital letters in a database is usually bad form, but it's not something you always have control over.
I also understand that almost any potential fix would be a breaking change, instead can a note about this edge case be added to the docs in a future release?

**Comment by josevalim** [comment]
I actually don't think we have a proper fix because we cannot quote the type automatically because sometimes it is an "expression", like `varchar(20)`. So a note to the docs can be helpful. A PR is welcome!
