### ISSUE TITLE
Trying to migrate at runtime, "module is not an Ecto.Migration"

### ISSUE THREAD

**Issue by MeerKatDev** [elixir-ecto/ecto_sql#388]
I'm trying to run selected migrations for tests - there are many tables created, and I need only 2 or 3 per test. I thought I would you use `Ecto.Migrator` to this end.

### Environment

* Elixir version (elixir -v): 13
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL v14
* Ecto version (mix deps): 3.7
* Database adapter and version (mix deps):
  ```
  {:ecto_sql, "~> 3.7"},
  {:postgrex, ">= 0.0.0"},
  ```
* Operating system: MacOS Monterey

### Current behavior
Modules:
```
# dao/test/support/test_repo.ex
defmodule Dao.TestRepo do
  use Ecto.Repo, otp_app: :dao, adapter: Ecto.Adapters.Postgres
end

# dao/mix.exs
  defp elixirc_paths(:test), do: ["lib", "test/support", "priv/repo/migrations"]
  defp elixirc_paths(_), do: ["lib"]

# dao/priv/repo/migrations/20210402151318_create_accounts.exs
defmodule Pos.Migrations.CreateAccounts do
  use Ecto.Migration

  def change do
    create table(:accounts) do
      add(:some_id, :integer)
      add(:some_other_id, :integer)
      ...
    end
  end
```
Config: 
```
config :dao,
	ecto_repos: [Dao.TestRepo]

config :dao, Dao.TestRepo,
	username: "postgres",
	password: "postgres",
	database: "test_db",
	hostname: "localhost"
```
`MIX_ENV=test mix ecto.create` correctly creates the db.

Usage:
```
Ecto.Migrator.up(TestRepo, 20210402151318, CreateAccounts)
# -> ** (UndefinedFunctionError) function Dao.Repo.Migrations.CreateAccounts.__migration__/0 is undefined (module Dao.Repo.Migrations.CreateAccounts is not available)

Ecto.Migrator.run(TestRepo, [{20210402151318, CreateAccounts}], :up, all: true)
# -> ** (Ecto.MigrationError) module Dao.Repo.Migrations.CreateAccounts is not an Ecto.Migration
```

### Expected behavior

It should run the migration at runtime correctly.

**Comment by josevalim** [comment]
You need to move the module into your lib directory then or use Code.require_file to load the file before running the migration.

**Comment by MeerKatDev** [comment]
Why is this:
> defp elixirc_paths(:test), do: ["lib", "test/support", "priv/repo/migrations"]

not enough?

**Comment by MeerKatDev** [comment]
yes, cause I'm running tests

**Comment by v0idpwn** [comment]
I'm guessing here, but maybe its because these are `exs` files?

**Comment by josevalim** [comment]
Yup, .exs files would explain it.

**Comment by MeerKatDev** [comment]
If I copy the migration under `lib/version_name.ex` (not exs), it still doesn't get loaded. 

It works only with `Code.require_file`. @josevalim is there a way to do this from mix.exs?
