### ISSUE TITLE
I believe this section of the docs is incorrect and could be improved

### ISSUE THREAD

**Issue by maxmarcon** [elixir-ecto/ecto_sql#406]
https://github.com/elixir-ecto/ecto_sql/blob/427468fb653dde0d0150aaa8d2bb2feeca31838d/lib/ecto/adapters/sql/sandbox.ex#L249

I think this section of the docs is incorrect or at least misleading and could be improved.

> For example, imagine multiple tests are
  trying to insert the same user to the database. They will attempt to
  retrieve the same database lock, causing only one test to succeed and
  run while all other tests wait for the lock.

How can this ever happen? Each test uses its own transaction, isolated from the rest. Even if different tests try to insert the same data, they will never cause a conflict because the transactions of the sandbox are never committed. In fact, my tests do this all the time: each test inserts its own data calling the same fixture functions. The primary keys of the rows they insert overlap a lot, and I've never seen a conflict. There can't be conflicts if you're not committing a transaction.
Also which database lock will they "attempt to retrieve" when inserting a row? No locks are acquired when inserting a new row. 

>For example, instead of:
      def insert_user do
        Repo.insert! %User{email: "sample@example.com"}
      end
  prefer:
      def insert_user do
        Repo.insert! %User{email: "sample-#{counter()}@example.com"}
      end
      defp counter do
        System.unique_integer [:positive]
      end

I think this is unnecessary for the reasons stated above: each test operates in its own transaction, which is a completely isolated world. Different tests can insert the same row and they will never see each other's data.

I think that the concerns stated here apply to the situation where the test data is inserted _before_ running the tests (i.e. not within the sandbox transaction), for example with a test DB that has been seeded beforehand. In that case, yes, different tests may try to acquire a lock on the same rows and cause deadlocks. However, this should never be a problem if the test data is inserted from within the sandbox transaction.

Do you agree? Or am I missing something important?

Thanks!

**Comment by josevalim** [comment]
It is missing the information there is a unique index on the email column. I will update.

**Comment by v0idpwn** [comment]
Hope this helps to understand how it happens: https://gist.github.com/v0idpwn/dc621ca348837a590dac01fd909126e2

**Comment by greg-rychlewski** [comment]
FWIW, the deadlock in the insert case occurs because each transaction is waiting on the other to commit before it can proceed. 

How this is implemented in postgres is that a transaction takes an "exclusive" lock on its own transaction id.  When another transaction comes along and sees the potential for a conflict (i.e. with inserting the same unique value) it will attempt to take a "share" lock out on the other transaction's id. But this has to wait for the original transaction's "exclusive" lock to disappear (i.e. for that transaction to commit/rollback). So when both transactions are waiting on each other in this way, there is a deadlock.

Reference:
https://www.postgresql.org/docs/current/view-pg-locks.html

>Throughout running a transaction, a server process holds an exclusive lock on the transaction's virtual transaction ID. If a permanent ID is assigned to the transaction (which normally happens only if the transaction changes the state of the database), it also holds an exclusive lock on the transaction's permanent transaction ID until it ends. When a process finds it necessary to wait specifically for another transaction to end, it does so by attempting to acquire share lock on the other transaction's ID (either virtual or permanent ID depending on the situation). That will succeed only when the other transaction terminates and releases its locks.

**Comment by maxmarcon** [comment]
Thanks @greg-rychlewski that's the bit of information I was missing!

I have to confess I had no clue postgres was that smart and would try to detect whether 2 transactions can potentially create a deadlock when inserting new data. I'm a bit baffled as to why my async tests never see this problem (I've never seen a deadlock!) even though they always insert the same data. What I suspect it's happening is that one of my test is waiting on the other to terminate and release the lock. That would mean that the speed of my test suite could be improved. I'll test this out.

Again, I had no idea DB would perform that kind of check during insertion, I was assuming all checks would be performed when trying to commit the transaction. Apparently I learned something new today.

>Also just in general, transactions are not completely in their own world when it comes to writing. You cannot update the same row as another transaction until it has committed. If this wasn't the case then imagine a scenario where 2 transactions are incrementing the same row:

My point was specifically about writing new data, not updating existing data. When it comes to updating existing data, I was well aware that different transactions could (and should) be able to get on each other's toes.

**Comment by maxmarcon** [comment]
@v0idpwn thanks for your example, too!
