### ISSUE TITLE
MyXQL doesn't quote locks

### ISSUE THREAD

**Issue by matiasgarciaisaia** [elixir-ecto/ecto_sql#441]
### Elixir version

1.8

### Database and Version

MySQL 5.7.33 (RDS) with "ANSI_QUOTES" in sql_mode

### Ecto Versions

3.7.1

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.5.1

### Current behavior

1. Setup a database with `ANSI_QUOTES` in its `sql_mode` setting.
2. Create an Ecto app that will try to run a migration.
3. Run the migration (`mix ecto.migrate`)

Ecto throws an exception due to [the lack of escaping of a lock name](https://github.com/elixir-ecto/ecto_sql/blob/1ce10220f73e376e2c34ebef60efa4defb1e1975/lib/ecto/adapters/myxql.ex#L257) (there may be other such scenarios).

```
** (MatchError) no match of right hand side value: {:error, %MyXQL.Error{connection_id: 95080, message: "Unknown column 'ecto_Ask.Repo' in 'field list'", mysql: %{code: 1054, name: nil}, statement: "SELECT RELEASE_LOCK(\"ecto_Ask.Repo\")"}}
    (ecto_sql) lib/ecto/adapters/myxql.ex:244: Ecto.Adapters.MyXQL."-lock_for_migrations/3-after$^0/0-0-"/3
    (ecto_sql) lib/ecto/adapters/myxql.ex:240: anonymous fn/4 in Ecto.Adapters.MyXQL.lock_for_migrations/3
    (ecto_sql) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1512: DBConnection.run_transaction/4
    (ecto_sql) lib/ecto/adapters/myxql.ex:237: Ecto.Adapters.MyXQL.lock_for_migrations/3
    (ecto_sql) lib/ecto/migrator.ex:526: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
```

### Expected behavior

The migration should work, and MyXQL should correctly escape/quote the objects in the emitted SQL.

**Comment by matiasgarciaisaia** [comment]
I think it's important to note that, regardless of the `ANSI_QUOTES` setting, MyXQL should quote the constants and columns names anyway (preferably according to the ANSI standard).

**Comment by josevalim** [comment]
Can you please submit a PR that escapes the lock? Escaping functions exists in `Ecto.Adapters.MyXQL.Connection`.

**Comment by josevalim** [comment]
Closing in favor of the PR!
