### ISSUE TITLE
on test: could not checkout the connection owned by #PID

### ISSUE THREAD

**Issue by gabrielmancini** [elixir-ecto/ecto_sql#472]
### Elixir version

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Database and Version

PostgreSQL 12

### Ecto Versions

ecto 3.9.4 (Hex package) (mix)

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5 (Hex package) (mix)

### Current behavior

testing a multi-tenancy app
the idea -> https://www.germanvelasco.com/blog/how-live-view-got-rid-of-dangling-processes-in-tests 
i am using phoenix 1.7 rc-2 
phx.new --umbrella --binary-id

before i created the schema and then:
```elixir
          Ecto.Migrator.run(
            repo,
            tenant_migrations_path(repo),
            direction,
            opts_with_prefix
          )
```
stacktrace:
```
** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.835.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 10907ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
     stacktrace:
       (db_connection 2.4.3) lib/db_connection.ex:953: DBConnection.transaction/3
       (ecto_sql 3.9.2) lib/ecto/migrator.ex:326: Ecto.Migrator.run_maybe_in_transaction/5
       (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
       (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
       (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### Expected behavior

i see the similar discussion here https://github.com/elixir-ecto/ecto_sql/issues/409
but, how i test migrations?

**Comment by greg-rychlewski** [comment]
You're not able to use shared/manual mode for the Sandbox to test migrations. What happens during a migration is this:

1. A transaction starts
2. The table that tracks completed migrations is locked
3. The migration is run in a separate process.
4. The transaction ends

Some details left out to focus on the main issue. So basically you have 2 processes trying to use the same connection in the same transaction which is not possible. One process can't join another's transaction. It has to wait for it to complete.

I believe you need to use sandbox in auto mode or just use your regular pool to test these.
