### ISSUE TITLE
no case clause matching

### ISSUE THREAD

**Issue by saleynik** [elixir-ecto/ecto_sql#476]
### Elixir version

14.3

### Database and Version

MySQL 5.5

### Ecto Versions

3.7.2

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.5.2

### Current behavior

Unfortunately I don't have any more details, but have been seeing this error in the logs:

** (CaseClauseError) no case clause matching: {:ok, %MyXQL.Result{columns: nil, connection_id: 6786606, last_insert_id: 0, num_rows: 0, rows: nil, num_warnings: 4}}
    (ecto_sql 3.7.2) lib/ecto/adapters/myxql.ex:265: Ecto.Adapters.MyXQL.insert/6
    (ecto 3.7.2) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.2) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto 3.7.2) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.2) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4

### Expected behavior

No error should be raised

**Comment by josevalim** [comment]
This happens because the insert is failing. I am assuming you have a trigger or similar which makes the insert fail. We can improve the error message but it will still fail. Do you kjnow what could be causing the insert to fail?

**Comment by saleynik** [comment]
Unfortunately the information in the log is insufficient to provide any more information for this error.  At least if the error message could be made more informative that would help.
