### ISSUE TITLE
wrong error message on type validation in migration

### ISSUE THREAD

**Issue by ruslandoga** [elixir-ecto/ecto_sql#483]
### Elixir version

1.14.3

### Database and Version

any

### Ecto Versions

current

### Database Adapter and Versions (postgrex, myxql, etc)

any

### Current behavior

When using an `Ecto.Type` as the type for a column in a migration, it still falls through to https://github.com/elixir-ecto/ecto_sql/blob/c936e6db3e14022ce7032c492eedf7b24b310f6f/lib/ecto/migration.ex#L1397-L1400 even though the suggestion error message says it is supported https://github.com/elixir-ecto/ecto_sql/blob/c936e6db3e14022ce7032c492eedf7b24b310f6f/lib/ecto/migration.ex#L1418-L1431

### Expected behavior

I'd expect either for `Ecto.Type` to allowed in migrations or the suggestion error message to not include it.

**Comment by v0idpwn** [comment]
We could virtually call `type.type()`, but since the underlying type is database specific, I think its better to continue disallowing Ecto.Type and remove the suggestion from the message. WDYT? @josevalim @greg-rychlewski

**Comment by josevalim** [comment]
Yes, let's update the message. I think the reason why we decided to remove is because sometimes the type could come from dependency, and now your migrations would be broken if the dependency changes or is removed.
