### ISSUE TITLE
missing constraint type in migration

### ISSUE THREAD

**Issue by ruslandoga** [elixir-ecto/ecto_sql#485]
### Elixir version

1.14.3

### Database and Version

any

### Ecto Versions

current

### Database Adapter and Versions (postgrex, myxql, etc)

any

### Current behavior

https://github.com/elixir-ecto/ecto_sql/blob/8d4328638aeb5821c1a0fa55454c97cd21171fa0/lib/ecto/adapter/migration.ex#L13-L24

seems to be missing `{:create %Constraint{}}` and `{:drop, %Constraint{}, mode}` and co.

### Expected behavior

The command type should cover all possible cases.

**Comment by v0idpwn** [comment]
Thanks for the reports @ruslandoga!
