### ISSUE TITLE
`Ecto.Query.select/3`seems to crash when selecting non-binary pinned variables

### ISSUE THREAD

**Issue by vereis** [elixir-ecto/ecto_sql#491]
### Elixir version

Elixir 1.11.4 (compiled with Erlang/OTP 24)

### Database and Version

PostgreSQL 14

### Ecto Versions

Ecto 3.9.4, Ecto SQL 3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

Postgrex 0.16.5

### Current behavior

I've got a sample repository which reproduces the issue [here](https://github.com/vereis/ecto_sql_bug_example). Running `MIX_ENV=test docker-compose up -d; mix do ecto.drop, ecto.create, ecto.migrate, test` will fail doing something that feels like it should pass.

tl;dr: it looks like `Repo.select(from x in Schema, select: %{something: ^result})` when `result = 123` will cause an error as follows:

```elixir
  1) test I expect this to not crash! (BugExampleTest)
     test/bug_example_test.exs:6
     ** (DBConnection.EncodeError) Postgrex expected a binary, got 123. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
     code: assert {0, ^expectation} = BugExample.Repo.one(from x in BugExample.Schema, select: {count(x), ^expectation})
     stacktrace:
       (postgrex 0.16.5) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.encode_params/3
       (postgrex 0.16.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
       (db_connection 2.4.3) lib/db_connection.ex:1304: DBConnection.encode/5
       (db_connection 2.4.3) lib/db_connection.ex:1404: DBConnection.run_prepare_execute/5
       (db_connection 2.4.3) lib/db_connection.ex:1508: DBConnection.run/6
       (db_connection 2.4.3) lib/db_connection.ex:644: DBConnection.parsed_prepare_execute/5
       (db_connection 2.4.3) lib/db_connection.ex:697: DBConnection.execute/4
       (ecto_sql 3.9.2) lib/ecto/adapters/postgres/connection.ex:102: Ecto.Adapters.Postgres.Connection.execute/4
       (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:858: Ecto.Adapters.SQL.execute!/5
       (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
       (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
       (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
       (ecto 3.9.4) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
       test/bug_example_test.exs:17: (test)
```

Whereas doing `Repo.select(from x in Schema, select: %{something: 123})` works as one would expect.

### Expected behavior

Selecting a field and populating it via pinned variable should work the same way an inlined literal works.

**Comment by greg-rychlewski** [comment]
Hi,

Thank you for the report. It's crashing because you passed an integer when the underlying type is a string. If you do this it should  work:

```elixir
result = "123"
Repo.select(from x in Schema, select: %{something: ^result})
```

The Postgrex driver is not doing automatic type conversion.

**Comment by greg-rychlewski** [comment]
To see what is going on under the hood you can log the queries:

```elixir
    query = from p in Post, select: %{title: 123}
    TestRepo.all(query, log: :info)

    result = 123
    query = from p in Post, select: %{title: ^result}
    TestRepo.all(query, log: :info)
```

produces:

```
09:15:38.080 [info]  QUERY OK source="posts" db=0.9ms queue=1.7ms
SELECT TRUE FROM "posts" AS p0 []

09:15:38.086 [info]  QUERY ERROR source="posts" db=3.0ms queue=0.2ms
SELECT $1 FROM "posts" AS p0 [123]
```

You can see the first query is essentially not caring about your constant. Ecto does post processing after the query is done to insert it.

**Comment by vereis** [comment]
Amazing, so basically its crashing because Postgrex isn't even trying to attempt to do any type conversion.

I managed to work around this issue by explicitly telling what types I expect via `type/2` then! The following patch to my example fixes the issue:

```diff
diff --git a/test/bug_example_test.exs b/test/bug_example_test.exs
index 5286046..d6752d5 100644
--- a/test/bug_example_test.exs
+++ b/test/bug_example_test.exs
@@ -5,15 +5,24 @@ defmodule BugExampleTest do

     # This crashes... :-(
     expectation = 123
-    assert {0, ^expectation} = BugExample.Repo.one(from x in BugExample.Schema, select: {count(x), ^expectation})
+
+    assert {0, ^expectation} =
+             BugExample.Repo.one(
+               from(x in BugExample.Schema, select: {count(x), type(^expectation, :integer)})
+             )
   end
 end
```

Thank you so much for your insight! :pray: :heart:

Closing!
