### ISSUE TITLE
MyXQL - Cannot remove foreign key column with `change`

### ISSUE THREAD

**Issue by KiKoS0** [elixir-ecto/ecto_sql#494]
### Elixir version

1.14.3

### Database and Version

MySQL 5.7/8

### Ecto Versions

ecto 3.9.4 ecto_sql 3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.6.3

### Current behavior

I apologize if this issue has already been addressed in a previous discussion. Since MySQL doesn't allow deleting a foreign key column without dropping the foreign key constraint first, I noticed that this migration would fail to rollback. (It works fine with Postgres)
```elixir
defmodule Sample.Repo.Migrations.AddUserIdColumn do
  use Ecto.Migration

  def change do
    alter table(:posts) do
      add :user_id, references(:users)
    end
  end
end
```

```elixir
❯ mix ecto.rollback --step 1
** (MyXQL.Error) (1553) Cannot drop index 'posts_user_id_fkey': needed in a foreign key constraint

    query: ALTER TABLE `posts` DROP `user_id`
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:332: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:118: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
```
Explicitly having `up/0` and `down/0` methods does work though.
```elixir
defmodule Sample.Repo.Migrations.AddUserIdColumn do
  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :user_id, references(:users)
    end
  end

  def down do
    alter table(:posts) do
      remove :user_id, references(:users)
    end
  end
end
```

### Expected behavior

Successfully run the migration with the `change` version which already works with Postgres. I looked into it further and I found out it's caused by the fact that this `table_reverse` clause discards the type of the field when reversing the operation, so the adapter can't know anymore that it's a `%Reference{}` and needs to be treated differently. 

Is there a specific reason why it's implemented this way that I am missing, or may I submit a pr to include the return type in the tuple? Thank you.

https://github.com/elixir-ecto/ecto_sql/blob/7f0bc4793b62edeedb7a6edbbdce4794106e0932/lib/ecto/migration/runner.ex#L270-L272
https://github.com/elixir-ecto/ecto_sql/blob/1bf8166606665e835cfe5d54420f37777d802eb3/lib/ecto/adapters/myxql/connection.ex#L921-L924

**Comment by greg-rychlewski** [comment]
+1 for a PR.

I think this probably is affecting Postgres as well. If it's not dropping the constraint and you to forward -> backward -> forward it should try to add a constraint that already exits and raise an error.

**Comment by KiKoS0** [comment]
You are right it doesn't affect Postgres because it automatically drops both constraints and indexes.
https://www.postgresql.org/docs/8.0/sql-altertable.html
> DROP COLUMN
> This form drops a column from a table. Indexes and table constraints involving the column will be automatically dropped as well. 

In the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html) they only mention dropping indexes and removing the column from partial ones automatically, which fails when these are tied to constraints.
