### ISSUE TITLE
Link to documentation in README is broken

### ISSUE THREAD

**Issue by jeremyjung** [elixir-ecto/ecto_sql#5]
### Environment

Master branches of ecto and ecto_sql.

### Current behavior

The link to the ecto_sql documentation (https://hexdocs.pm/ecto_sql) is broken.

### Expected behavior

Documentation for ecto_sql should be displayed.  It currently does not because ecto_sql is not a published package on hex.  This also breaks the Ecto.Adapters.SQL link in the [ecto](https://github.com/elixir-ecto/ecto) README.

**Comment by josevalim** [comment]
Yes, this happens because we are preparing for the first. It should be fixed soon this week when the RC will be out.

**Comment by josevalim** [comment]
Docs are up!
