### ISSUE TITLE
ecto.load --quiet should omit debug SQL logs 

### ISSUE THREAD

**Issue by kevinlang** [elixir-ecto/ecto_sql#501]
### Elixir version

1.14.4

### Database and Version

Postgres 14

### Ecto Versions

ecto 3.9.5 ecto_sql 3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

1. Go to project w/ ecto
2. Dump database structure with `ecto.dump`
3. Load database structure with `ecto.load --quiet --skip-if-loaded`
4. Observe a debug log e.g.

```
10:53:37.739 [debug] QUERY OK db=2.1ms decode=0.7ms queue=27.1ms idle=0.0ms
SELECT true FROM information_schema.tables WHERE table_name = $1 AND table_schema = current_schema() LIMIT 1 ["schema_migrations"]
```

I would expect the `--quiet` here to perform similar to how `ecto.migrate` runs where it ensures no logs are emitted.

### Expected behavior

Setting `--quiet` should not emit any debug logs

**Comment by josevalim** [comment]
Agreed. PRs welcome.
