### ISSUE TITLE
Documentation does not mention the :identity primary key type

### ISSUE THREAD

**Issue by Munksgaard** [elixir-ecto/ecto_sql#515]
### Elixir version

1.14.3

### Database and Version

Postgres 15.2

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgresx

### Current behavior

#255 implemented support for the `:identity` primary key type (and column type), but it is not mentioned anywhere in the documentation.

### Expected behavior

It would be nice if the documentation mentioned `:identity`. I had to search far and wide to find out that it was in fact implemented, [as have others](https://elixirforum.com/t/how-to-use-postgres-identity-columns-in-ecto/25166/7).

**Comment by josevalim** [comment]
A PR is welcome!
