### ISSUE TITLE
YugabyteDB 2.18.0.1: Ecto Migrations Fail Due to Unsupported SHARE UPDATE EXCLUSIVE Lock

### ISSUE THREAD

**Issue by fire** [elixir-ecto/ecto_sql#527]
### Elixir version

 ``` Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit] Elixir 1.12.2 (compiled with Erlang/OTP 24) ```

### Database and Version

YugabyteDB 2.18.0.1

### Ecto Versions

ecto_sql 3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.1

### Current behavior

1. Create a new Elixir project with Ecto and Postgrex dependencies.
2. Set up the database configuration to use YugabyteDB 2.18.0.1.
3. Create a migration file.
4. Run `mix ecto.migrate`.

The error should occur during the migration process.

When running migrations, the following error occurs:

> (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: 4281, message: nil, postgres: %{code: :feature_not_supported, file: "gram.y", hint: "Please report the issue on https://github.com/YugaByte/yugabyte-db/issues", line: "17468", message: "SHARE UPDATE EXCLUSIVE not supported yet", pg_code: "0A000", position: "35", routine: "raise_feature_not_supported_signal", severity: "ERROR", unknown: "ERROR"}, query: "LOCK TABLE \"schema_migrations\" IN SHARE UPDATE EXCLUSIVE MODE"}}

This error is caused by the unsupported `SHARE UPDATE EXCLUSIVE` lock in YugabyteDB 2.18.0.1.

### Expected behavior

Ecto should be able to run migrations without encountering errors related to unsupported lock types in YugabyteDB.

**Comment by josevalim** [comment]
YugaByte either needs to support this operation or you need to disable the migration lock on your own migrations.

**Comment by fire** [comment]
It is not well documented to add:

```
migration_lock: :pg_advisory_lock
```

**Comment by josevalim** [comment]
Feel free to provide a PR to update the docs :)
