### ISSUE TITLE
Ecto.Query.API.type(true, :boolean) generates invalid MySQL query

### ISSUE THREAD

**Issue by m1dnight** [elixir-ecto/ecto_sql#537]
### Elixir version

1.15.2

### Database and Version

MySQL 8.0 

### Ecto Versions

ecto 3.10.3, ecto_sql 3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.6.3

### Current behavior

A query that uses `where([c], c.is_active == type(^true, :boolean))` generates an SQL query that contains `WHERE (c0.`is_active` = CAST(? AS boolean))`. 

MySQL does not support casting to type `boolean`: https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast

I have built a minimal working example on the `casting` branch in this repo:  https://github.com/m1dnight/flop_bug/tree/casting

The readme contains the instructions to reproduce it using a docker container for the mysqldb.

### Expected behavior

The cast is either not made, or a more complex if test is used to obtain the same behavior. 
For example here: https://dba.stackexchange.com/questions/12569/how-to-cast-an-integer-to-a-boolean-in-a-mysql-select-clause

**Comment by m1dnight** [comment]
That I can do! Thanks

**Comment by josevalim** [comment]
Btw, You can find tests under test/Ecto/adapters :)

**Comment by m1dnight** [comment]
Fixed by https://github.com/elixir-ecto/ecto_sql/pull/538
