### ISSUE TITLE
Starting a transaction on MSSQL 2012 fails

### ISSUE THREAD

**Issue by bhlieberman** [elixir-ecto/ecto_sql#547]
### Elixir version

1.14.0

### Database and Version

SQL Server 2012

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

tds 2.3.2

### Current behavior

1. Make a new Phoenix app with `mix phx.new`.
2.  Configure a MSSQL 2012 database and corresponding Phoenix config.
3. Create an Ecto schema and try to migrate with `mix ecto.migrate`.

At this point, you may see that the database throws a syntax error. This originates here:
```
def lock_for_migrations(meta, opts, fun) do
    %{opts: adapter_opts, repo: repo} = meta

    if Keyword.fetch(adapter_opts, :pool_size) == {:ok, 1} do
      Ecto.Adapters.SQL.raise_migration_pool_size_error()
    end

    opts = Keyword.merge(opts, timeout: :infinity, telemetry_options: [schema_migration: true])

    {:ok, result} =
      transaction(meta, opts, fn ->
        query =
          "sp_getapplock @Resource = 'ecto_#{inspect(repo)}', @LockMode = 'Exclusive', @LockOwner = 'Transaction', @LockTimeout = -1"

        Ecto.Adapters.SQL.query!(meta, query, [], opts)
        fun.()
      end)

    result
  end
```
The workaround for me was to add an `exec` to the `query`, i.e. `query = "exec sp_getapplock ..."`, but I just used the library as-is to connect to a SQL Server 2017 instance and it works fine. I'm quite green in Elixir so I can't say whether this is the root cause or not. But it seems to be.

### Expected behavior

I can connect to MSSQL 2012 and run transactions.

**Comment by greg-rychlewski** [comment]
Thanks for the report. Could you please copy the error and stack trace you received ?

**Comment by josevalim** [comment]
I am fine with not supporting MSSQL 2012. It is no longer officially supported by Microsoft unless you are paying for extended security policies: https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012.  If someone wants to send a PR that supports both versions and it is not tons of work, then it is fine. :)

Although we should note at least 2017 is required in the Ecto.Adapters.TDS docs.

**Comment by bhlieberman** [comment]
Here's the trace:
```
10:41:47.295 [debug] Line 1 (Error 8180): Statement(s) could not be prepared.
** (Tds.Error) Line 1 (Error 102): Incorrect syntax near 'sp_getapplock'.
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.1) lib/ecto/adapters/tds.ex:292: anonymous fn/4 in Ecto.Adapters.Tds.lock_for_migrations/3
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
    (ecto_sql 3.10.1) lib/ecto/adapters/tds.ex:290: Ecto.Adapters.Tds.lock_for_migrations/3
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:574: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
```

I totally understand not wanting to support 2012...I don't want to work with MSSQL 2012 😅 alas...

**Comment by greg-rychlewski** [comment]
I wonder if the exec variant works for all versions. But I never used sql server even once so not sure what kind of land mines are hidden

**Comment by josevalim** [comment]
Well, let's try: https://github.com/elixir-ecto/ecto_sql/pull/548
