### ISSUE TITLE
Unable to override `:migration_lock` parameter when used in connection configuration

### ISSUE THREAD

**Issue by mjaric** [elixir-ecto/ecto_sql#56]
I'm working on MSSQL adapter and having trouble to understand how to disable default "FOR UPDATE" :migration_lock value without implementing my custom `Ecto.Adapter.SQL.lock_for_migrations/4` function in adapter. 

The meta I'm getting looks like this

```elixir
%{
  cache: #Reference<0.224688069.2605580292.202322>,
  opts: [
    timeout: 15000,
    pool_timeout: 5000,
    pool_size: 5,
    pool: DBConnection.Ownership
  ],
  pid: #PID<0.290.0>,
  sql: Ecto.Adapters.MsSql.Connection,
  telemetry: {:debug, [], [:ecto, :integration, :test_repo, :query]}
}
```

Where TestRepo is configured like this

```elixir
Application.put_env(
  :ecto_sql,
  TestRepo,
  migration_lock: nil, 
  hostname: System.get_env("SQL_HOSTNAME"),
  username: System.get_env("SQL_USERNAME"),
  password: System.get_env("SQL_PASSWORD"),
  database: "ecto_test",
  pool: Ecto.Adapters.SQL.Sandbox,
  pool_size: 5,
  set_allow_snapshot_isolation: :on,
  filter_null_on_unique_indexes: true
)
```

**Comment by mjaric** [comment]
Just saw, how init function is written. It takes only pool related options and puts it into meta. Does anyone mind if I add `migration_lock` as additional flag in Keyword.take (`opts = Keyword.take(config, [:timeout, :pool, :pool_size, :pool_timeout, :migration_lock])`) so I can easily add `nil` value in child_spec of my adapter, something like below:
 
```elixir
  @doc false
  def init(connection, adapter, config) do
    unless Code.ensure_loaded?(connection) do
      raise """
      could not find #{inspect connection}.

      Please verify you have added #{inspect adapter} as a dependency:

          {#{inspect adapter}, ">= 0.0.0"}

      And remember to recompile Ecto afterwards by cleaning the current build:

          mix deps.clean --build ecto
      """
    end

    log = Keyword.get(config, :log, :debug)
    loggers = Keyword.get(config, :loggers, [])
    telemetry_prefix = Keyword.fetch!(config, :telemetry_prefix)
    telemetry = {log, loggers, telemetry_prefix ++ [:query]}

    config = adapter_config(config)
    opts = Keyword.take(config, [:timeout, :pool, :pool_size, :pool_timeout, :migration_lock])
    meta = %{telemetry: telemetry, sql: connection, opts: opts}
    {:ok, connection.child_spec(config), meta}
  end
```

**Comment by josevalim** [comment]
Thanks @mjaric! Can you please try out master with commit 65557d00bc79b81ae819c9ed5934905ab77d8a95? If it works I will release a new version that you can depend on.

My commit allows you to set a default for the whole driver, without messing with the user default.

**Comment by mjaric** [comment]
I will sync my fork and give it a try, from what I can see in commit, that is what I need. Thanks!

**Comment by josevalim** [comment]
@mjaric should I do a new release now or would you rather wait a bit in case you find other incompatibilities? :)

**Comment by mjaric** [comment]
no need to release it now
