### ISSUE TITLE
(DBConnection.ConnectionError) in tests

### ISSUE THREAD

**Issue by samphilipd** [elixir-ecto/ecto_sql#58]
Since upgrading to Ecto 3.0.3 we randomly get this error in tests:

```
(DBConnection.ConnectionError) connection not available and request was dropped from queue after 254ms
```

It seems to only happen sometimes, but once it happens all subsequent tests are affected.

**Comment by josevalim** [comment]
@samphilipd that's the new pool_timeout. You can read more about this here: https://github.com/elixir-ecto/ecto/issues/2833

Please let us know if tweaking those values improve things.

**Comment by josevalim** [comment]
Closing this, let us know if we can provide more info.
