### ISSUE TITLE
Raw SQL Regex Issue with Ecto.Migration#execute/1

### ISSUE THREAD

**Issue by lavli-food-admin** [elixir-ecto/ecto_sql#583]
### Elixir version

1.16.0

### Database and Version

PostgreSQL 16.1

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.4

### Step 1: Migration
For a couple of reasons I use some raw SQL in my migration files. I created a `contacts` table with the following statement (only relevant parts):

```elixir
def up do
  execute """
    create table contacts (
      -- Keys
      ...
  
      -- Data
      ...
      phone_number text,
  
      -- Timestamps
      ...
  
      -- Check constraint to ensure phone number matches format `+<country_code> <area_code> <number>` following DIN 5008
      constraint din_5008_phone_number check (phone_number ~ '^\+[1-9]\d{0,2} [1-9]\d* \d+(-\d+)?$')
  );
  """
end
```

### Step 2: Seeding the Database
When trying to seed the database with `mix run priv/repo/seeds.exs` I got this error:

```bash
** (Postgrex.Error) ERROR 2201B (invalid_regular_expression) invalid regular expression: quantifier operand invalid
```

for a fake phone number like this: `+76 581 91201-32`. It should a) pass the check and b) the regex check constraint was taken from a previous project so I was pretty sure it is correct.

### Step 3: Debugging
I dropped the constraint and created a new one in the DB with exactly the same regex:

```sql
alter table contacts
drop constraint din_5008_phone_number;

alter table contacts
add constraint din_5008_phone_number check (phone_number ~ '^\+[1-9]\d{0,2} [1-9]\d* \d+(-\d+)?$');
```

Now the seeding works fine and the random phone numbers pass the check.

I compared the two constraint definitions (Ecto migration vs. adding in DB) with:

```sql
select
    conname as constraint_name,
    contype as constraint_type,
    conrelid::regclass as table_name,
    pg_get_constraintdef(c.oid) as constraint_definition
from
    pg_constraint c
join
    pg_class t on c.conrelid = t.oid
join
    pg_namespace n on t.relnamespace = n.oid
where
    contype = 'c';
```

If you create the constraint in the DB, the resulting `constraint_definition` looks like this:
`CHECK ((phone_number ~ '^\+[1-9]\d{0,2} [1-9]\d* \d+(-\d+)?$'::text))`

With Ecto.Migration#execute/1 it looks like this:
`CHECK ((phone_number ~ '^+[1-9] {0,2} [1-9]* +(-+)?$'::text))`

### Step 4: Solution
After a lot of try and error the simple solution is to double escape the regex within the `execute/1` like this:

```sql
constraint din_5008_phone_number check (phone_number ~ '^\\+[1-9]\\d{0,2} [1-9]\\d* \\d+(-\\d+)?$')
```

### Expected behavior

Maybe this a feature and not a bug 🤗, but it took me quite some time to get it right and I would expect the raw SQL execution in a migration file to create the same result as dropping it directly into the database.

If it's some known and expected behavior, maybe you could just extend the documentation and give a hint how to deal with Postgres regex escapes. Many thanks!

**Comment by josevalim** [comment]
Yes, you need to either double escape the regex, because \+ will escape the Elixir character, or use `execute ~S"""`. ~S is a sigil in Elixir that disables all character escaping and interpolation, therefore you don't need to double escape. :)
