### ISSUE TITLE
Unable to set sqlite PRAGMA in migrations

### ISSUE THREAD

**Issue by spiffytech** [elixir-ecto/ecto_sql#589]
### Elixir version

1.15.7

### Database and Version

SQLite

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

0.15.0

### Current behavior

_(Apologies if this should be filed in the ecto_sqlite3 repo. I'm unsure if it's an issue with the migrator or the adapter.)_

If I try to set a PRAGMA inside a migration (either with `query!` or with `execute`), it looks like it doesn't 'stick'. Subsequent queries behave as if the PRAGMA got reset, or maybe never got set in the first place.

This is important, given SQLite`s [requirement to jump through hoops](https://sqlite.org/lang_altertable.html) for commonplace table modifications will eat your data if foreign key enforcement isn't disabled.

Below, I've written a sample migration that sets up some test data, then another one that follows SQLite's [procedure](https://sqlite.org/lang_altertable.html) for table changes. (The before and after schemas are identical, for demonstration purposes).

These migrations result in the `bar` table being emptied out, because foreign keys were incorrectly enforced during `drop table`. If I disable foreign keys in `config.exs`, the data survives the migration.

config.exs
```exs
config :ecto_test, EctoTest.Repo, database: "db.sqlite", pool_size: 1, foreign_keys: :on
config :ecto_test, ecto_repos: [EctoTest.Repo]
```

Migration 1. Creates a table and inserts some foreign-keyed rows:
```exs
defmodule EctoTest.Repo.Migrations.CreateFoo do
  use Ecto.Migration

  def change do
    create table(:foo) do
      timestamps(type: :utc_datetime)
    end

    create table(:bar) do
      add :foo_id, references(:foo, on_delete: :delete_all), null: false

      timestamps(type: :utc_datetime)
    end

    execute "insert into foo (inserted_at, updated_at) values (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);"

    execute "insert into bar (foo_id, inserted_at, updated_at) values (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);"
  end
end
```

Migration 2, a minimal version of SQLite's [procedure](https://sqlite.org/lang_altertable.html) for many table modifications:
```exs
defmodule EctoTest.Repo.Migrations.TestQueryOrder do
  use Ecto.Migration

  def up do
    execute "pragma foreign_keys = off"

    execute """
      CREATE TABLE IF NOT EXISTS "foo2" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
    """

    execute "insert into foo2 select * from foo;"
    execute "drop table foo"
    execute "alter table foo2 rename to foo"
    execute "pragma foreign_keys = on"
  end

  def down do
  end
end
```

### Expected behavior

I expect the data in the `bar` table to still exist after the migration, since the migration disables foreign keys before dropping the `foo` table that `bar` references.

**Comment by greg-rychlewski** [comment]
Hi,

If you put this as a module attribute in your migration file does it work?

>@disable_ddl_transaction true

I'm not an SQLite expert but reading [the docs for that pragma](https://www.sqlite.org/pragma.html#pragma_foreign_keys) says this:

> This pragma is a no-op within a transaction; foreign key constraint enforcement may only be enabled or disabled when there is no pending [BEGIN](https://www.sqlite.org/lang_transaction.html) or [SAVEPOINT](https://www.sqlite.org/lang_savepoint.html).

With your version of ecto sqlite I believe migrations are run inside a transaction by default.

**Comment by spiffytech** [comment]
Ah, good catch! I've now set `@disable_ddl_transaction true`.

With that change I'm seeing a new issue: the migration errors out part-way through. It doesn't drop the table immediately (the table still exists by the time we execute `alter table rename`), but after the migration errors out, the table _has_ been dropped.

If I wrap the migration SQL in `BEGIN`/`END` (with the `pragma` outside the transaction), the migration crashes with "database busy" while running the `drop table` statement. Given that `mix ecto.migrate` is the only thing using the database, I don't understand why the DB would be busy.

(I've double-checked the SQL statements themselves by running them with the `sqlite3` CLI and a .sql file. I also modified the schema of the new table to make it easy to confirm the migration succeeds)

Is ecto doing something that would keep the database busy?

Output of table not dropping:
```
17:31:46.088 [info] == Running 20240118185606 EctoTest.Repo.Migrations.TestQueryOrder.up/0 forward

17:31:46.100 [info] execute "pragma foreign_keys = off"

17:31:46.101 [info] execute "  CREATE TABLE IF NOT EXISTS \"foo2\" (\"id\" INTEGER PRIMARY KEY AUTOINCREMENT, \"inserted_at\" TEXT NOT NULL, \"updated_at\" TEXT NOT NULL, new_col text)\n"

17:31:46.103 [info] execute "insert into foo2 select *, null from foo"

17:31:46.104 [info] execute "drop table foo"

17:31:46.105 [info] execute "alter table foo2 rename to foo"
** (Exqlite.Error) there is already another table or index with this name: foo
alter table foo2 rename to foo
```

Output of `database busy` (`pragma fk off` -> `begin` -> logic -> `commit` -> `pragma fk on`):
```
17:37:00.379 [info] == Running 20240118185606 EctoTest.Repo.Migrations.TestQueryOrder.up/0 forward

17:37:00.390 [info] execute "pragma foreign_keys = off"

17:37:00.391 [info] execute "begin"

17:37:00.391 [info] execute "  CREATE TABLE IF NOT EXISTS \"foo2\" (\"id\" INTEGER PRIMARY KEY AUTOINCREMENT, \"inserted_at\" TEXT NOT NULL, \"updated_at\" TEXT NOT NULL, new_col text)\n"

17:37:00.393 [info] execute "insert into foo2 select *, null from foo"

17:37:00.394 [info] execute "drop table foo"
** (Exqlite.Error) Database busy
drop table foo
```

**Comment by greg-rychlewski** [comment]
I tried running your scenario 1 and wasn't able to reproduce it locally. 

Could you maybe give a minimal reproducible example that fails? Either a script like this: https://github.com/wojtekmach/mix_install_examples/blob/main/ecto_sql.exs. Or a repo with just the bare minimum needed to generate the error.

Nothing is really jumping out to me so would need to play around with an example that is failing. Thanks.

**Comment by greg-rychlewski** [comment]
@josevalim On a somewhat related note, what do you think about adding before_begin/after_commit callbacks for scenarios these kind of scenarios where a pragma needs to be switched off before the migration starts and switched back on after it?

https://sqlite.org/lang_altertable.html#making_other_kinds_of_table_schema_changes

**Comment by josevalim** [comment]
@greg-rychlewski given folks can already achieve this with an isolated migration with ddl transaction set to false, I don't see a strong need for adding more callbacks.

**Comment by spiffytech** [comment]
> Could you maybe give a minimal reproducible example that fails?

After further debugging, I only see the issue if I run the two migrations as separate `mix ecto.migrate` commands. If I start from an empty database and run both, I don't get the issue.

I couldn't reproduce using a self-contained `.exs` file, so I made a repo that reproduces: [spiffytech/ecto_589](spiffytech/ecto_589). It's just `mix ecto.gen.repo` manually reconfigured for sqlite.

```sh
rm db.sqlite
mix ecto.migrate --to-exclusive 20240118185606
mix ecto.migrate
```

**Comment by greg-rychlewski** [comment]
Thanks very much. The link is sending me to a 404, maybe there are permission issues?

**Comment by spiffytech** [comment]
Sorry, no permissions issues, I just fumbled the shorthand syntax for linking to the repo. https://github.com/spiffytech/ecto_589

**Comment by greg-rychlewski** [comment]
Does this reproduction only fail for scenario 2 or also the original scenario?

**Comment by spiffytech** [comment]
It's set up for scenariot 2 (manual `BEGIN`/`COMMIT`, `database busy`), but if I remove those statements, I also get the failure from scenario 1 (`there is already another table with this name`).

**Comment by spiffytech** [comment]
The reproduction uses `pool_size: 1`, but I also see that with pool > 1 it looks like each `execute` runs on in a separate database connection. Could that be related, or should I file a separate issue for that?

**Comment by greg-rychlewski** [comment]
>Could that be related, or should I file a separate issue for that?

That is normal behaviour for Ecto so should not be filed an issue under this repo. If SQLite requires a special pool configuration then it would need to be abled by their adapter.

**Comment by spiffytech** [comment]
Alright. Not an SQLite-specific thing, just wondering the right way to run multiple manual SQL statements in a migration if the connection is stateful (such as the `pragma` or `BEGIN` discussed here).

Is there a different function I should call, or should I just set `pool_size: 1` for a migrations-only `MIX_ENV`?

**Comment by greg-rychlewski** [comment]
It works the following way:

1. If you are in a transaction then each statement will be run on the same connection
2. If you are not in a transaction then each statement will get a connection from the connection pool. It might be the same as the last one or might not, there is no guarantee. To guarantee the same one then you need a single connection in the pool

**Comment by greg-rychlewski** [comment]
Taking a closer look at your repo, I think the issue might be with how you are setting your pool size. I don't believe the application configuration is read for the mix tasks. It reads it from the flag `--pool-size` and if none exists defaults to two. So this might be your issue. Can you try running with `--pool-size 1`

**Comment by spiffytech** [comment]
Yep, the migration completes now. Thanks very much for the help!

I'd like to PR a docs change to `Ecto.Adapters.SQLite3` covering this stuff, as well as open a discussion in the Google Group about how we can make it easier for Ecto users to get this commonplace SQLite procedure right.
