### ISSUE TITLE
References inside a prefixed table cannot reference an unprefixed table

### ISSUE THREAD

**Issue by jdewar** [elixir-ecto/ecto_sql#590]
### Elixir version

Elixir 1.15.7

### Database and Version

PostgreSQL 14.1

### Ecto Versions

Ecto 3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.4

### Current behavior

# Ecto

```elixir
Mix.install([
  {:ecto, "~> 3.10"},
  {:ecto_sql, "~> 3.10"},
  {:postgrex, "~> 0.17.3"},
  {:kino, "~> 0.11.0"}
])
```

## Repo

```elixir
defmodule Repo do
  use Ecto.Repo, otp_app: :my_app, adapter: Ecto.Adapters.Postgres
end
```

```elixir
Kino.start_child({Repo, url: "postgres://postgres:postgres@localhost/postgres"})
```

## Ecto migration

```elixir
defmodule Migration do
  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA schema1")
    execute("CREATE SCHEMA schema2")

    create table("prefixed_group", prefix: "schema2") do
    end

    create table("group") do
    end

    create table("user", prefix: "schema1") do
      add(:prefixed_group_id, references("prefixed_group", prefix: "schema2"))
      # add(:group_id, references("group", prefix: nil))
    end
  end

  def down do
    drop(table("user", prefix: "schema1"))
    drop(table("group"))
    drop(table("prefixed_group", prefix: "schema2"))
    execute("DROP SCHEMA schema1")
    execute("DROP SCHEMA schema2")
  end
end
```

```elixir
Ecto.Migrator.up(Repo, 1, Migration)
|> dbg()

Ecto.Migrator.down(Repo, 1, Migration)
```

The above Livebook (0.12.1) runs perfectly fine, until you uncomment the attempt to reference the "group" table that has no prefix.  I could find no way to point a reference at an unprefixed table from one with a prefix.

### Expected behavior

I expect some way to overwrite the prefix in a reference, or in a table, such that it can _unset_ the default prefix (implied by table or application config) back to "no prefix at all"

**Comment by josevalim** [comment]
Nah, `prefix()` may return `nil` too. In order to fix this, we would need to change the `.prefix` field in index, table, reference and other structs to be `{:ok, prefix} | :error` or something of sorts.

**Comment by jdewar** [comment]
nothing super elegant, but ..
* one backwards compatible option would be to have a `no_prefix: true` (remove_prefix, clear_prefix, etc) option that raised if you tried to set it and `:prefix` in the same opts.  
* another would be to allow prefix: to take something more complex than an atom/string, like {:clear, :prefix}
* similar to previous idea, maybe it's okay to special case the `false` atom as clearing the prefix (you could still use "false" string if that was a desired prefix)

**Comment by SteffenDE** [comment]
The default schema on postgres databases is `"public"`. So you should be able to write `add(:group_id, references("group", prefix: "public"))` in this case.

**Comment by greg-rychlewski** [comment]
> The default schema on postgres databases is `"public"`. So you should be able to write `add(:group_id, references("group", prefix: "public"))` in this case.

This is good advice. Maybe we should just document something like this as the solution. As far as I know you should always be able to write unqualified table names as qualified table names. In Postgres every table is inside of a schema. In MySQL every table is inside of a database. 

It sounds better to me than introducing a new conflicting option or a backwards incompatible change.

**Comment by josevalim** [comment]
Yeah, it is just the behaviour is inconsistent with the other uses of prefixes, but there isn't much we can do I think.

**Comment by greg-rychlewski** [comment]
Is there any precedent to create a new function that is basically the old one but with the correct fix? And then deprecate the old one.

**Comment by greg-rychlewski** [comment]
Oh I think I see what you mean. The issue is here right:

> quote_table(ref.prefix || table.prefix, ref.table)

So if `ref.prefix` is `:error` then we use `table.prefix` but if it is `{:ok, nil}` then we use the unprefixed `quote_table` function?

That looks good to me. I wasn't sure what the policy was about changing the behaviour of existing migrations or other adapters like SQLite, Clickhouse, etc. But if it's normal procedure then +1 from me.

**Comment by josevalim** [comment]
Typically we add new callbacks on major versions, which often breaks the adapter anyway, but it is very unoften that we change behaviour. That's why adding a new field to the struct, as mentioned by @jdewar, may be the best option? We can call it `options`, keep it as a keyword list, and shove `:prefix` there? So the code above becomes:

    quote_table(Keyword.get(ref.options, :prefix, table.prefix), ref.table)

And we deprecate .prefix?

**Comment by greg-rychlewski** [comment]
That sounds like the best option to me. And the docs are pretty clear about he behaviour:

> :prefix - The prefix for the reference. Defaults to the prefix defined by the block's [table/2](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#table/2) struct (the "products" table in the example above), or nil.

So if someone was using `prefix: nil` to be the table's prefix then they were using it in error anyway.

**Comment by jdewar** [comment]
We were able to side step the problem by creating a new prefix, and using "public" would've been our solve (wouldn't've created this issue even, had I known).  Thanks much for this change!  It's nice to set prefix to 'nil' in a way that matches my mental model.

> > :prefix - The prefix for the reference. Defaults to the prefix defined by the block's [table/2](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#table/2) struct (the "products" table in the example above), or nil.
> 
> So if someone was using `prefix: nil` to be the table's prefix then they were using it in error anyway.

@greg-rychlewski I did want to comment on this part; one might have the Application config define a `:migration_default_prefix`, and then a table's `prefix: nil` could make sense, eg:
```
config :myapp, Repo, migration_default_prefix: "my_prefix"

...

create table("user", prefix: nil) do
  add(:prefixed_group_id, references("prefixed_group", prefix: "my_prefix"))
end
```

**Comment by greg-rychlewski** [comment]
Yes sorry. I meant it's ok for us to "break" users who are relying on our mistake to have the migrations behave in an undocumented way.
