### ISSUE TITLE
Calling to_sql on an intersect query right after a union query generates identitical SQL

### ISSUE THREAD

**Issue by darinwilson** [elixir-ecto/ecto_sql#60]
### Environment

* Elixir version (elixir -v): 1.7.2, Erlang/OTP 21
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.3
* Ecto version (mix deps): 3.0.4
* Database adapter and version (mix deps): postgrex 0.14.0
* Operating system: MacOS High Sierra

### Current behavior

If you create a `union` query and call `Repo.to_sql,` then change the query to use `intersect` and call  `Repo.to_sql` again, you get the exact same generated SQL (the `UNION` isn't changing to `INTERSECT`)

I created a failing test case in my fork of `ecto_sql` which demonstrates the issue (branch is `issue/union-then-intersect`):

https://github.com/darinwilson/ecto_sql/blob/b70c96104bc98dc655ac91e288f40846c9ab6ee1/integration_test/sql/sql.exs#L55,L65

I ran this with `ECTO_ADAPTER=pg` - I haven't tried it with MySQL.

### Expected behavior

`UNION` should change to `INTERSECT` in the second `to_sql` call.

**Comment by josevalim** [comment]
Good catch, fixed here: https://github.com/elixir-ecto/ecto/commit/5e2303ce629b6fd346b004452e052be6261c7c43

**Comment by darinwilson** [comment]
Thanks for the quick fix! ❤️
