### ISSUE TITLE
`in` operator produces invalid SQL when used with a MySQL JSON array

### ISSUE THREAD

**Issue by Wigny** [elixir-ecto/ecto_sql#608]
### Elixir version

1.16.2

### Database and Version

mysql:8.4

### Ecto Versions

3.11

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.6.4

### Current behavior

The `in` operator states that it can also be used in queries when the right side element is a database column, when it is of type array.

```elixir
from u in User, where: "admin" in u.roles
```

However, since MySQL does not have a proper array data type, using the operator generates an invalid SQL:

```
** (MyXQL.Error) (1064) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'u0.`roles`))' at line 1

    query: SELECT u0.`id`, u0.`roles` FROM `users` AS u0 WHERE ('admin' = ANY(u0.`roles`))
```
> [Gist](https://gist.github.com/Wigny/30c368ecbb9176a997672e951ac7b2dd#file-mysql_array_in-exs)

### Expected behavior

Given that Ecto already handles casting MySQL JSON arrays (by using the `json` type in migrations and the `array` type in schemas), providing a similar experience of having a native array data type, it would be great if the `in` operator worked on JSON arrays too.

Right now the way to have the functionality of the `in` operator with MySQL is by using the [`JSON_CONTAINS` function](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-contains) in a `fragment`, and I wonder if that should be directly used by the MyXQL adapter when `in` is called. That could also be an addition to the API, given we already have `json_extract_path/2`.

**Comment by greg-rychlewski** [comment]
Hi, thank you for bringing up the topic.

One thing I noticed when playing around with this is that `json_contains` is a lot more particular than the usual array operators

```elixir
mysql> select json_contains('[1, 2, 3]', 1);
ERROR 3146 (22032): Invalid data type for JSON data in argument 2 to function json_contains; a JSON string or JSON type is required.

mysql> select json_contains('[1, 2, 3]', '1');
+---------------------------------+
| json_contains('[1, 2, 3]', '1') |
+---------------------------------+
|                               1 |
+---------------------------------+
1 row in set (0.00 sec)
```

So for example you couldn't do 
```elixir
from s in "schema, where: 1 in s.integer_array_field`
```

**Comment by josevalim** [comment]
Generally speaking, we don't try to be very smart in Ecto. The query you write is close to the SQL you would write. That makes things predictable and consistent. If MySQL wants you to use `json_contains`, then you have to use `json_contains`. :) You can always convince MySQL folks to support those in `in` as well. Then everyone gets it for free. :)
