### ISSUE TITLE
[Proposal] Allow Addapter developers to override how Ecto.UUID dumps and loads uuid binary representation

### ISSUE THREAD

**Issue by mjaric** [elixir-ecto/ecto_sql#62]
### Background

Most database engines that was first developed for *nix operating system stores UUID type binary in order as human readable representation is rendered. As for many things, Microsoft did not respect this standard, so fist part of 4 bytes, bytes in reversed order and next 2 bytes also, after that, other bytes are not changed. 

standard order: 
```elixir
<<b1, b2, b3, b4, ?-, b5, b6, ?-, b7, b8, ?-, b9, b10, ?-, b11, b12, b13, b14, b15, b16>>
```
tds order: 
```elixir
<<b4, b3, b2, b1, ?-, b6, b5, ?-, b8, b7, ?-, b9, b10, ?-, b11, b12, b13, b14, b15, b16>>
```
Earlier, before ecto 3.x I used custom type Tds.UUID instead of builtin and had to rewrite all support integration tests. Since most of integration test are using UUID this would mean that if I add MsSql adapter to ecto_sql repository, I have to write my own test cases, schemas and migrations in order to cover all cases properly. 

### Solution
So far I don't have idea how to nicely override Ecto.UUID since this is out of adapter reach, any suggestions that do not involve rewriting all that integration cases are welcome!!!

**Comment by josevalim** [comment]
Definitely.

My proposal would be for us to define a new function here, called `uuid_type`: https://github.com/elixir-ecto/ecto_sql/blob/master/integration_test/pg/test_helper.exs#L39

Now instead of using `Ecto.UUID` we would do `PoolRepo.uuid_type`. There may even be some places where we assert on the value of the UUID in particular. We likely need to rewrite those to use `PoolRepo.uuid_type.dump` so we verify they are valid.

What do you think?

**Comment by mjaric** [comment]
And this should be only done for unit testing. In regular project where ecto_sql is used, developers should continue using current modules.

I will refactor integrations tests and test_helper.exs in all adapters, so it will be part of my PR with mssql adapter.

BTW, when do we plan to release 3.1? Asking since I fave 2 more features to cover, cursors and schema dump/load. Second one will take some time since there is no official command line tool that I can use, so I have to write what ever is needed in TDS.

**Comment by josevalim** [comment]
> And this should be only done for unit testing. In regular project where ecto_sql is used, developers should continue using current modules.

Yes, it is for testing only.

> I will refactor integrations tests and test_helper.exs in all adapters, so it will be part of my PR with mssql adapter.

It is probably best to send separate PRs for those changes. It is likely that the PR is going to be big, so if we can reduce its size by sending earlier PRs, it will be better. :)

> BTW, when do we plan to release 3.1? Asking since I fave 2 more features to cover, cursors and schema dump/load.

We have no plans, so take your time.

>  Second one will take some time since there is no official command line tool that I can use, so I have to write what ever is needed in TDS.

You can likely do dump/load via the TCP client. That's how we do create/drop for some of them too.

**Comment by mjaric** [comment]
Btw, I discovered 2 more things that are different between mysql, postgresql comapring to mssql and I will try to solve that in another ecto repo PR later. `distinct` and `like` are not supported in mssql for columns of type `text` and `ntext` so I will try to isolate them in tagged test cases, e.g. `:filter_text_using_like` and `:distinct_text_column` so I can add exclusion in test_helper.exs for mssql adapter. 

deal?

**Comment by josevalim** [comment]
@mjaric yes, we can definitely add more filters. :D

However, maybe it is better to use like and distinct in other columns? This way the tests can still run on MSSQL, which is preferable.

**Comment by mjaric** [comment]
I will check, since I do want to avoid adding another function in TestRepo for varchar type. We are using custom type for varchar in schema ever since we discovered performance issue on large tables when varchar columns are filtered in query. MSSQL adapter is unable to distinguish if string parameter should be nvarchar or varchar so it always declared nvarchar parameter and that caused unnecessary IO reads in database so queries become much slower. But if that column is nvarchar then it will work out of the box. I'll check schemas and see what can be done without changing that code too much.

Also, correct me if I'm not mistaken, if we test distinct only using one db type, we could say it will work for other types too? There is no need to test backend, right?

**Comment by josevalim** [comment]
> Also, correct me if I'm not mistaken, if we test distinct only using one db type, we could say it will work for other types too? There is no need to test backend, right?

Right. Our test is mostly likely checking that we emit the proper SQL, unless the test explicitly says otherwise. If the operation does not work for a certain type in the database, it is not really Ecto's concern. So as long as we use any column, we should be good.

Can you link to both tests? Then I can confirm that's the case. :)

**Comment by mjaric** [comment]
Yes, here is few tests output samples

### Binary column, nvarchar parameter

```elixir
226) test many_to_many assoc (Ecto.Integration.AssocTest)
     deps/ecto/integration_test/cases/assoc.exs:118
     ** (Tds.Error) Line 1 (Error 257): Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
     code: p1 = TestRepo.insert!(%Post{title: "1", text: "hi"})
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:604: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:264: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
       (ecto) lib/ecto/repo/schema.ex:166: Ecto.Repo.Schema.insert!/3
       deps/ecto/integration_test/cases/assoc.exs:119: (test)
```

Reason is that field `text` in `Post` is `:binary`or `varbinary` in database in [scehma](https://github.com/elixir-ecto/ecto/blob/master/integration_test/support/schemas.exs#L31) and [migration](https://github.com/elixir-ecto/ecto_sql/blob/master/integration_test/support/migration.exs#L14) but parameter is string and adapter is unable to know here that it should cast/mark parameter value into varbinary type. `Ecto.Query.type` can help when used as e.g. `type("1", :binary)` or in queries `type("1", p.text)` where ecto will resolve column type during compile time but I'm not sure if this can be used during insert.

### Distinct over text columns

```elixir
216) test has_many through-through assoc trailing (Ecto.Integration.AssocTest)
     deps/ecto/integration_test/cases/assoc.exs:103
     ** (Tds.Error) Line 1 (Error 421): The text data type cannot be selected as DISTINCT because it is not comparable.
     code: assert [^u1] = TestRepo.all(query)
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:604: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql) lib/ecto/adapters/sql.ex:537: Ecto.Adapters.SQL.execute/5
       (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
       deps/ecto/integration_test/cases/assoc.exs:111: (test)
```

The query is 
```sql
declare @p1 int
set @p1=NULL
exec sp_prepare @handle=@p1 output,@params=N'@1 bigint',@stmt=N'SELECT DISTINCT u0.[id], u0.[name], u0.[custom_id], u0.[inserted_at], u0.[updated_at] FROM [users] AS u0 INNER JOIN [posts] AS p1 ON p1.[id] = @1 INNER JOIN [comments] AS c2 ON c2.[post_id] = p1.[id] WHERE (u0.[id] = c2.[author_id])'
select @p1
```

Where in schema `users` column `name` is of type `string` (if send as raw parameter, tds will think it is nvrachar) where in migration it is `text` column type ([migration](https://github.com/elixir-ecto/ecto_sql/blob/master/integration_test/support/migration.exs#L6) and [schema](url))

...

And there is more cases, but I think github can't accept such long comment 😄... and they are similar anyway.

**Comment by mjaric** [comment]
Here is a changed copy of integration files I used while working on adapter for ecto 2.x
* [migration](https://github.com/livehelpnow/tds_ecto/blob/master/test/Integration/support/migration.exs)
* [schemas](https://github.com/livehelpnow/tds_ecto/blob/master/test/Integration/support/schemas.exs)

**Comment by josevalim** [comment]
@mjaric I am pretty sure we can change the migration.exs file itself and make it only use text in a less used schema. I will push something soon.

**Comment by josevalim** [comment]
@mjaric Pushed! It should be better now but some improvements are likely still necessary.

**Comment by mjaric** [comment]
👍
Let me check it and see if some errors are gone

**Comment by mjaric** [comment]
COOL! Distinct issue is gone. I see some more related to varchar columns and iserts. Below, sql complains that adapter is trying to insert nvarchar in varchar column `title`. But let me first see if I can do something in insert callback in adapter, e.g. if I get column type from ecto, I think if we use changeset (cast) for insert it works without adding type hints.

```
15) test many_to_many assoc on delete deletes all (Ecto.Integration.AssocTest)
     /Users/mjaric/prj/github/ecto/integration_test/cases/assoc.exs:673
     ** (Tds.Error) Line 1 (Error 257): Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
     code: p1 = TestRepo.insert!(%Post{title: "1", text: "hi"})
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:604: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:651: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:264: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
       (ecto) lib/ecto/repo/schema.ex:166: Ecto.Repo.Schema.insert!/3
       /Users/mjaric/prj/github/ecto/integration_test/cases/assoc.exs:674: (test)
```

**Comment by josevalim** [comment]
I believe this particular issue is fixed :D if there is anything else, please let us know!

**Comment by mjaric** [comment]
I will open individual issue per topic later. There are differences but among them there is one that it is related actually to elixir itself. `NaiveDateTime` nor `DateTime` is not precise enough for MSSQL `DateTime2`, `Time` and `DateTimeOffset`. In SQL server all are 7 digits precise, and I'm afraid that I need to introduce custom types to avoid precision loss.

**Comment by josevalim** [comment]
@mjaric can't we discard the 7th digit when loading and pad it with a 0 when dumping? I think the custom types would be worse for the developer in general as it would "fork" the experience. If someone wants to keep the 7th digit, then we can provide a way for them to do so.

**Comment by mjaric** [comment]
... or not, if ecto uses :datetime2 then when migration is run it should create column with datetime2(6)... same for parameters! Is this ok?

**Comment by josevalim** [comment]
Yes, that's what you should do. `:datetime` in migrations should be `datetime2(6)`. Folks can pass the `scale: ...` option (or whatever we call it) if they want to.

**Comment by mjaric** [comment]
ok, I will create loaders and dumpers so they will work as you mentioned. I will keep in `Tds` lib erlang datetime tuple for now as it was working so far.

Thanks!

**Comment by josevalim** [comment]
@mjaric it may be better if the adapter also returns Elixir data types because it means raw SQL queries also return Elixir types. You can put them behind an option if you want to.

**Comment by mjaric** [comment]
Adapter will return elixir types. 

> I will keep in Tds lib erlang datetime tuple for now as it was working so far.

[Tds](https://github.com/livehelpnow/tds) I mentioned above is just DBConnection implementation. So far it worked with erl datetime tuple and it preserves precision.
