### ISSUE TITLE
Add Repo name to Telemetry metadata

### ISSUE THREAD

**Issue by binaryseed** [elixir-ecto/ecto_sql#69]
For monitoring solutions, it'd be nice to have the `Repo` module name in the Telemetry metadata map.

This would enable us to report metrics with the proper namespace in the condition that there are multiple `Repo`s in an application. Without this we couldn't tell the difference between tables with the same name in different databases...

Thanks!

**Comment by josevalim** [comment]
In master!

**Comment by binaryseed** [comment]
Thanks!!
