### ISSUE TITLE
Wording in docs is slightly confusing...

### ISSUE THREAD

**Issue by ryanwinchester** [elixir-ecto/ecto_sql#70]
I feel like the docs here are a bit confusing.

![](http://drops.ryanwinchester.ca/9c0c95eb72c7/Screen%252520Shot%2525202019-01-05%252520at%2525206.08.47%252520PM.png)

I think this could be read as `execute/2` is one of those commands that are non-reversible in `change/0` (even though it provides an `up/0` and `down/0`).

This confused me quite a bit, actually, and I wasted a bunch of time trying to find some examples of `execute/2`'s usage in migrations.

Thoughts? Should we make it more clear?

Or am I just terrible at reading comprehension? 🤣

**Comment by josevalim** [comment]
Maybe we should add something like: "This makes `execute/2` reversible as long as you pass it two arguments."? WDYT? PR please?
