### ISSUE TITLE
Proposal: static telemetry event naming

### ISSUE THREAD

**Issue by binaryseed** [elixir-ecto/ecto_sql#78]
Hello folks! I've been participating in the various conversations around `telemetry` project, and I'd like to propose a change in the Event naming scheme that Ecto uses...

Right now it is configurable, so a user could change the event name to `[:my_app, :query]`. The impact of this is that it's impossible to attach to Ecto events w/o some configuration input from the user (since the event name is needed up-front to subscribe to the event stream. This situation doesn't improve the ergonomics at all, but does introduce a burden on the user & the reporter library.

I'd like to suggest that the event name be static, so that all event name sent from Telemetry for Ecto instrumentation is always the same, for example:

```
:telemetry.execute([:ecto, :query], total, metadata)
```

This change would mean that the raw events are discoverable & consumable directly by Telemetry reporters, while still allowing customization via metadata or through `telemetry_metrics`. Any user-specific info, like a custom metric name or the Ecto Repo belong in the metadata. 

Thanks!

cc/ @josevalim @arkgil

FYI, I think this should also be the generic recommendation for building Telemetry instrumentation into libraries.

**Comment by josevalim** [comment]
I am afraid this boat has sailed for Ecto for two reasons:

1. backwards compatibility

2. people have explicitly asked for an ability to give different event names per query, which means that your tooling needs to be able to handle extra queries anyway

**Comment by binaryseed** [comment]
Would it be possible to publish the events in 2 streams then? The standard `[:ecto, :query]` and the custom one?

Also, do you know why people wanted to have custom event names? I'm unclear what their use case would be..

**Comment by josevalim** [comment]
> Also, do you know why people wanted to have custom event names? I'm unclear what their use case would be..

They want to segregate long queries to not skew some of their measurements. Let's go with a simple event for now and we will potentially evolve it to two later on.

**Comment by binaryseed** [comment]
ok, thanks!
