### ISSUE TITLE
** (Postgrex.Error) ERROR 3B001 (invalid_savepoint_specification) no such savepoint

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto_sql#8]
### Environment

* Ecto version (mix deps): master
* Database adapter and version (mix deps): postgrex master

### Current behavior

I'm getting this error:

```
15:41:37.483 [debug] QUERY ERROR db=1.1ms queue=1.9ms
INSERT INTO "packages" ("meta","name") VALUES ($1,$2) RETURNING "id" [%{}, "foo"]

15:41:37.484 [error] Postgrex.Protocol (#PID<0.294.0>) disconnected: ** (Postgrex.Error) ERROR 3B001 (invalid_savepoint_specification) no such savepoint


  1) test greets the world (ExampleMasterTest)
     test/example_master_test.exs:10
     ** (Postgrex.Error) ERROR 3B001 (invalid_savepoint_specification) no such savepoint
     code: Repo.insert!(Package.changeset(%Package{}, %{name: "foo", meta: %{}}))
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:584: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:600: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:226: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
       (ecto) lib/ecto/repo/schema.ex:128: Ecto.Repo.Schema.insert!/3
       test/example_master_test.exs:11: (test)
```

Turns out I forgot to set `config :postgrex, json_library: ...` which is needed for map field. When I set it, it's fine. It's possible I've somehow misconfigured the repo too.

Repo to reproduce: https://github.com/wojtekmach/example_master

### Expected behavior

Perhaps a compile-time error from Ecto.Adapters.Postgres that json library is missing.

**Comment by fishcakez** [comment]
This looks like a bug in `cached_statement` implementation in postgrex. Quickly looking at the code suggests the savepoint isn't created on prepare when mode is `:savepoint` and query is in the cache.

**Comment by josevalim** [comment]
@fishcakez good catch. What do you think we should do in this case? create the savepoint or avoid the rolling back to the savepoint that does not exist?

**Comment by fishcakez** [comment]
@josevalim when we execute we need to create a savepoint, so we can't avoid it. I think it is much simpler code wise if we create it in the `handle_prepare` callback.

**Comment by josevalim** [comment]
Fixed in https://github.com/elixir-ecto/postgrex/pull/416.
