### ISSUE TITLE
Breaking change in migrations when upgrading 3.0.3 -> 3.0.5

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto_sql#80]
### Environment
Upgrading
* ecto: 3.0.5 -> 3.0.7
* ecto_sql: 3.0.3 -> 3.0.5

### Intro
One of our developers created migrations with different file names but with the same module name inside. These migrations contain different instructions inside.
From logs:
```
[info] == Running 20180107124803 App.Repo.Migrations.AddCoherenceToUser.change/0 forward
...
[info] == Running 20180123144846 App.Repo.Migrations.AddCoherenceToUser.change/0 forward
```

### Previous behavior
It worked well

### Current behavior
The first migration runs twice with different timestamps, and we have conflicts. 

### Expected behavior
Allow conflicting module names or show warning.

P. S: Is it safe to just rename a module?

Edited: okay, a warning is shown.

**Comment by josevalim** [comment]
No, it is not safe to rename a module. We have no guarantees migrations will behave as expected if you rename modules, the behaviour may change on any release because that's unexpected and therefore the behaviour is unspecified.

**Comment by fuelen** [comment]
Then what could be a solution in our case?

**Comment by josevalim** [comment]
You should be able to just rename the module.

**Comment by fuelen** [comment]
Thanks
