### ISSUE TITLE
Ecto.Adapters.Postgres.structure_load delegates to `psql`

### ISSUE THREAD

**Issue by jjl** [elixir-ecto/ecto_sql#81]
Present in master.

This means that we need to ship the psql tool to where we build our database, which is less than ideal.

### Current behavior

Ecto.Adapters.Postgres.structure_load delegates to `psql`

### Expected behavior

Ecto.Adapters.Postgres.structure_load performs the work without reliance on the `psql` tool.

**Comment by josevalim** [comment]
Hi @jjl ! We understand. This is not something we plan to work on ourselves but if somebody is willing to contribute an implementation that uses a regular connection we will be glad to review and merge it if appropriate. Thanks!

**Comment by jjl** [comment]
Were I to go ahead and contribute such a change, can you think of any reason why this hasn't been done until now which might affect my decision?

**Comment by josevalim** [comment]
As far as I know it was always implemented like that: https://github.com/elixir-ecto/ecto/pull/901

Maybe there is something that prohibits it but we don't know what that is yet. :) So giving it a try would be welcome!

**Comment by jjl** [comment]
Cool, thanks. I'll discuss and see if I can justify this.

**Comment by paulobezerr** [comment]
@josevalim, if we keep this issue open someone that wants to contribute with this project can see easier and enhance this behaviour.
