### ISSUE TITLE
Failing migration left db in inconsistent state

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-ecto/ecto_sql#86]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):PostgreSQL 9.6
* Ecto version (mix deps): ecto 3.0.7, ecto-sql 3.0.5
* Database adapter and version (mix deps): postgrex 0.14.1
* Operating system: Linux (debian)

### Current behavior

On our production system we run migrations as pre startup task. We deployed a new version of our app with several migrations to be applied (Let's call them M1, M2, M3, ..). From what was logged we can see that M1 was applied successfully. M2 started and took too long to complete before our app health check failed and the app was killed. After restart the migrations were supposed to rerun but failed due to inconsistent state in schema_migrations.

Logs of the first run
```
Running migrations
Loading my_app..
Starting dependencies..
Starting repos..
Running migrations for my_app
11:24:22.407 [info] == Running 20190131122210 MyApp.Repo.Migrations.M1.change/0 forward
11:24:22.408 [info] create table table_1
11:24:22.436 [info] create index table_1_column_1_index
11:24:22.440 [info] alter table table_2
11:24:22.447 [info] execute "DROP MATERIALIZED VIEW view_1;"
11:24:22.456 [info] == Migrated 20190131122210 in 0.0s
11:24:22.523 [info] == Running 20190131122211 MyApp.Repo.Migrations.M2.change/0 forward
11:24:22.524 [info] execute "update table_3 set status = 'status_1' where status = 'status_2';"
(killed by health check policy)
```
Logs of the second run
```
Loading my_app..
Starting dependencies..
Starting repos..
Running migrations for my_app
11:28:48.228 [info] == Running 20190131122210 MyApp.Repo.Migrations.M1.change/0 forward
11:28:48.229 [info] create table table_1
[31m▸ Evaluation failed with: ERROR 42P07 (duplicate_table) relation "table_1" already exists[0m
(returned non 0 exit code)
```
### Expected behavior

Migration should be marked as applied even if app terminates during applying of following migrations

**Comment by josevalim** [comment]
I have pushed a fix to v3.0, please give it a try. Thanks!

**Comment by lukaszsamson** [comment]
@josevalim Thanks for the quick fix. I checked it locally and it seems to be working fine. Obviously I'm not going to retest failing migrations on production deliberately. Moreover there are some breaking changes in telemetry 0.4

**Comment by josevalim** [comment]
If you try the v3.0 branch  it should be backwards compatible and without the telemetry changes. :)
